### ISSUE TITLE
How to export onnx model with dynamic batchsize?

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmpose#1090]
How to export onnx model with dynamic batchsize?

```
python tools/deployment/pytorch2onnx.py configs/body/2d/shufflenetv2_coco_384x288.py weights/shufflenetv2_coco_384x288-fb38ac3a_20200921.pth --shape -1 3 384 288 --output-file shufflenetv2_body.onnx --opset-version 11
load checkpoint from local path: weights/shufflenetv2_coco_384x288-fb38ac3a_20200921.pth
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 146, in <module>
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 63, in pytorch2onnx
    one_img = torch.randn(input_shape)
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 3, 384, 288]

```

**Comment by ly015** [comment]
You can set `dynamic_axes` arguments for torch.onnx.export used in `tools/deployment/pytorch2onnx.py` [here](https://github.com/open-mmlab/mmpose/blob/93c3a742c540dfb4ca515ad545cef705a07d90b4/tools/deployment/pytorch2onnx.py#L66-L73).

For example:

```python
dynamic_axes = {'img': {0: 'batch'}, 'keypoint': {0: 'batch'}}
torch.onnx.export(
        model,
        one_img,
        output_file,
        export_params=True,
        keep_initializers_as_inputs=True,
        verbose=show,
        opset_version=opset_version,
        input_names=['img'],
        output_names=['keypoint'],
        dynamic_axes=dynamic_axes)
```

Please refer to the [pytorch docs](https://pytorch.org/docs/stable/onnx.html) for more information.
