### ISSUE TITLE
KeyError: '/0000115_img.png'

### ISSUE THREAD

**Issue by YuktiADY** [open-mmlab/mmpose#1154]
I am getting the below error while training on my custom dataset.

Traceback (most recent call last):
  File "./mmpose/tools/train.py", line 170, in <module>
    main()
  File "./mmpose/tools/train.py", line 166, in main
    meta=meta)
  File "/home/yukti/mmpose/mmpose/mmpose/apis/train.py", line 192, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/yukti/mmpose/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yukti/mmpose/mmcv/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/yukti/mmpose/mmcv/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/yukti/mmpose/mmcv/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/yukti/mmpose/mmcv/mmcv/runner/hooks/evaluation.py", line 505, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/yukti/mmpose/mmpose/mmpose/core/evaluation/eval_hooks.py", line 139, in evaluate
    **self.eval_kwargs)
  File "/home/yukti/mmpose/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 274, in evaluate
    image_id = self.name2id[image_paths[i][len(self.img_prefix):]]
KeyError: '/0000115_img.png'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 902238) of binary: /home/yukti/anaconda3/envs/open-mmlab/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

Please fin my annotation file :

**Comment by jin-s13** [comment]
Please check the image path again, especially "img_prefix" in config.

**Comment by YuktiADY** [comment]
> Please check the image path again, especially "img_prefix" in config.

Yes I checked it looks fine.

**Comment by YuktiADY** [comment]
> Please check the image path again, especially "img_prefix" in config.

Could you guide me how to fix this error, I am stuck here and cant proceed with the training ?

I made changes in the topdown_coco_dataset.py , passing empty value in (self.img_prefix)
image_id = self.name2id[image_paths[i][len(self.img_prefix):]]
my code : image_id = self.name2id[image_paths[i][len():]]

**Comment by YuktiADY** [comment]
solved by adding `/` at the end of `img_prefix` in the data/val section in the config py.
