### ISSUE TITLE
AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params'

### ISSUE THREAD

**Issue by supersarr** [open-mmlab/mmpose#1331]
This happens when I train with multiple GPUs, but I can work normally with a single GPU

Traceback (most recent call last):
  File "./tools/train.py", line 196, in <module>
    main()
  File "./tools/train.py", line 185, in main
    train_model(
  File "/data/hxr/mmpose/mmpose/apis/train.py", line 205, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/root/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/root/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 48, in train_step
    self._sync_params()
  File "/root/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 28325 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 28324) of binary: /root/anaconda3/envs/mmlab/bin/python

RTX 3090
CUDA11.3 Torch 1.11.0

However, when I used geforce 1080ti, I didn't encounter this problem

**Comment by ly015** [comment]
This issue is likely to be caused by incompatibility versions of mmcv and PyTorch. Please ensure that you have the mmcv-full>=1.4.8 installed to support torch1.11.0.

**Comment by supersarr** [comment]
> 这个问题很可能是由 mmcv 和 PyTorch 的不兼容版本引起的。请确保您已安装 mmcv-full>=1.4.8 以支持 torch1.11.0。



> This issue is likely to be caused by incompatibility versions of mmcv and PyTorch. Please ensure that you have the mmcv-full>=1.4.8 installed to support torch1.11.0.

thank you very much
