### ISSUE TITLE
about hrformer model to onnx 

### ISSUE THREAD

**Issue by supersarr** [open-mmlab/mmpose#1342]
i want to hrformer model to onnx ,but 
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 169, in <module>
    verify=args.verify)
  File "tools/deployment/pytorch2onnx.py", line 78, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/hxr/mmpose/mmpose/models/detectors/top_down.py", line 213, in forward_dummy
    output = self.backbone(img)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/hxr/mmpose/mmpose/models/backbones/hrnet.py", line 564, in forward
    x = self.norm1(x)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 134, in forward
    self._check_input_dim(input)
  File "/root/anaconda3/envs/mmpose/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 513, in _check_input_dim
    raise ValueError("expected 5D input (got {}D input)".format(input.dim()))
ValueError: expected 5D input (got 4D input)

The conversion of other models is normal

**Comment by ly015** [comment]
Hi, thanks for your feedback. Some of the models in our model zoo are not supported for export to onnx due to their model architecture or data pipeline. We will add a list of exportable models to the documentation.

And please note that pytorch2onnx in MMPose is no longer maintained and will be deprecated in the future. We have [MMDeploy](https://github.com/open-mmlab/mmdeploy) to support model deployment for all OpenMMLab codebases including MMPose. You can find details about supported models and user guides in their [documentation](https://mmdeploy.readthedocs.io/), and raise issues to request support for the models you would like to use.

**Comment by ly015** [comment]
We haven't tested converting HRFormer to onnx, but based on your description there seem to be some problems. Maybe you can try other models like HRNet.

**Comment by supersarr** [comment]
> We haven't tested converting HRFormer to onnx, but based on your description there seem to be some problems. Maybe you can try other models like HRNet.

ok thank you for your reply.
