### ISSUE TITLE
Error occurred when I tried to verify my installation

### ISSUE THREAD

**Issue by SecretMG** [open-mmlab/mmpose#1442]
After I finished the INSTALLATION step, I tried to VERIFY it following the instructions, but such error occurred to me like: 

> Traceback (most recent call last):
  File "config.py", line 5, in <module>
    pose_model = init_pose_model(config_file, checkpoint_file, device='cuda:0')  # or device='cuda:0'
  File "xxx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmpose/apis/inference.py", line 38, in init_pose_model
    config = mmcv.Config.fromfile(config)
  File "xxx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "xxx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 252, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "xxx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 183, in _file2dict
    check_file_exist(filename)
  File "xxx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "xxx/\_base\_/default_runtime.py" does not exist

I've tried both the PIP type of installation and PROJECT type of installation, but the error keeps to jump on me.
I wonder the possible reasons for it, thanks a lot!

**Comment by Ben-Louis** [comment]
Did you use the config file `associative_embedding_hrnet_w32_coco_512x512.py` as stated in the installation guideline or any other config file?

**Comment by ly015** [comment]
This doesn't seem like an installation issue.
Could you please check the `_base_` field in your config and ensure they are valid relative paths to existing files? By default, we place all model configs in `/configs/xxx/` and base configs in `/config/_base_`. If the model config has been moved, the `_base_` paths need to be modified accordingly.

**Comment by SecretMG** [comment]
Thank you guys, I've solved it based on your suggestions! Thank you again!
