### ISSUE TITLE
`image_size` in results passed to `top_down_transform` is empty, can't retrieve aspect_ratio (too many indices for array)

### ISSUE THREAD

**Issue by oxysoft** [open-mmlab/mmpose#1521]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

```
❮ python top_down_video_demo_full_frame_without_det.py associative_embedding_hrnet_w32_coco_512x5
12.py hrnet_w32_coco_512x512-bcb8c247_20200816.pth --video-path video.mp4 --out-video-root .
Initializing model...
load checkpoint from local path: hrnet_w32_coco_512x512-bcb8c247_20200816.pth
Running inference...
[                                                  ] 0/211, elapsed: 0s, ETA:Traceback (most recent call last):
  File "top_down_video_demo_full_frame_without_det.py", line 138, in <module>
    main()
  File "top_down_video_demo_full_frame_without_det.py", line 100, in main
    pose_results, returned_outputs = inference_top_down_pose_model(
  File "/home/nuck/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/nuck/.conda/envs/openmmlab/lib/python3.8/site-packages/mmpose/apis/inference.py", line 392, in inference_top_down_pose_model
    poses, heatmap = _inference_single_pose_model(
  File "/home/nuck/.conda/envs/openmmlab/lib/python3.8/site-packages/mmpose/apis/inference.py", line 259, in _inference_single_pose_model
    data = test_pipeline(data)
  File "/home/nuck/.conda/envs/openmmlab/lib/python3.8/site-packages/mmpose/datasets/pipelines/shared_transform.py", line 107, in __call__
    data = t(data)
  File "/home/nuck/.conda/envs/openmmlab/lib/python3.8/site-packages/mmpose/datasets/pipelines/top_down_transform.py", line 46, in __call__
    aspect_ratio = image_size[0] / image_size[1]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

**Reproduction**

1. Follow the instructions to install with conda and pip
2. Record a video from my phone
3. run the `top_down_video_demo_full_frame_without_det` demo

**Environment**

```
sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1660 SUPER
CUDA_HOME: /opt/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 12.1.0
PyTorch: 1.12.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.0
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMPose: 0.28.0+ceb6192
```

**Comment by jin-s13** [comment]
Hi, `top_down_video_demo_full_frame_without_det.py` this only works for top-down approaches, while associative embedding is bottom-up.

**Comment by oxysoft** [comment]
Thanks! There should be a more graceful error message, mmpose will be used by non-ML engineers as a lib for making other stuff. I think a page describing each model and their advantages in general would be useful. I'm a bit lost and don't know which ones I should use, hence I just stuck with the default from the tutorial for this.

**Comment by jin-s13** [comment]
Good suggestions!
