### ISSUE TITLE
problem with multi-gpu training

### ISSUE THREAD

**Issue by khanhha** [open-mmlab/mmpose#156]
Hello,

Could you please help me with this multi-GPU training problem?

The training is started on AWS g4dn.12xlarge, 4 GPUs with 48 CPUs.

Here is the training command line

**bash ./tools/dist_train.sh ./configs/bottom_up/higherhrnet/coco/higher_hrnet32_coco22_640x640.py 4 --autoscale-lr**

And here is the error I got. 

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch_p36/bin/python', '-u', './tools/train.py', '--local_rank=3', './configs/bottom_up/higherhrnet/coco/higher_hrnet32_coco22_640x640.py', '--launcher', 'pytorch', '--autoscale-lr']' died with <Signals.SIGKILL: 9>.

 File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 33 leaked semaphores to clean up at shutdown
  len(cache))

I look forward to hearing from you soon

Best

**Comment by khanhha** [comment]
Hello, 
the issue was solved by changing workers_per_gpu from 8 to 1
    samples_per_gpu=6,
    workers_per_gpu=1,

I am not sure why.

**Comment by innerlee** [comment]
i guess the shared mem is not large enough
