### ISSUE TITLE
Test Res50 in COCO. get an error:OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by lllrj** [open-mmlab/mmpose#1563]
I newly installed mmpose on win10, when testing res50 on coco dataset I enter the following code:
`>python tools\test.py configs/body/2d_kpt_sview_rgb_img/deeppose/coco/res50_coco_256x192.py checkpoints/deeppose_res50_coco_256x192-f6de6c0e_20210205.pth`

The following error occurred:
. . .
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 104125/104125, 222.9 task/s, elapsed: 467s, ETA:     0sLoading and preparing results...
DONE (t=3.13s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
Traceback (most recent call last):
  File "tools\test.py", line 184, in <module>
    main()
  File "tools\test.py", line 178, in main
    results = dataset.evaluate(outputs, cfg.work_dir, **eval_config)
  File "C:\Users\MyPC\Anaconda3\envs\mm\lib\site-packages\mmcv\utils\misc.py", line 330, in new_func
    output = old_func(*args, **kwargs)
  File "d:\mm\mmpose\mmpose\datasets\datasets\top_down\topdown_coco_dataset.py", line 326, in evaluate
    info_str = self._do_python_keypoint_eval(res_file)
  File "d:\mm\mmpose\mmpose\datasets\datasets\top_down\topdown_coco_dataset.py", line 389, in _do_python_keypoint_eval
    coco_eval.evaluate()
  File "C:\Users\MyPC\Anaconda3\envs\mm\lib\site-packages\xtcocotools\cocoeval.py", line 262, in evaluate
    self.evalImgs = [evaluateImg(imgId, catId, areaRng, maxDet)
  File "C:\Users\MyPC\Anaconda3\envs\mm\lib\site-packages\xtcocotools\cocoeval.py", line 262, in <listcomp>
    self.evalImgs = [evaluateImg(imgId, catId, areaRng, maxDet)
  File "C:\Users\MyPC\Anaconda3\envs\mm\lib\site-packages\xtcocotools\cocoeval.py", line 456, in evaluateImg
    dtm[tind, dind]  = gt[m]['id']
OverflowError: Python int too large to convert to C long

Then I re-tested on mpii with no problems and the pred.mat was output correctly.
So I want to know how to solve the error when running test.py on the coco dataset
Below is my environment (I tried two different mmcv-full versions and neither worked)
python=3.8
pytorch=1.10
torchvision=0.11.1
cudatoolkit=11.3
mmcv-full=1.6.1/1.3.9

**Comment by liqikai9** [comment]
Hi, what is the version of your xtcocotools?
FYI, you can run `pip show xtcocotools` to get the version information.

**Comment by lllrj** [comment]
> Hi, what is the version of your xtcocotools? FYI, you can run `pip show xtcocotools` to get the version information.

xtcocotools=1.12

**Comment by liqikai9** [comment]
I see. This issue may be related to the precision of dtype in different platforms. 

You may refer to [this PR on xtcocotools](https://github.com/jin-s13/xtcocoapi/pull/27), and reinstall xtcocotools  from source following this: https://github.com/jin-s13/xtcocoapi#installation

**Comment by lllrj** [comment]
Thank you!I will take your advice and let you know the result

**Comment by lllrj** [comment]
> Thank you!I will take your advice and let you know the result

According to the modification in that PR, I made the same modification and got a normal result.
Thanks for solving a problem that has been bothering me for two days！

**Comment by liqikai9** [comment]
Thanks for your reply, too! If you have any other questions, please feel free to raise an issue here~

**Comment by LjIA26** [comment]
Hello! 

I also got the same error, even after installing xtcocoapi from source. 




[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 104125/104125, 33.9 task/s, elapsed: 3070s, ETA:     0sLoading and preparing results...
DONE (t=5.32s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 190, in main
    train_model(
  File "d:\mmpose\mmpose\apis\train.py", line 213, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 277, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 367, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\mmcv\utils\misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "d:\mmpose\mmpose\datasets\datasets\top_down\topdown_coco_dataset.py", line 326, in evaluate
    info_str = self._do_python_keypoint_eval(res_file)
  File "d:\mmpose\mmpose\datasets\datasets\top_down\topdown_coco_dataset.py", line 389, in _do_python_keypoint_eval
    coco_eval.evaluate()
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\xtcocotools\cocoeval.py", line 262, in evaluate
    self.evalImgs = [evaluateImg(imgId, catId, areaRng, maxDet)
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\xtcocotools\cocoeval.py", line 262, in <listcomp>
    self.evalImgs = [evaluateImg(imgId, catId, areaRng, maxDet)
  File "C:\Users\LJ\anaconda3\envs\poseE\lib\site-packages\xtcocotools\cocoeval.py", line 456, in evaluateImg
    dtm[tind, dind]  = gt[m]['id']
OverflowError: Python int too large to convert to C long

**Comment by LjIA26** [comment]
I updated the cudatools from 10.2 to 11.3 and then installed xtcocotools from source, and it still didn't work.

**Comment by liqikai9** [comment]
@LjIA26 
What is the command that you run to reinstall xtcocotools? Did you uninstall the original xtcocotools first?
