### ISSUE TITLE
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 3

### ISSUE THREAD

**Issue by EugeneKok97** [open-mmlab/mmpose#1614]
Hi guys,I'm attempting to use mmpose to train on my custom dataset in the COCO format. My custom dataset is a set of cropped images of single apples with the size of 96 x 96. The goal is to detect only two keypoints: stem and calyx of the apple. However, only one keypoint is present for the most of the time. I managed to train Associative Embedding + HigherHRNet and Associative Embedding + Resnet50 without any problem. However, I'm getting the following error as I attempt to train the Associative Embedding + Hourglass network. I've been stucked with this for days, any help and guidance is very much appreciated!

**Error Traceback:**
```
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 191, in main
    train_model(
  File "/home/lmga-titanx/mmpose/mmpose/apis/train.py", line 213, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/lmga-titanx/mmpose/mmpose/models/detectors/base.py", line 104, in train_step
    losses = self.forward(**data_batch)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/lmga-titanx/mmpose/mmpose/models/detectors/associative_embedding.py", line 135, in forward
    return self.forward_train(img, targets, masks, joints, img_metas,
  File "/home/lmga-titanx/mmpose/mmpose/models/detectors/associative_embedding.py", line 174, in forward_train
    output = self.backbone(img)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmga-titanx/mmpose/mmpose/models/backbones/hourglass_ae.py", line 203, in forward
    hourglass_feat = single_hourglass(inter_feat)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmga-titanx/mmpose/mmpose/models/backbones/hourglass_ae.py", line 63, in forward
    low2 = self.low2(low1)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmga-titanx/mmpose/mmpose/models/backbones/hourglass_ae.py", line 63, in forward
    low2 = self.low2(low1)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmga-titanx/mmpose/mmpose/models/backbones/hourglass_ae.py", line 63, in forward
    low2 = self.low2(low1)
  File "/home/lmga-titanx/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmga-titanx/mmpose/mmpose/models/backbones/hourglass_ae.py", line 66, in forward
    return up1 + up2
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 3
```
**Config:**
```
log_level = 'INFO'
load_from = None
resume_from = None
dist_params = dict(backend='nccl')
workflow = [('train', 1)]
checkpoint_config = dict(interval=50)
evaluation = dict(interval=50, metric='mAP', save_best='AP')
optimizer = dict(type='Adam', lr=0.0015)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=100,
    warmup_ratio=0.001,
    step=[200, 260])
log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')])
total_epochs = 300
channel_cfg = dict(
    dataset_joints=2, dataset_channel=[[0, 1]], inference_channel=[0, 1])
data_cfg = dict(
    image_size=96,
    base_size=48,
    base_sigma=2,
    heatmap_size=[24],
    num_joints=2,
    dataset_channel=[[0, 1]],
    inference_channel=[0, 1],
    num_scales=1,
    scale_aware_sigma=False)
model = dict(
    type='AssociativeEmbedding',
    pretrained=None,
    backbone=dict(type='HourglassAENet', num_stacks=4, out_channels=34),
    keypoint_head=dict(
        type='AEMultiStageHead',
        in_channels=34,
        out_channels=34,
        num_stages=4,
        num_deconv_layers=0,
        extra=dict(final_conv_kernel=0),
        loss_keypoint=dict(
            type='MultiLossFactory',
            num_joints=2,
            num_stages=4,
            ae_loss_type='exp',
            with_heatmaps_loss=[True, True, True, True],
            with_ae_loss=[True, True, True, True],
            push_loss_factor=[0.001, 0.001, 0.001, 0.001],
            pull_loss_factor=[0.001, 0.001, 0.001, 0.001],
            heatmaps_loss_factor=[1.0, 1.0, 1.0, 1.0])),
    train_cfg=dict(num_joints=2, img_size=96),
    test_cfg=dict(
        num_joints=2,
        max_num_people=30,
        scale_factor=[1],
        with_heatmaps=[True, True, True, True],
        with_ae=[True, True, True, True],
        select_output_index=[3],
        project2image=True,
        nms_kernel=5,
        nms_padding=2,
        tag_per_joint=True,
        detection_threshold=0.1,
        tag_threshold=1,
        use_detection_val=True,
        ignore_too_much=False,
        adjust=True,
        refine=True,
        flip_test=True))
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='BottomUpRandomAffine',
        rot_factor=30,
        scale_factor=[0.75, 1.5],
        scale_type='short',
        trans_factor=40),
    dict(type='BottomUpRandomFlip', flip_prob=0.5),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='MultitaskGatherTarget',
        pipeline_list=[[{
            'type': 'BottomUpGenerateTarget',
            'sigma': 2,
            'max_num_people': 30
        }]],
        pipeline_indices=[0, 0, 0, 0],
        keys=['targets', 'masks', 'joints']),
    dict(
        type='Collect',
        keys=['img', 'joints', 'targets', 'masks'],
        meta_keys=[])
]
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
    dict(
        type='BottomUpResizeAlign',
        transforms=[
            dict(type='ToTensor'),
            dict(
                type='NormalizeTensor',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225])
        ]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'aug_data', 'test_scale_factor', 'base_size',
            'center', 'scale', 'flip_index'
        ])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
    dict(
        type='BottomUpResizeAlign',
        transforms=[
            dict(type='ToTensor'),
            dict(
                type='NormalizeTensor',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225])
        ]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'aug_data', 'test_scale_factor', 'base_size',
            'center', 'scale', 'flip_index'
        ])
]
data_root = '/home/lmga-titanx/mmpose/data/testing_set'
data = dict(
    train_dataloader=dict(samples_per_gpu=6),
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    workers_per_gpu=2,
    train=dict(
        type='BottomUpCocoDataset',
        ann_file=
        '/home/lmga-titanx/mmpose/data/testing_set/annotations/person_keypoints_train.json',
        img_prefix='/home/lmga-titanx/mmpose/data/testing_set/images/',
        data_cfg=dict(
            image_size=96,
            base_size=48,
            base_sigma=2,
            heatmap_size=[24],
            num_joints=2,
            dataset_channel=[[0, 1]],
            inference_channel=[0, 1],
            num_scales=1,
            scale_aware_sigma=False),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='BottomUpRandomAffine',
                rot_factor=30,
                scale_factor=[0.75, 1.5],
                scale_type='short',
                trans_factor=40),
            dict(type='BottomUpRandomFlip', flip_prob=0.5),
            dict(type='ToTensor'),
            dict(
                type='NormalizeTensor',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]),
            dict(
                type='MultitaskGatherTarget',
                pipeline_list=[[{
                    'type': 'BottomUpGenerateTarget',
                    'sigma': 2,
                    'max_num_people': 30
                }]],
                pipeline_indices=[0, 0, 0, 0],
                keys=['targets', 'masks', 'joints']),
            dict(
                type='Collect',
                keys=['img', 'joints', 'targets', 'masks'],
                meta_keys=[])
        ],
        dataset_info=dict(
            dataset_name='apple_calyx_coco',
            paper_info=dict(
                author=
                'Lin, Tsung-Yi and Maire, Michael and Belongie, Serge and Hays, James and Perona, Pietro and Ramanan, Deva and Doll{\'a}r, Piotr and Zitnick, C Lawrence',
                title='Microsoft coco: Common objects in context',
                container='European conference on computer vision',
                year='2014',
                homepage='http://cocodataset.org/'),
            keypoint_info=dict({
                0:
                dict(name='calyx', id=0, color=[0, 0, 255], swap=''),
                1:
                dict(name='stem', id=1, color=[255, 0, 0], swap='')
            }),
            skeleton_info=dict(),
            joint_weights=[1.0, 1.0],
            sigmas=[0.05, 0.05])),
    val=dict(
        type='BottomUpCocoDataset',
        ann_file=
        '/home/lmga-titanx/mmpose/data/testing_set/annotations/person_keypoints_valid.json',
        img_prefix='/home/lmga-titanx/mmpose/data/testing_set/images/',
        data_cfg=dict(
            image_size=96,
            base_size=48,
            base_sigma=2,
            heatmap_size=[24],
            num_joints=2,
            dataset_channel=[[0, 1]],
            inference_channel=[0, 1],
            num_scales=1,
            scale_aware_sigma=False),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
            dict(
                type='BottomUpResizeAlign',
                transforms=[
                    dict(type='ToTensor'),
                    dict(
                        type='NormalizeTensor',
                        mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
                ]),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'image_file', 'aug_data', 'test_scale_factor', 'base_size',
                    'center', 'scale', 'flip_index'
                ])
        ],
        dataset_info=dict(
            dataset_name='apple_calyx_coco',
            paper_info=dict(
                author=
                'Lin, Tsung-Yi and Maire, Michael and Belongie, Serge and Hays, James and Perona, Pietro and Ramanan, Deva and Doll{\'a}r, Piotr and Zitnick, C Lawrence',
                title='Microsoft coco: Common objects in context',
                container='European conference on computer vision',
                year='2014',
                homepage='http://cocodataset.org/'),
            keypoint_info=dict({
                0:
                dict(name='calyx', id=0, color=[0, 0, 255], swap=''),
                1:
                dict(name='stem', id=1, color=[255, 0, 0], swap='')
            }),
            skeleton_info=dict(),
            joint_weights=[1.0, 1.0],
            sigmas=[0.05, 0.05])),
    test=dict(
        type='BottomUpCocoDataset',
        ann_file=
        '/home/lmga-titanx/mmpose/data/testing_set/annotations/person_keypoints_test.json',
        img_prefix='/home/lmga-titanx/mmpose/data/testing_set/images/',
        data_cfg=dict(
            image_size=96,
            base_size=48,
            base_sigma=2,
            heatmap_size=[24],
            num_joints=2,
            dataset_channel=[[0, 1]],
            inference_channel=[0, 1],
            num_scales=1,
            scale_aware_sigma=False),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
            dict(
                type='BottomUpResizeAlign',
                transforms=[
                    dict(type='ToTensor'),
                    dict(
                        type='NormalizeTensor',
                        mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
                ]),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'image_file', 'aug_data', 'test_scale_factor', 'base_size',
                    'center', 'scale', 'flip_index'
                ])
        ],
        dataset_info=dict(
            dataset_name='apple_calyx_coco',
            paper_info=dict(
                author=
                'Lin, Tsung-Yi and Maire, Michael and Belongie, Serge and Hays, James and Perona, Pietro and Ramanan, Deva and Doll{\'a}r, Piotr and Zitnick, C Lawrence',
                title='Microsoft coco: Common objects in context',
                container='European conference on computer vision',
                year='2014',
                homepage='http://cocodataset.org/'),
            keypoint_info=dict({
                0:
                dict(name='calyx', id=0, color=[0, 0, 255], swap=''),
                1:
                dict(name='stem', id=1, color=[255, 0, 0], swap='')
            }),
            skeleton_info=dict(),
            joint_weights=[1.0, 1.0],
            sigmas=[0.05, 0.05])))
work_dir = '/home/lmga-titanx/mmpose/work_dirs/bottomup/hourglass_ae_coco_96x96'
gpu_ids = [0]
```

**Comment by Ben-Louis** [comment]
The cause of the problem may be the input image size. You could try a large image size, such as 128, as it is a power of 2.

BTW, the `in_channels` and `out_channels` of backbone and head should be `2 * num_joints`. 34 is for COCO dataset whose instances have 17 joints.

**Comment by EugeneKok97** [comment]
> The cause of the problem may be the input image size. You could try a large image size, such as 128, as it is a power of 2.
> 
> BTW, the `in_channels` and `out_channels` of backbone and head should be `2 * num_joints`. 34 is for COCO dataset whose instances have 17 joints.

Thank you so much for your input! That has solved the problem. I will proceed to close the thread.
