### ISSUE TITLE
webcam api增加线程遇到问题

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmpose#1822]
webcam_demo.py中包含有四个线程，分别为input，det，pose，和display，其中前三个为分线程，display为主线程。我增加了一个分线程，用于读取激光雷达数据（防止读取雷达数据拖慢mmpose的整体推理速度），但增加线程后导致程序报错：

Exception in thread Thread-5:
Traceback (most recent call last):
  File "F:\Anaconda\envs\mmpose\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "F:\Anaconda\envs\mmpose\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:/mmpose-master/webcam_demo_7points_lidar1.py", line 296, in inference_pose
    dataset=dataset_name)
  File "F:\mmpose-master\mmpose\apis\inference.py", line 413, in inference_top_down_pose_model
    return_heatmap=return_heatmap)
  File "F:\mmpose-master\mmpose\apis\inference.py", line 297, in _inference_single_pose_model
    return_heatmap=return_heatmap)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Anaconda\envs\mmpose\lib\site-packages\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "F:\mmpose-master\mmpose\models\detectors\top_down.py", line 141, in forward
    img, img_metas, return_heatmap=return_heatmap, **kwargs)
  File "F:\mmpose-master\mmpose\models\detectors\top_down.py", line 186, in forward_test
    features_flipped, img_metas[0]['flip_pairs'])
  File "F:\mmpose-master\mmpose\models\heads\topdown_heatmap_simple_head.py", line 218, in inference_model
    target_type=self.target_type)
  File "F:\mmpose-master\mmpose\core\post_processing\post_transforms.py", line 142, in flip_back
    output_flipped_back[:, left, ...] = output_flipped[:, right, ...]
IndexError: index 4 is out of bounds for axis 1 with size 4

![微信截图_20221120163306](https://user-images.githubusercontent.com/95410252/202894368-fd05ee9c-3634-4fe4-8bb1-0cad405544c6.png)

代码如下：
![微信截图_20221120171602](https://user-images.githubusercontent.com/95410252/202894414-8989444c-f2a0-40b1-9d01-876d3ba50ef9.png)

求解，感谢开发大神解答！

**Comment by ly015** [comment]
这里看起来像是 flip_pair 不正确，关键点应该只有 4 个，对应 index 0-3，但 flip_pair 里出现了 4。可能需要检查一下使用的 pose model 的 config。

**Comment by ShaneCan** [comment]
> 这里看起来像是 flip_pair 不正确，关键点应该只有 4 个，对应 index 0-3，但 flip_pair 里出现了 4。可能需要检查一下使用的 pose model 的 config。

感谢亦宁，我犯了基础性错误，非线程问题，已解决！
