### ISSUE TITLE
There are some problems in the dev1.0 branch torch2onnx, some modules seem to be from the master branch?

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmpose#1824]
There is a problem with mmpose1.0 series export, the error seems to be that the environment is not compatible and the error is as follows:

1. Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 8, in <module>
    from mmpose.apis import init_pose_model
ImportError: cannot import name 'init_pose_model' from 'mmpose.apis' (/home/dell/bag-torch/darkpull/Paddle/mmpose/mmpose/apis/__init__.py)

2. After modification as follows:
pytorch2onnx.py

```py
# from mmpose.apis import init_pose_model
from mmpose.apis import init_model

```

Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 17, in <module>
    from mmcv.onnx.symbolic import register_extra_symbolics
ModuleNotFoundError: No module named 'mmcv.onnx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 19, in <module>
    raise NotImplementedError('please update mmcv to version>=1.0.4')
NotImplementedError: please update mmcv to version>=1.0.4

**Comment by ly015** [comment]
Thanks for using MMPose. Please note that `pytorch2onnx.py` is deprecated in MMPose and will be removed from 1.x. The model export and deployment are supported by [MMDepoly](https://github.com/open-mmlab/mmdeploy). Please refer to MMDeploy's documents for details:

- MMDeploy 1.x for MMPose 1.x: https://mmdeploy.readthedocs.io/en/dev-1.x/04-supported-codebases/mmpose.html
- MMDeploy 0.x for MMPose 0.x: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpose.html

**Comment by chen-del** [comment]
Okay, thank you. It can be exported and used normally. The main reason is that it is a little different from the master branch. I am not used to it for the time being?

**Comment by ly015** [comment]
Yes, MMPose 1.0 introduced major refactoring and unavoidable breaking changes. We have prepared a document to introduce the design of MMPose 1.0 and how to migrate from the old version. Hope it will help: https://mmpose.readthedocs.io/en/1.x/migration.html

**Comment by dengtianbi** [comment]
> Okay, thank you. It can be exported and used normally. The main reason is that it is a little different from the master branch. I am not used to it for the time being?

What code did you change to export onnx model in mmpose1.x ? I'm also having the same issue.
