### ISSUE TITLE
Failed to run demo

### ISSUE THREAD

**Issue by Billccx** [open-mmlab/mmpose#1827]
Hello!
I try to run the training demo with cmd
```
python tools/train.py configs/body_2d_keypoint/topdown_regression/coco/td-reg_res50_rle-8xb64-210e_coco-256x192.py
```

Unfortunately, I got the error as follows
```
11/21 14:32:31 - mmengine - INFO - Result has been saved to /home/ccx/code/python/mmpose-1.x/work_dirs/td-reg_res50_rle-8xb64-210e_coco-256x192/modules_statistic_results.json
11/21 14:32:34 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 154, in main
    runner = Runner.from_cfg(cfg)
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 434, in from_cfg
    runner = cls(
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.wrap_model(
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 848, in wrap_model
    model = revert_sync_batchnorm(model)
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmengine/model/utils.py", line 174, in revert_sync_batchnorm
    from mmcv.ops import SyncBatchNorm
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/ccx/anaconda3/envs/mmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ccx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs
```
Could you please tell me how to solve this problem?
Thanks in advance.

您好。我尝试运行教程中快速上手部分的[训练实例](https://mmpose.readthedocs.io/zh_CN/1.x/quick_run.html)，但是发生了错误，我不知道这是什么原因，环境的配置和安装均是严格按照教程来的，请问如何才能解决以上报错？谢谢

**Comment by ly015** [comment]
It seems that MMCV is not properly installed. Please uninstall MMCV and reinstall it following the documentation. We suggest installing MMPose 1.0 and its dependencies in a clean environment (without the old version MMPose or MMCV) to avoid conflicts.
