### ISSUE TITLE
Error with custom loss 

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#1958]
Hello, 

I have the following error when I run with a custom loss: 

```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

```

Traceback:
```
Traceback (most recent call last):
  File "D:\toolkit\mmpose\tools\train.py", line 161, in <module>
    main()
  File "D:\toolkit\mmpose\tools\train.py", line 157, in main
    runner.train()
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\runner\runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\runner\loops.py", line 90, in run
    self.run_epoch()
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\runner\loops.py", line 106, in run_epoch
    self.run_iter(idx, data_batch)
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\runner\loops.py", line 122, in run_iter
    outputs = self.runner.model.train_step(
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\model\base_model\base_model.py", line 116, in train_step
    optim_wrapper.update_params(parsed_losses)
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\optim\optimizer\optimizer_wrapper.py", line 184, in update_params
    self.backward(loss)
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\mmengine\optim\optimizer\optimizer_wrapper.py", line 208, in backward
    loss.backward(**kwargs)
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\LJ\anaconda3\envs\toolkit\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Is there a way to solve it? 

When I run it in my conda enviroment on its own, using random tensors it does work. 

Thank you.

**Comment by ly015** [comment]
As indicated by the error message, it seems that the custom loss is computed from tensors that do not require gradients. Could you please provide the implementation of this custom loss?

**Comment by LjIA26** [comment]
Hello! 
I added the loss.requires_grad_(true) and now it works.

**Comment by ly015** [comment]
Usually, it's unnecessary to explicitly set ``requires_grad_(True)`` for a loss tensor when it's calculated from other tensors with gradients (e.g. activations or model parameters). You may need to double-check the implementation of your loss module.
