### ISSUE TITLE
After added mmaction2 node into web_cam demo, different thread would change the default_scope value at the same time. It will cause error.

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmpose#2044]
When I add mmyolo and mmaction2 nodes to `webcam_demo.py `, it shows error bellow. I think the code miss lock when changing `default_scope`. 

/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/registry/utils.py:110: UserWarning: The current default scope "mmpose" is not "mmyolo", `init_default_scope` will force set the currentdefault scope to "mmyolo".
  warnings.warn('The current default scope '  # type: ignore
Exception in thread detector:
Traceback (most recent call last):
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/wushuchen/projects/mmyolo/mmpose/mmpose/apis/webcam/nodes/node.py", line 396, in run
    output_msg = self.process(input_msgs)
  File "/home/wushuchen/projects/mmyolo/mmpose/mmpose/apis/webcam/nodes/model_nodes/detector_node.py", line 116, in process
    preds = inference_detector(self.model, img)
  File "/home/wushuchen/projects/mmyolo/mmdetection/mmdet/apis/inference.py", line 152, in inference_detector
    test_pipeline = Compose(test_pipeline)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmcv/transforms/wrappers.py", line 65, in __init__
    transform = TRANSFORMS.build(transform)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 95, in build_from_cfg
    with registry.switch_scope_and_registry(scope) as registry:
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/registry/registry.py", line 280, in switch_scope_and_registry
    with DefaultScope.overwrite_default_scope(scope):
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/registry/default_scope.py", line 88, in overwrite_default_scope
    tmp = copy.deepcopy(cls._instance_dict)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/copy.py", line 305, in _reconstruct
    for key, value in dictiter:
RuntimeError: OrderedDict mutated during iteration

**Comment by ly015** [comment]
Thanks for using MMPose 1.0!
MMPose 1.0 involved major refactoring compared to MMPose 0.x. We ported the webcam API from the MMPose 0.x to MMPose 1.0, but there are still gaps so the webcam API may not work smoothly in MMPose 1.0. So we are considering a deprecation of webcam API.

We recommend using 'Inferencer', a unified model inference interface for MMPose which supports webcam input. Please checkout the [document](https://mmpose.readthedocs.io/en/1.x/user_guides/inference.html#out-of-the-box-inferencer).
