### ISSUE TITLE
some error about training my dataset with 5 keypoints on dekr 

### ISSUE THREAD

**Issue by lkvanny** [open-mmlab/mmpose#2070]
`2023-03-15 19:34:32,827 - mmpose - INFO - Set random seed to 1736424472, deterministic: False
load checkpoint from http path: https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w48-8ef0771d.pth
load checkpoint from http path: https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w48-8ef0771d.pth
2023-03-15 19:34:33,897 - mmpose - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: head.0.0.0.conv1.weight, head.0.0.0.bn1.weight, head.0.0.0.bn1.bias, head.0.0.0.bn1.running_mean, head.0.0.0.bn1.running_var, head.0.0.0.conv2.weight, head.0.0.0.bn2.weight, head.0.0.0.bn2.bias, head.0.0.0.bn2.running_mean, head.0.0.0.bn2.running_var, head.0.0.0.conv3.weight, head.0.0.0.bn3.weight, head.0.0.0.bn3.bias, head.0.0.0.bn3.running_mean, head.0.0.0.bn3.running_var, head.0.0.0.downsample.0.weight, head.0.0.0.downsample.1.weight, head.0.0.0.downsample.1.bias, head.0.0.0.downsample.1.running_mean, head.0.0.0.downsample.1.running_var, head.0.1.0.conv1.weight, head.0.1.0.bn1.weight, head.0.1.0.bn1.bias, head.0.1.0.bn1.running_mean, head.0.1.0.bn1.running_var, head.0.1.0.conv2.weight, head.0.1.0.bn2.weight, head.0.1.0.bn2.bias, head.0.1.0.bn2.running_mean, head.0.1.0.bn2.running_var, head.0.1.0.conv3.weight, head.0.1.0.bn3.weight, head.0.1.0.bn3.bias, head.0.1.0.bn3.running_mean, head.0.1.0.bn3.running_var, head.0.1.0.downsample.0.weight, head.0.1.0.downsample.1.weight, head.0.1.0.downsample.1.bias, head.0.1.0.downsample.1.running_mean, head.0.1.0.downsample.1.running_var, head.0.2.0.conv1.weight, head.0.2.0.bn1.weight, head.0.2.0.bn1.bias, head.0.2.0.bn1.running_mean, head.0.2.0.bn1.running_var, head.0.2.0.conv2.weight, head.0.2.0.bn2.weight, head.0.2.0.bn2.bias, head.0.2.0.bn2.running_mean, head.0.2.0.bn2.running_var, head.0.2.0.conv3.weight, head.0.2.0.bn3.weight, head.0.2.0.bn3.bias, head.0.2.0.bn3.running_mean, head.0.2.0.bn3.running_var, head.0.2.0.downsample.0.weight, head.0.2.0.downsample.1.weight, head.0.2.0.downsample.1.bias, head.0.2.0.downsample.1.running_mean, head.0.2.0.downsample.1.running_var, head.1.0.0.conv1.weight, head.1.0.0.bn1.weight, head.1.0.0.bn1.bias, head.1.0.0.bn1.running_mean, head.1.0.0.bn1.running_var, head.1.0.0.conv2.weight, head.1.0.0.bn2.weight, head.1.0.0.bn2.bias, head.1.0.0.bn2.running_mean, head.1.0.0.bn2.running_var, head.1.0.0.conv3.weight, head.1.0.0.bn3.weight, head.1.0.0.bn3.bias, head.1.0.0.bn3.running_mean, head.1.0.0.bn3.running_var, head.1.0.0.downsample.0.weight, head.1.0.0.downsample.1.weight, head.1.0.0.downsample.1.bias, head.1.0.0.downsample.1.running_mean, head.1.0.0.downsample.1.running_var, head.1.1.0.conv1.weight, head.1.1.0.bn1.weight, head.1.1.0.bn1.bias, head.1.1.0.bn1.running_mean, head.1.1.0.bn1.running_var, head.1.1.0.conv2.weight, head.1.1.0.bn2.weight, head.1.1.0.bn2.bias, head.1.1.0.bn2.running_mean, head.1.1.0.bn2.running_var, head.1.1.0.conv3.weight, head.1.1.0.bn3.weight, head.1.1.0.bn3.bias, head.1.1.0.bn3.running_mean, head.1.1.0.bn3.running_var, head.1.1.0.downsample.0.weight, head.1.1.0.downsample.1.weight, head.1.1.0.downsample.1.bias, head.1.1.0.downsample.1.running_mean, head.1.1.0.downsample.1.running_var, head.2.0.0.conv1.weight, head.2.0.0.bn1.weight, head.2.0.0.bn1.bias, head.2.0.0.bn1.running_mean, head.2.0.0.bn1.running_var, head.2.0.0.conv2.weight, head.2.0.0.bn2.weight, head.2.0.0.bn2.bias, head.2.0.0.bn2.running_mean, head.2.0.0.bn2.running_var, head.2.0.0.conv3.weight, head.2.0.0.bn3.weight, head.2.0.0.bn3.bias, head.2.0.0.bn3.running_mean, head.2.0.0.bn3.running_var, head.2.0.0.downsample.0.weight, head.2.0.0.downsample.1.weight, head.2.0.0.downsample.1.bias, head.2.0.0.downsample.1.running_mean, head.2.0.0.downsample.1.running_var, head.3.0.0.conv1.weight, head.3.0.0.bn1.weight, head.3.0.0.bn1.bias, head.3.0.0.bn1.running_mean, head.3.0.0.bn1.running_var, head.3.0.0.conv2.weight, head.3.0.0.bn2.weight, head.3.0.0.bn2.bias, head.3.0.0.bn2.running_mean, head.3.0.0.bn2.running_var, head.3.0.0.conv3.weight, head.3.0.0.bn3.weight, head.3.0.0.bn3.bias, head.3.0.0.bn3.running_mean, head.3.0.0.bn3.running_var, head.3.0.0.downsample.0.weight, head.3.0.0.downsample.1.weight, head.3.0.0.downsample.1.bias, head.3.0.0.downsample.1.running_mean, head.3.0.0.downsample.1.running_var, fc.weight, fc.bias

load checkpoint from http path: https://download.openmmlab.com/mmpose/pretrain_models/kpt_rescore_coco-33d58c5c.pth
load checkpoint from http path: https://download.openmmlab.com/mmpose/pretrain_models/kpt_rescore_coco-33d58c5c.pth
loading annotations into memory...
loading annotations into memory...
Done (t=0.03s)
creating index...
Done (t=0.03s)
creating index...
index created!
index created!
=> num_images: 1000
=> num_images: 1000
loading annotations into memory...
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
=> num_images: 250
Done (t=0.01s)
creating index...
2023-03-15 19:34:36,888 - mmpose - INFO - Start running, host: kunyu@server, work_dir: /mnt/data1/pywork/mmpose/work_dirs/hrnet_w48_worm_640x640
index created!
2023-03-15 19:34:36,889 - mmpose - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(NORMAL      ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) DistSamplerSeedHook                
(NORMAL      ) DistEvalHook                       
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) DistEvalHook                       
(LOW         ) IterTimerHook                      
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(NORMAL      ) DistEvalHook                       
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(NORMAL      ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(NORMAL      ) DistSamplerSeedHook                
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2023-03-15 19:34:36,889 - mmpose - INFO - workflow: [('train', 1)], max: 50 epochs
2023-03-15 19:34:36,889 - mmpose - INFO - Checkpoints will be saved to /mnt/data1/pywork/mmpose/work_dirs/hrnet_w48_worm_640x640 by HardDiskBackend.
=> num_images: 250
2023-03-15 19:35:09,255 - mmpose - INFO - Epoch [1][50/100]     lr: 9.890e-05, eta: 0:53:23, time: 0.647, data_time: 0.055, memory: 10993, loss_hms: 0.0016, loss_ofs: 0.0004, loss: 0.0020
2023-03-15 19:35:37,384 - mmpose - INFO - Epoch [1][100/100]    lr: 1.988e-04, eta: 0:49:23, time: 0.562, data_time: 0.000, memory: 10993, loss_hms: 0.0009, loss_ofs: 0.0004, loss: 0.0013
[                                                  ] 0/250, elapsed: 0s, ETA:/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811806235/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/functional.py:4003: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811806235/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/functional.py:4003: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 190, in main
    train_model(
  File "/mnt/data1/pywork/mmpose/mmpose/apis/train.py", line 213, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 503, in _do_evaluate
    results = self.test_fn(
  File "/mnt/data1/pywork/mmpose/mmpose/apis/test.py", line 70, in multi_gpu_test
    result = model(return_loss=False, **data)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/data1/pywork/mmpose/mmpose/models/detectors/one_stage.py", line 136, in forward
    return self.forward_test(
  File "/mnt/data1/pywork/mmpose/mmpose/models/detectors/one_stage.py", line 350, in forward_test
    keep_pose_inds = nearby_joints_nms(
  File "/mnt/data1/pywork/mmpose/mmpose/core/post_processing/nms.py", line 246, in nearby_joints_nms
    assert num_nearby_joints_thr < num_joints, '`num_nearby_joints_thr` must '\
AssertionError: `num_nearby_joints_thr` must be less than the number of joints.
Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 190, in main
    train_model(
  File "/mnt/data1/pywork/mmpose/mmpose/apis/train.py", line 213, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 503, in _do_evaluate
    results = self.test_fn(
  File "/mnt/data1/pywork/mmpose/mmpose/apis/test.py", line 70, in multi_gpu_test
    result = model(return_loss=False, **data)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/data1/pywork/mmpose/mmpose/models/detectors/one_stage.py", line 136, in forward
    return self.forward_test(
  File "/mnt/data1/pywork/mmpose/mmpose/models/detectors/one_stage.py", line 350, in forward_test
    keep_pose_inds = nearby_joints_nms(
  File "/mnt/data1/pywork/mmpose/mmpose/core/post_processing/nms.py", line 246, in nearby_joints_nms
    assert num_nearby_joints_thr < num_joints, '`num_nearby_joints_thr` must '\
AssertionError: `num_nearby_joints_thr` must be less than the number of joints.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4125) of binary: /home/kunyu/anaconda3/envs/openmmlab_0.x/bin/python
Traceback (most recent call last):
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-15_19:35:42
  host      : server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4126)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-15_19:35:42
  host      : server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4125)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. According to your log, an assertion error has occurred, which states:
```
AssertionError: num_nearby_joints_thr must be less than the number of joints.
```
It seems that you have reduced the number of keypoints to 5, but have not updated [this argument](https://github.com/open-mmlab/mmpose/blob/cbac8809f9aaf9a06d12739b1000eb9fc7b9a69d/configs/body/2d_kpt_sview_rgb_img/dekr/coco/hrnet_w32_coco_512x512.py#L105) accordingly. As a result, the assertion error occurred. I would suggest modifying the value of this argument to 2 or 3 and trying again.

**Comment by lkvanny** [comment]
Thank you. That problem has been solved。

**A New Problem: norm_ Indexes=(5,6), what does this parameter mean?**
test_cfg=dict(
        num_joints=channel_cfg['dataset_joints'],
        max_num_people=30,
        project2image=False,
        align_corners=False,
        max_pool_kernel=5,
        use_nms=True,
        nms_dist_thr=0.05,
        nms_joints_thr=8,
        keypoint_threshold=0.01,
        rescore_cfg=dict(
            in_channels=74,
            norm_indexes=(5, 6),
            pretrained='https://download.openmmlab.com/mmpose/'
            'pretrain_models/kpt_rescore_coco-33d58c5c.pth'),
        flip_test=True))

**Comment by Ben-Louis** [comment]
The `rescore_cfg` configuration establishes a rescore net that serves to evaluate OKS during post-processing. However, it should be noted that this rescore net is exclusively applicable to poses defined in COCO and cannot be used for custom datasets. Hence, it would be advisable to remove the `rescore_cfg` item when training DEKR on your own dataset.

**Comment by lkvanny** [comment]
Thank you for your timely response, the problem has been resolved.
