### ISSUE TITLE
mmpose v1.0.0rc1 cannot train!

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmpose#2079]
Thanks for your error report and we appreciate it a lot.
If you feel we have helped you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

mmpose v1.0.0rc1 cannot train! 
````
03/17 10:53:32 - mmengine - WARNING - Failed to import mmpose.models, please check the location of the registry model is correct.
python-BaseException
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/registry.py", line 325, in switch_scope_and_registry
    yield registry
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'TopdownPoseEstimator is not in the model registry. Please check whether the value of `TopdownPoseEstimator` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
Backend TkAgg is interactive backend. Turning interactive mode on.
````

**Reproduction**

- What command or script did you run?
I run the train.py.

- What config did you run?
````
_base_ = [
    '/my_path/mmpose/configs/_base_/default_runtime.py',
    '/my_path/mmpose/configs/_base_/datasets/custom.py'
]

# runtime
train_cfg = dict(max_epochs=210, val_interval=10)

# optimizer
optim_wrapper = dict(optimizer=dict(
    type='Adam',
    lr=5e-4,
))

# learning policy
param_scheduler = [
    dict(
        type='LinearLR', begin=0, end=500, start_factor=0.001,
        by_epoch=False),  # warm-up
    dict(
        type='MultiStepLR',
        begin=0,
        end=210,
        milestones=[170, 200],
        gamma=0.1,
        by_epoch=True)
]

# automatically scaling LR based on the actual training batch size
auto_scale_lr = dict(base_batch_size=512)

# hooks
default_hooks = dict(checkpoint=dict(save_best='coco/AP', rule='greater'))

# codec settings
codec = dict(
    type='MSRAHeatmap', input_size=(288, 384), heatmap_size=(72, 96), sigma=3)

# model settings
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='ResNetV1d',
        depth=50,
        init_cfg=dict(type='Pretrained', checkpoint='mmcls://resnet50_v1d'),
    ),
    head=dict(
        type='HeatmapHead',
        in_channels=2048,
        out_channels=17,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        decoder=codec),
    test_cfg=dict(
        flip_test=True,
        flip_mode='heatmap',
        shift_heatmap=True,
    ))

# base dataset settings
dataset_type = 'CocoDataset'
data_mode = 'topdown'
data_root = '/my_path/grading_dataset/coco'

# pipelines
train_pipeline = [
    dict(type='LoadImage', file_client_args={{_base_.file_client_args}}),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='GenerateTarget', encoder=codec),
    dict(type='PackPoseInputs')
]
val_pipeline = [
    dict(type='LoadImage', file_client_args={{_base_.file_client_args}}),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='PackPoseInputs')
]

# data loaders
train_dataloader = dict(
    batch_size=8,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/keypoints_train.json',
        data_prefix=dict(img='train/'),
        pipeline=train_pipeline,
    ))
val_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/keypoints_val.json',
        bbox_file=None,
        data_prefix=dict(img='val/'),
        test_mode=True,
        pipeline=val_pipeline,
    ))
test_dataloader = val_dataloader

# evaluators
val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/keypoints_val.json')
test_evaluator = val_evaluator

````

- Did you make any modifications on the code or config? Did you understand what you have modified?
- What dataset did you use?
- "I use my own dataset, and according to the steps in the documentation, I created the corresponding custom.py file and registered it accordingly. I think the 
````
03/17 10:53:32 - mmengine - WARNING - Failed to import mmpose.models, please check the location of the registry model is correct.
python-BaseException
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/registry.py", line 325, in switch_scope_and_registry
    yield registry
  File "/home/anaconda3/envs/mmpose_1/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'TopdownPoseEstimator is not in the model registry. Please check whether the value of `TopdownPoseEstimator` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
Backend TkAgg is interactive backend. Turning interactive mode on.
````
 error appears to have nothing to do with the dataset, because no matter which configuration file I run, the same error will be reported.". I checked the TopdownPoseEstimator in mmpose, which is located in mmpose/models/pose_ estimators/__ init__. "There is already a registration in mmpose/models/pose_estimators/__init__.py
![image](https://user-images.githubusercontent.com/90760124/225802138-56afe72f-9f75-41d8-b6ec-ef55156f5d2f.png)
which seems to be a problem that is not registered in MMEngine.". Is it caused by the incompatibility between the latest mmpose v1. x and MMEngine?

**Environment**
![image](https://user-images.githubusercontent.com/90760124/225802668-334471e8-3a99-4364-af76-122343cb74d1.png)

**Comment by Ben-Louis** [comment]
Were you able to successfully import TopdownPoseEstimator into your Python interactive shell using the following code snippet?
```python
from mmpose.models import TopdownPoseEstimator
```

**Comment by Ben-Louis** [comment]
BTW, the method to specify dataset meta information is changed in MMPose 1.x. It should be specified in `dataset` like
```python
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        type=dataset_type,
        data_root='root/of/your/train/data',
        ann_file='path/to/your/train/json',
        data_prefix=dict(img='path/to/your/train/img'),
        # specify the new dataset meta information config file
        metainfo=dict(from_file='configs/_base_/datasets/custom.py'),
        ...),
    )

val_dataloader = dict(
    batch_size=2,
    dataset=dict(
        type=dataset_type,
        data_root='root/of/your/val/data',
        ann_file='path/to/your/val/json',
        data_prefix=dict(img='path/to/your/val/img'),
        # specify the new dataset meta information config file
        metainfo=dict(from_file='configs/_base_/datasets/custom.py'),
        ...),
    )
```


For more details, please refer to [this documentation](https://mmpose.readthedocs.io/en/1.x/guide_to_framework.html#dataset-meta-information)

**Comment by hh123445** [comment]
> BTW, the method to specify dataset meta information is changed in MMPose 1.x. It should be specified in `dataset` like
> 
> ```python
> train_dataloader = dict(
>     batch_size=2,
>     dataset=dict(
>         type=dataset_type,
>         data_root='root/of/your/train/data',
>         ann_file='path/to/your/train/json',
>         data_prefix=dict(img='path/to/your/train/img'),
>         # specify the new dataset meta information config file
>         metainfo=dict(from_file='configs/_base_/datasets/custom.py'),
>         ...),
>     )
> 
> val_dataloader = dict(
>     batch_size=2,
>     dataset=dict(
>         type=dataset_type,
>         data_root='root/of/your/val/data',
>         ann_file='path/to/your/val/json',
>         data_prefix=dict(img='path/to/your/val/img'),
>         # specify the new dataset meta information config file
>         metainfo=dict(from_file='configs/_base_/datasets/custom.py'),
>         ...),
>     )
> ```
> 
> For more details, please refer to [this documentation](https://mmpose.readthedocs.io/en/1.x/guide_to_framework.html#dataset-meta-information)

This is useful!  Thank you very much!
