### ISSUE TITLE
topdown_heatmap train error

### ISSUE THREAD

**Issue by lkvanny** [open-mmlab/mmpose#2099]
try my dataset with 5 keypoints on topdown_heatmap/hrnet_w48_worm-ground_256x192.py

loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
=> num_images: 1000
=> load 3839 samples
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
=> Total boxes: 3
Traceback (most recent call last):
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/data1/pywork/mmpose/mmpose/datasets/datasets/top_down/topdown_worm_dataset.py", line 92, in __init__
    self.db = self._get_db()
  File "/mnt/data1/pywork/mmpose/mmpose/datasets/datasets/top_down/topdown_worm_dataset.py", line 104, in _get_db
    gt_db = self._load_coco_person_detection_results()
  File "/mnt/data1/pywork/mmpose/mmpose/datasets/datasets/top_down/topdown_worm_dataset.py", line 197, in _load_coco_person_detection_results
    if det_res['category_id'] != 1:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 190, in main
    train_model(
  File "/mnt/data1/pywork/mmpose/mmpose/apis/train.py", line 194, in train_model
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/mnt/data1/pywork/mmpose/mmpose/datasets/builder.py", line 87, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/kunyu/anaconda3/envs/openmmlab_0.x/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: TopDownWormDataset: string indices must be integers

**Comment by Tau-J** [comment]
I'll close this issue due to no response. Please feel free to reopen it if need.
