### ISSUE TITLE
Issue with multi GPU single device training 

### ISSUE THREAD

**Issue by valavakilian** [open-mmlab/mmpose#2124]
**Question**

Hello. Thank you for the great Repo. I am trying to train a custom model using multiple gpus (2 or 4) on a single device on a cluster. I can train with single GPU with a modified script but I was trying to follow the mmpose instructions to train on multiGPU (on single device) for a faster runtime. 

The config file is set up to train a custom model on coco pose data.  As far as I remember, the installation is done with a conda environment setup the same way as suggested by the mmpose website (mmcv-full installed with MIM) for gpu training. I had the following questions:

1. Am I using the correct setup to train on single machine with multiple GPUs ? I am a bit confused about the configuration required for that compared to distributed training on different machines.
2. I suspect parhaprs that "train.py: error: unrecognized arguments: --local-rank=1"  could be the root of this problem? As far as I understand from the mmcv packages "os.environ['LOCAL_RANK'] = str(args.local_rank)" line in the tools/train.py should resolve the issue ?
3. I am not that familiar with multi "torch.distributed.launch" and distrbuted training of mmpose modules. If I am to get a better traceback for the errors (if 2 is not the cause), how can I modify the code to provide better feedback about the error.

I appreciate all the help.

**Error Information**

I use the following pbs command to run the training: 
```
#!/bin/bash 
 
#PBS -l walltime=48:00:00,select=1:ncpus=2:ngpus=2:mem=32gb
#PBS -N 2gpu_multi_poolPose
#PBS -A <User Info>
#PBS -m abe
#PBS -M <User Info>
#PBS -o 2gpu_multi_output_poolPose.txt
#PBS -e 2gpu_multi_error_poolPose.txt
 
################################################################################

source ~/.bashrc

module load gcc/9.4.0 
module load cuda
conda activate openmmlab
 

cd <project path>

bash ./tools/dist_train.sh poolpose_config_2gpu_multi.py 2 --seed 0
```

I get the following error: 

```
/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/arc/project/s<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Matplotlib created a temporary config/cache directory at /tmp/pbs.4806063.pbsha.ib.sockeye/matplotlib-yor7e00_ because the default path (/home/<user_dir>.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/pbs.4806063.pbsha.ib.sockeye/matplotlib-vismndpo because the default path (/home/<user_dir>/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate] [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff_seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK] [--autoscale-lr]
                config
train.py: error: unrecognized arguments: --local-rank=0
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate] [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff_seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK] [--autoscale-lr]
                config
train.py: error: unrecognized arguments: --local-rank=1
/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 50509) of binary: /arc/project/<user_dir>/conda_envs/openmmlab/bin/python
Traceback (most recent call last):
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/arc/project/<user_dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-26_14:43:27
  host      : se297.ib.sockeye
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 50510)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-26_14:43:27
  host      : se297.ib.sockeye
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 50509)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

The following config file is used: 

- What config did you run?

```
_base_ = [
    'configs/_base_/default_runtime.py',
    'configs/_base_/datasets/coco.py'
]
evaluation = dict(interval=10, metric='mAP', save_best='AP')

log_level = '/scratch/<user_dir>/CPSC_533R/2gpu_multi/INFO_8gpu_distr'

work_dir = '/scratch/<user_dir>/CPSC_533R/2gpu_multi/work_dirs/poolpose_dir1_distr'

optimizer = dict(type='AdamW', lr=5e-4, betas=(0.9, 0.999), weight_decay=0.1)

optimizer_config = dict(grad_clip=dict(max_norm=1., norm_type=2))

# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[170, 200])
total_epochs = 210
target_type = 'GaussianHeatmap'
channel_cfg = dict(
    num_output_channels=17,
    dataset_joints=17,
    dataset_channel=[
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    ],
    inference_channel=[
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
    ])

# model settings
model = dict(
    type='TopDown',
    pretrained=None,
    backbone=dict(
        type='PoolPoses'
    ),
    keypoint_head=dict(
        type='TopdownHeatmapSimpleHead',
        in_channels=384,
        num_deconv_layers=2,
        num_deconv_filters=(256, 256),
        num_deconv_kernels=(4, 4),
        extra=dict(final_conv_kernel=1, ),
        out_channels=channel_cfg['num_output_channels'],
        loss_keypoint=dict(type='JointsMSELoss', use_target_weight=True)),
    train_cfg=dict(),
    test_cfg=dict(
        flip_test=True,
        post_process='default',
        shift_heatmap=False,
        target_type=target_type,
        modulate_kernel=11,
        use_udp=True))

data_cfg = dict(
    image_size=[224, 224],
    heatmap_size=[56, 56],
    num_output_channels=channel_cfg['num_output_channels'],
    num_joints=channel_cfg['dataset_joints'],
    dataset_channel=channel_cfg['dataset_channel'],
    inference_channel=channel_cfg['inference_channel'],
    soft_nms=False,
    nms_thr=1.0,
    oks_thr=0.9,
    vis_thr=0.2,
    use_gt_bbox=False,
    det_bbox_thr=0.0,
    bbox_file='data/coco/person_detection_results/'
    'COCO_val2017_detections_AP_H_56_person.json',
)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type = 'TopDownGetBboxCenterScale'),
    dict(type='TopDownRandomFlip', flip_prob=0.5),
    dict(
        type='TopDownHalfBodyTransform',
        num_joints_half_body=8,
        prob_half_body=0.3),
    dict(
        type='TopDownGetRandomScaleRotation', rot_factor=40, scale_factor=0.5),
    dict(type='TopDownAffine', use_udp=True),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='TopDownGenerateTarget',
        sigma=2,
        encoding='UDP',
        target_type=target_type),
    dict(
        type='Collect',
        keys=['img', 'target', 'target_weight'],
        meta_keys=[
            'image_file', 'joints_3d', 'joints_3d_visible', 'center', 'scale',
            'rotation', 'bbox_score', 'flip_pairs'
        ]),
]

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownAffine', use_udp=True),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'center', 'scale', 'rotation', 'bbox_score',
            'flip_pairs'
        ]),
]

test_pipeline = val_pipeline

launcher = "none"
data_root = 'data/coco'
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=4,
    val_dataloader=dict(samples_per_gpu=32),
    test_dataloader=dict(samples_per_gpu=32),
    train=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/annotations/person_keypoints_train2017.json',
        img_prefix=f'{data_root}/train2017/',
        data_cfg=data_cfg,
        pipeline=train_pipeline,
        dataset_info={{_base_.dataset_info}}),
    val=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/annotations/person_keypoints_val2017.json',
        img_prefix=f'{data_root}/val2017/',
        data_cfg=data_cfg,
        pipeline=val_pipeline,
        dataset_info={{_base_.dataset_info}}),
    test=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/annotations/person_keypoints_val2017.json',
        img_prefix=f'{data_root}/val2017/',
        data_cfg=data_cfg,
        pipeline=test_pipeline,
        dataset_info={{_base_.dataset_info}}),
)

```

Here is the environment information: 

```sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
GPU 0,1: Tesla V100-SXM2-32GB
CUDA_HOME: /arc/software/spack-2021/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.4.0/cuda-11.3.1-56n7klho37iu7zbc7aslccxr5akscmrf
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Spack GCC) 9.4.0
PyTorch: 2.0.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.0
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: not available
MMPose: 0.29.0+unknown
```

**Comment by ly015** [comment]
Hi, PyTorch 2.0 has renamed the argument `--local_rank` to `--local-rank`, which leads to incompatibility with MMPose. You can try modifying the argument name in the training script.

**Comment by valavakilian** [comment]
Hello and thank you for the response. I changed it earlier but I wasn't sure if that was the issue. So am I using the proper training parameters and setting. 

Also I fixed the issue above and how I have the following problem: 
```
Traceback (most recent call last):
  File "./tools/train.py", line 219, in <module>
    main()
  File "/arc/project/<user dir>/conda_envs/openmmlab/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "./tools/train.py", line 167, in main
    logger = get_root_logger(log_file=log_file, log_level=cfg.log_level)
  File "/arc/project/<user dir>/CPSC_533R/mmpose-master/mmpose/utils/logger.py", line 25, in get_root_logger
    return get_logger(__name__.split('.')[0], log_file, log_level)
  File "/arc/project/<user dir>/conda_envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/logging.py", line 72, in get_logger
    handler.setLevel(log_level)
  File "/arc/project/<user dir>/conda_envs/openmmlab/lib/python3.8/logging/__init__.py", line 916, in setLevel
    self.level = _checkLevel(level)
  File "/arc/project/<user dir>/conda_envs/openmmlab/lib/python3.8/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: '/scratch/<user dir>/CPSC_533R/INFO_2gpu_multi_distr'
```

Any ideas on how to fix this ?

**Comment by HAOCHENYE** [comment]
@valavakilian  Hi, it seems the `log_level` and `work_dir` parsed from you config is incorrect:

![image](https://user-images.githubusercontent.com/57566630/227860196-2c856277-644e-46a5-ae8e-571fb9859787.png)

Could you provide the original config file if you've checked that the `work_dir` and `log_level` is reasonable?

**Comment by valavakilian** [comment]
Hello and thanks for the response. I believe they are reasonable since I have been able to save to scuh directories before.  I can get a training code (name main_train_single_GPU.py) running if I run the following script:

```
from mmcv import Config

cfg = Config.fromfile(
    '/arc/project/<user dir>/CPSC_533R/mmpose-master/poolpose_config.py'
)

cfg.work_dir = '/scratch/<user dir>/CPSC_533R/work_dirs/poolpose_dir1'
cfg.gpus = 1
cfg.gpu_ids = range(1)
cfg.seed = 0
cfg.log_config.interval = 1000

import torch

import mmcv
from mmpose.datasets import build_dataset
from mmpose.models import build_posenet
from mmpose.apis import train_model


# build dataset
datasets = [build_dataset(cfg.data.train)]

# build model
model = build_posenet(cfg.model)

# create work_dir
mmcv.mkdir_or_exist(cfg.work_dir)

# # train model
train_model(
    model, datasets, cfg, distributed=False, validate=True, meta=dict())
```

With the proper pbs script running this code (python main_train_single_GPU.py).

**Comment by HAOCHENYE** [comment]
@valavakilian  What's the `log_level` defined in your config file? According to the traceback, its value seems weird.

![image](https://user-images.githubusercontent.com/57566630/227868828-115b39e5-4819-4bbd-af70-cf0305d5d4cf.png)

**Comment by valavakilian** [comment]
```
log_level = '/scratch/st-cthrampo-1/vaalaa/CPSC_533R/INFO_1gpu'
```
Sorry  I replaced st-cthrampo-1/vaalaa  with  <user dir> before to avoid confusion. Its just the directory where I want to save the logger.  Is that not the correct way to use it ?

**Comment by HAOCHENYE** [comment]
The log level should be a string like "DEBUG", "INFO"  or an integer as [here](https://docs.python.org/3/library/logging.html#logging-levels) defined
