### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by 670768312** [open-mmlab/mmpose#2195]
When I run the demo file, there was an error ocurring. "ImportError: numpy.core.multiarray failed to import",  I dont know how to fix it. Can you give me a help?

**Comment by 670768312** [comment]
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\mmpose-1.x\demo\topdown_demo_with_mmdet.py", line 12, in <module>
    from mmpose.apis import inference_topdown
  File "H:\mmpose-1.x\mmpose\apis\__init__.py", line 2, in <module>
    from .inference import inference_bottomup, inference_topdown, init_model
  File "H:\mmpose-1.x\mmpose\apis\inference.py", line 16, in <module>
    from mmpose.datasets.datasets.utils import parse_pose_metainfo
  File "H:\mmpose-1.x\mmpose\datasets\__init__.py", line 3, in <module>
    from .dataset_wrappers import CombinedDataset
  File "H:\mmpose-1.x\mmpose\datasets\dataset_wrappers.py", line 10, in <module>
    from .datasets.utils import parse_pose_metainfo
  File "H:\mmpose-1.x\mmpose\datasets\datasets\__init__.py", line 2, in <module>
    from .animal import *  # noqa: F401, F403
  File "H:\mmpose-1.x\mmpose\datasets\datasets\animal\__init__.py", line 2, in <module>
    from .animalpose_dataset import AnimalPoseDataset
  File "H:\mmpose-1.x\mmpose\datasets\datasets\animal\animalpose_dataset.py", line 3, in <module>
    from ..base import BaseCocoStyleDataset
  File "H:\mmpose-1.x\mmpose\datasets\datasets\base\__init__.py", line 2, in <module>
    from .base_coco_style_dataset import BaseCocoStyleDataset
  File "H:\mmpose-1.x\mmpose\datasets\datasets\base\base_coco_style_dataset.py", line 12, in <module>
    from xtcocotools.coco import COCO
  File "H:\ProgramData\Anaconda3\envs\mmpose\lib\site-packages\xtcocotools\coco.py", line 58, in <module>
    from . import mask as maskUtils
  File "H:\ProgramData\Anaconda3\envs\mmpose\lib\site-packages\xtcocotools\mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools\_mask.pyx", line 23, in init xtcocotools._mask
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. For this issue, please try reinstalling `xtcocotools` from source.
```shell
pip uninstall xtcocotools
pip install git+https://github.com/jin-s13/xtcocoapi
```

**Comment by 670768312** [comment]
But I met another error " topdown_demo_with_mmdet.py: error: the following arguments are required: det_config, det_checkpoint, pose_config, pose_checkpoint ". However, I have set these arguments. 
"parser.add_argument('det_config', default = 'demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py',help='Config file for detection')
    parser.add_argument('det_checkpoint', default = 'data/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth',help='Checkpoint file for detection')
    parser.add_argument('pose_config', default = 'configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_8xb32-210e_coco-256x192.py', help='Config file for pose')
    parser.add_argument('pose_checkpoint', default = 'data/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth',help='Checkpoint file for pose')"

**Comment by 670768312** [comment]
Thanks a lot , i have solved this problem !
