### ISSUE TITLE
Unable to run inferencer_demo.py

### ISSUE THREAD

**Issue by tet28** [open-mmlab/mmpose#2263]
Hi.

I installed mmpose 1.0.0 today and tried to run pose estimation on a video and it failed with an error.
The code I executed is as follows.
python3 . /inferencer_demo.py . /test.mp4 --pose2d . /projects/yolox-pose/configs/yolox-pose_l_4xb64-300e_coco.py --pose2d-weights . /projects/yolox-pose/models/yolox-pose_l_4xb64-300e_coco-122e4cf8_20230321.pth --device cuda:0 --vis-out-dir . /vis_results --scope mmyolo

Then I got the following error and it failed.

Traceback (most recent call last):
  File "/home/work/mmpose38/mmpose1.0-env/lib/python3.8/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'datasets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/work/mmpose38/mmpose1.0-env/lib/python3.8/site-packages/mmengine/config/config.py", line 181, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/work/mmpose38/mmpose1.0-env/lib/python3.8/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import datasets

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./demo/inferencer_demo.py", line 138, in <module>
    main()
  File "./demo/inferencer_demo.py", line 132, in main
    inferencer = MMPoseInferencer(**init_args)
  File "/home/work/mmpose38/mmpose-main/mmpose/apis/inferencers/mmpose_inferencer.py", line 84, in __init__
    self.pose2d_inferencer = Pose2DInferencer(pose2d, pose2d_weights,
  File "/home/work/mmpose38/mmpose-main/mmpose/apis/inferencers/pose2d_inferencer.py", line 90, in __init__
    super().__init__(
  File "/home/work/mmpose38/mmpose1.0-env/lib/python3.8/site-packages/mmengine/infer/infer.py", line 152, in __init__
    cfg = Config.fromfile(model)
  File "/home/work/mmpose38/mmpose1.0-env/lib/python3.8/site-packages/mmengine/config/config.py", line 183, in fromfile
    raise ImportError('Failed to custom import!') from e
ImportError: Failed to custom import!

The environment was installed according to this site
https://mmpose.readthedocs.io/en/latest/installation.html

The python version is 3.8 and the installed libraries are as follows
addict==2.4.0
attrs==23.1.0
certifi==2022.12.7
charset-normalizer==3.1.0
chumpy==0.70
click==8.1.3
cmake==3.26.3
colorama==0.4.6
contourpy==1.0.7
coverage==7.2.3
cycler==0.11.0
Cython==0.29.34
exceptiongroup==1.1.1
filelock==3.12.0
flake8==6.0.0
fonttools==4.39.3
idna==3.4
importlib-metadata==6.5.0
importlib-resources==5.12.0
iniconfig==2.0.0
interrogate==1.5.0
isort==4.3.21
Jinja2==3.1.2
json-tricks==3.16.1
kiwisolver==1.4.4
lit==16.0.1
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
mccabe==0.7.0
mdurl==0.1.2
mmcv==2.0.0
mmdet==3.0.0
mmengine==0.7.2
# Editable install with no version control (mmpose==1.0.0)
-e /home/work/mmpose38/mmpose-main
model-index==0.1.11
mpmath==1.3.0
munkres==1.1.4
networkx==3.1
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
opencv-python==4.7.0.72
openmim==0.3.7
ordered-set==4.1.0
packaging==23.1
pandas==2.0.0
parameterized==0.9.0
Pillow==9.5.0
pluggy==1.0.0
py==1.11.0
pycocotools==2.0.6
pycodestyle==2.10.0
pyflakes==3.0.1
Pygments==2.15.1
pyparsing==3.0.9
pytest==7.3.1
pytest-runner==6.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
requests==2.28.2
rich==13.3.4
scipy==1.10.1
shapely==2.0.1
six==1.16.0
sympy==1.11.1
tabulate==0.9.0
termcolor==2.2.0
terminaltables==3.1.10
toml==0.10.2
tomli==2.0.1
torch==1.13.1+cu117
torchaudio==0.13.1+cu117
torchvision==0.14.1+cu117
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==1.26.15
xdoctest==1.1.1
xtcocotools==1.13
yapf==0.33.0
zipp==3.15.0

Please let me know if there is something wrong with my setup.
Thank you.

**Comment by Ben-Louis** [comment]
Thanks for using MMPose. You may need to set the `PYTHONPATH` according to the instruction in the README before using yolox-pose with inferencer

**Comment by tet28** [comment]
After setting the PYTHONPATH, it works! Thanks!
