### ISSUE TITLE
ModuleNotFoundError: No module named 'mmpose.visualization'

### ISSUE THREAD

**Issue by caozhe19961226** [open-mmlab/mmpose#2272]
root@autodl-container-704e11bd52-d3e14d82:~/mmpose# python tools/train.py configs/body_2d_keypoint/dekr/coco/dekr_hrnet-w32_8xb10-140e_coco-512x512.py Traceback (most recent call last):
  File "tools/train.py", line 160, in <module>
    main()
  File "tools/train.py", line 153, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 374, in __init__
    self.log_processor = self.build_log_processor(log_processor)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1594, in build_log_processor
    log_processor = LOG_PROCESSORS.build(log_processor_cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 442, in get
    self.import_from_location()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 376, in import_from_location
    import_module(loc)
  File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmpose.visualization'

How should this error be handled？Thanks

**Comment by Ben-Louis** [comment]
Thanks for using MMPose. You may need to set the `PYTHONPATH` as

```shell
PYTHONPATH=. python tools/train.py $CONFIG
```

**Comment by caozhe19961226** [comment]
Thank you for your prompt answer, which solves my problem






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmpose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmpose] ModuleNotFoundError: No module named 'mmpose.visualization' (Issue #2272)





 
Thanks for using MMPose. You may need to set the PYTHONPATH as
 PYTHONPATH=. python tools/train.py $CONFIG
