### ISSUE TITLE
mmpose/project/yolox-pose :I mportError: Failed to custom import!

### ISSUE THREAD

**Issue by shuyuanwen** [open-mmlab/mmpose#2279]
python tools/train.py configs/yolox-pose_s_8xb32-300e_coco.py  

(mmpose) --- projects/yolox-pose ‹main* M?› » python tools/train.py configs/yolox-pose_s_8xb32-300e_coco.py  
Traceback (most recent call last):
  File "/home/sywen/anaconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/sywen/anaconda3/envs/mmpose/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sywen/anaconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/config/config.py", line 181, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/sywen/anaconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import models

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/train.py", line 160, in <module>
    main()
  File "tools/train.py", line 142, in main
    cfg = Config.fromfile(args.config)
  File "/home/sywen/anaconda3/envs/mmpose/lib/python3.8/site-packages/mmengine/config/config.py", line 183, in fromfile
    raise ImportError('Failed to custom import!') from e
ImportError: Failed to custom import!

**Comment by Ben-Louis** [comment]
Thanks for using MMPose. Please set `PYTHONPATH` before training yolox-pose following the instruction in readme

**Comment by hsp2454** [comment]
Hello, have you solved this problem?

**Comment by WinnerMeat** [comment]
I'm having the following problem when training yolo-pose on the dist_train.sh script, mostly
```python
KeyError: 'BaseBackbone is already registered in model at models.backbones.base_backbone'.
```
The possible reason for this is that I installed mmyolo using the source code, which causes the package to be loaded repeatedly now, do you have any solution for   @Ben-Louis 


```python
$ bash dist_train.sh
NOTE: Redirects are currently not supported in Windows or MacOs.
D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\torch\distributed\launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:


Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in you
r application as needed.


[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.inte
rnal]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.inte
rnal]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
Traceback (most recent call last):
  File "./train.py", line 164, in <module>
    main()
  File "./train.py", line 142, in main
    cfg = Config.fromfile(args.config)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\config\config.py", line 182, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\utils\misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\userdocument\Y\mmpose\mmyolo\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\__init__.py", line 4, in <module>
    from .csp_resnet import PPYOLOECSPResNet
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\csp_resnet.py", line 8, in <module>
    from mmyolo.models.backbones import BaseBackbone
  File "d:\userdocument\Y\mmpose\mmyolo\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\__init__.py", line 2, in <module>
    from .base_backbone import BaseBackbone
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\base_backbone.py", line 16, in <module>
    class BaseBackbone(BaseModule, metaclass=ABCMeta):
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\registry\registry.py", line 644, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\registry\registry.py", line 589, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'BaseBackbone is already registered in model at models.backbones.base_backbone'
Traceback (most recent call last):
  File "./train.py", line 164, in <module>
    main()
  File "./train.py", line 142, in main
    cfg = Config.fromfile(args.config)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\config\config.py", line 182, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\utils\misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\userdocument\Y\mmpose\mmyolo\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\__init__.py", line 4, in <module>
    from .csp_resnet import PPYOLOECSPResNet
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\csp_resnet.py", line 8, in <module>
    from mmyolo.models.backbones import BaseBackbone
  File "d:\userdocument\Y\mmpose\mmyolo\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\__init__.py", line 2, in <module>
    from .base_backbone import BaseBackbone
  File "d:\userdocument\Y\mmpose\mmyolo\models\backbones\base_backbone.py", line 16, in <module>
    class BaseBackbone(BaseModule, metaclass=ABCMeta):
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\registry\registry.py", line 644, in _register
    self._register_module(module=module, module_name=name, force=force)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\mmengine\registry\registry.py", line 589, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'BaseBackbone is already registered in model at models.backbones.base_backbone'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 29252) of binary: D:\UserDocument\Y\Anaconda\envs\mmpose\python.exe
Traceback (most recent call last):
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\torch\distributed\launch.py", line 195, in <module>
    main()
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\torch\distributed\launch.py", line 191, in main
    launch(args)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\torch\distributed\launch.py", line 176, in launch
    run(args)
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\torch\distributed\run.py", line 753, in run
    elastic_launch(
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\torch\distributed\launcher\api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\UserDocument\Y\Anaconda\envs\mmpose\lib\site-packages\torch\distributed\launcher\api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-24_10:09:20
  host      : WIN-FM0O6KRPHJ9
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 29288)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-24_10:09:20
  host      : WIN-FM0O6KRPHJ9
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 29252)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
