### ISSUE TITLE
implement image_demo.py in 0.x version of mmpose 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2343]
### 📚 The doc issue

hello , 
I would like to ask about how to implement the function of 
`python demo/image_demo.py` 
on my old version of mmpose ( 0.29.0) , as i already trained different models on the old  version 

I want to have both a test image as well as the heat map figure of couples of image. 
similar to what presents in the [installation instruction.](https://mmpose.readthedocs.io/en/latest/installation.html)

it will be very time consuming to train my models again on the new version of mmpose . 
can you help me please. 

looking forward to hear from your side.

**Comment by Ben-Louis** [comment]
Models trained with MMPose 0.29 can typically be utilized with MMPose 1.0. The only requirement is to convert the config files to align with the format of the new version.

**Comment by alaa-shubbak** [comment]
i would like to reopen the issue please 
as i got error while trying to run the demo code. 

`python demo/image_demo.py`

here is the error 

```
/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/apis/inference.py:118: UserWarning: Can not load dataset_meta from the checkpoint or the model config. Use COCO metainfo by default.
  warnings.warn('Can not load dataset_meta from the checkpoint or the '
/home/shubbak/env_pose/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:228: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  interpolation: int = Image.BILINEAR,
/home/shubbak/env_pose/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:296: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  interpolation: int = Image.NEAREST,
/home/shubbak/env_pose/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:329: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  interpolation: int = Image.BICUBIC,
05/11 16:41:27 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/apis/inference.py:158: ResourceWarning: unclosed file <_io.BufferedReader name='/home/shubbak/Downloads/exc5.jpg'>
  w, h = Image.open(img).size
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/scratch/shubbak/mmpose/demo/image_demo.py", line 105, in <module>
    main()
  File "/scratch/shubbak/mmpose/demo/image_demo.py", line 85, in main
    batch_results = inference_topdown(model, args.img)
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/apis/inference.py", line 191, in inference_topdown
    results = model.test_step(batch)
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/models/pose_estimators/base.py", line 140, in forward
    return self.predict(inputs, data_samples)
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/models/pose_estimators/topdown.py", line 109, in predict
    preds = self.head.predict(feats, data_samples, test_cfg=self.test_cfg)
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/models/heads/heatmap_heads/heatmap_head.py", line 261, in predict
    _batch_heatmaps_flip = flip_heatmaps(
  File "/home/shubbak/env_pose/lib/python3.9/site-packages/mmpose/models/utils/tta.py", line 39, in flip_heatmaps
    assert len(flip_indices) == heatmaps.shape[1]
AssertionError
(env_pose) 
```

i try to modify ,y config to fit with the new version of mmpose . but i still get errors.
