### ISSUE TITLE
[Feature]  'plugins'

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#2382]
### What is the feature?

actually , i am trying to run a mmpose on a model based on ResNet-50 , to detect pose of my custom dataset . 

in general , the normal model is working , but i want to plugin some feature ,such as attention mechanism . 
unfortunately i got this error : 
`TypeError: TopDown: ResNet: __init__() got an unexpected keyword argument 'plugins'`

here is the full log of the error : 
```

Traceback (most recent call last):
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/shubbak/mmpose_old/mmpose/models/detectors/top_down.py", line 48, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/shubbak/mmpose_old/mmpose/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ResNet: __init__() got an unexpected keyword argument 'plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 203, in <module>
    main()
  File "tools/train.py", line 177, in main
    model = build_posenet(cfg.model)
  File "/home/shubbak/mmpose_old/mmpose/models/builder.py", line 39, in build_posenet
    return POSENETS.build(cfg)
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/shubbak/env2_pose/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: TopDown: ResNet: __init__() got an unexpected keyword argument 'plugins'

```

can you please guide me to be able to integrate this attenetion in my backbone of resnet-50 in topdown pose estimation appraoch. 

looking forward to your help.

**Comment by Tau-J** [comment]
Thanks for using MMPose. You need to modify `mmpose/models/backbones/resnet.py` to add `plugins`

**Comment by alaa-shubbak** [comment]
> You need to modify mmpose/models/backbones/resnet.py to add plugins

I did so , i try to modify the  resnet.py file in [mmpose](https://github.com/open-mmlab/mmpose/tree/main/mmpose)/[models](https://github.com/open-mmlab/mmpose/tree/main/mmpose/models)

i got this error : 
```

Traceback (most recent call last):
  File "tools/train.py", line 19, in <module>
    from mmpose.apis import init_random_seed, train_model
  File "/home/shubbak/mmpose_old/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottom_up_pose_model,
  File "/home/shubbak/mmpose_old/mmpose/apis/inference.py", line 17, in <module>
    from mmpose.datasets.dataset_info import DatasetInfo
  File "/home/shubbak/mmpose_old/mmpose/datasets/__init__.py", line 7, in <module>
    from .datasets import (  # isort:skip
  File "/home/shubbak/mmpose_old/mmpose/datasets/datasets/__init__.py", line 2, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/home/shubbak/mmpose_old/mmpose/deprecated.py", line 6, in <module>
    from .models.builder import HEADS, POSENETS
  File "/home/shubbak/mmpose_old/mmpose/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa
  File "/home/shubbak/mmpose_old/mmpose/models/backbones/__init__.py", line 4, in <module>
    from .hourglass import HourglassNet
  File "/home/shubbak/mmpose_old/mmpose/models/backbones/hourglass.py", line 11, in <module>
    from .resnet import BasicBlock, ResLayer
  File "/home/shubbak/mmpose_old/mmpose/models/backbones/resnet.py", line 259
    if self.with_plugins:
    ^
IndentationError: unexpected indent

```

**Comment by alaa-shubbak** [comment]
> modify

i want to open the issue again please. 
how can i modify the `mmpose/models/backbones/resnet.py` to contain the plugin as you mentioned . 
I try to use the exist one within [mmdetetction](https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/backbones/resnet.py)


i did try to modify it. 
i got this error `No module named 'mmpretrain.models.layers'`



here is the full error log :
```

05/28 16:38:56 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.8.11 (default, Jul 13 2021, 14:00:03) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
    CUDA available: True
    numpy_random_seed: 1605427802
    GPU 0: Tesla V100-PCIE-32GB
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 12.1, V12.1.105
    GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
    PyTorch: 2.0.0+cu117
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.15.1+cu117
    OpenCV: 4.7.0
    MMEngine: 0.7.3

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    deterministic: False
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

05/28 16:38:57 - mmengine - INFO - Config:
dataset_type = 'CustomDataset'
data_root = '/work/shubbak/datasets/ACID/'
data_preprocessor = dict(
    type='SelfSupDataPreprocessor',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True)
view_pipeline = [
    dict(
        type='RandomResizedCrop',
        scale=224,
        crop_ratio_range=(0.2, 1.0),
        backend='pillow'),
    dict(
        type='RandomApply',
        transforms=[
            dict(
                type='ColorJitter',
                brightness=0.4,
                contrast=0.4,
                saturation=0.4,
                hue=0.1)
        ],
        prob=0.8),
    dict(
        type='RandomGrayscale',
        prob=0.2,
        keep_channels=True,
        channel_weights=(0.114, 0.587, 0.2989)),
    dict(
        type='GaussianBlur',
        magnitude_range=(0.1, 2.0),
        magnitude_std='inf',
        prob=0.5),
    dict(type='RandomFlip', prob=0.5)
]
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiView',
        num_views=2,
        transforms=[[{
            'type': 'RandomResizedCrop',
            'scale': 224,
            'crop_ratio_range': (0.2, 1.0),
            'backend': 'pillow'
        }, {
            'type':
            'RandomApply',
            'transforms': [{
                'type': 'ColorJitter',
                'brightness': 0.4,
                'contrast': 0.4,
                'saturation': 0.4,
                'hue': 0.1
            }],
            'prob':
            0.8
        }, {
            'type': 'RandomGrayscale',
            'prob': 0.2,
            'keep_channels': True,
            'channel_weights': (0.114, 0.587, 0.2989)
        }, {
            'type': 'GaussianBlur',
            'magnitude_range': (0.1, 2.0),
            'magnitude_std': 'inf',
            'prob': 0.5
        }, {
            'type': 'RandomFlip',
            'prob': 0.5
        }]]),
    dict(type='PackInputs')
]
train_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=32,
    num_workers=8,
    drop_last=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='CustomDataset',
        data_root='/work/shubbak/datasets/ACID/',
        data_prefix=dict(img_path='ACID_Images/'),
        with_label=False,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiView',
                num_views=2,
                transforms=[[{
                    'type': 'RandomResizedCrop',
                    'scale': 224,
                    'crop_ratio_range': (0.2, 1.0),
                    'backend': 'pillow'
                }, {
                    'type':
                    'RandomApply',
                    'transforms': [{
                        'type': 'ColorJitter',
                        'brightness': 0.4,
                        'contrast': 0.4,
                        'saturation': 0.4,
                        'hue': 0.1
                    }],
                    'prob':
                    0.8
                }, {
                    'type': 'RandomGrayscale',
                    'prob': 0.2,
                    'keep_channels': True,
                    'channel_weights': (0.114, 0.587, 0.2989)
                }, {
                    'type': 'GaussianBlur',
                    'magnitude_range': (0.1, 2.0),
                    'magnitude_std': 'inf',
                    'prob': 0.5
                }, {
                    'type': 'RandomFlip',
                    'prob': 0.5
                }]]),
            dict(type='PackInputs')
        ]))
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='LARS', lr=0.3, weight_decay=1e-06, momentum=0.9),
    paramwise_cfg=dict(
        custom_keys=dict({
            'bn': dict(decay_mult=0, lars_exclude=True),
            'bias': dict(decay_mult=0, lars_exclude=True),
            'downsample.1': dict(decay_mult=0, lars_exclude=True)
        })))
param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.0001,
        by_epoch=True,
        begin=0,
        end=10,
        convert_to_iter_based=True),
    dict(
        type='CosineAnnealingLR', T_max=190, by_epoch=True, begin=10, end=200)
]
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=800, val_interval=10)
default_scope = 'mmpretrain'
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=10),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=10),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='VisualizationHook', enable=False))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='UniversalVisualizer', vis_backends=[dict(type='LocalVisBackend')])
log_level = 'INFO'
load_from = None
resume = False
randomness = dict(seed=None, deterministic=False)
model = dict(
    type='SimCLR',
    backbone=dict(
        type='mmdet.models.backbones.resnet',
        depth=50,
        norm_cfg=dict(type='SyncBN'),
        zero_init_residual=True,
        plugins=dict(
            cfg=dict(
                type='GeneralizedAttention',
                spatial_range=-1,
                num_heads=8,
                attention_type='0010',
                kv_stride=2),
            stages=(False, False, True, True),
            position='after_conv2')),
    neck=dict(
        type='NonLinearNeck',
        in_channels=2048,
        hid_channels=2048,
        out_channels=128,
        num_layers=2,
        with_avg_pool=True),
    head=dict(
        type='ContrastiveHead',
        loss=dict(type='CrossEntropyLoss'),
        temperature=0.1))
auto_scale_lr = dict(base_batch_size=256)
launcher = 'none'
work_dir = 'train_dir/ACID_all/simclr_resnet50_att/'

Traceback (most recent call last):
  File "tools/train.py", line 163, in <module>
    main()
  File "tools/train.py", line 156, in main
    runner = Runner.from_cfg(cfg)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/registry/registry.py", line 549, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/registry/registry.py", line 443, in get
    self.import_from_location()
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/registry/registry.py", line 377, in import_from_location
    import_module(loc)
  File "/software/python/3.8.11/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/backbones/__init__.py", line 36, in <module>
    from .resnetnew import ResNet, ResNetV1d
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/backbones/resnetnew.py", line 15, in <module>
    from ..layers import ResLayer
ModuleNotFoundError: No module named 'mmpretrain.models.layers'



```

any help please
