### ISSUE TITLE
KeyError: 'DetDataPreprocessor is not in the model registry. 

### ISSUE THREAD

**Issue by nakuda1** [open-mmlab/mmpose#2428]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

The latest version

### Reproduces the problem - code sample

Sorry to bother you.
I can run the test demo of mmpose, but I can not run the demo in animal pose estimation 
---------------------------------------------------------------------------------------------------------------------------
!python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \   https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/animal_2d_keypoint/topdown_heatmap/animalpose/td-hm_hrnet-w32_8xb64-210e_animalpose-256x256.py \
    https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth \
    --input tests/data/animalpose/cow1.jpg \
    --output-root vis_results --save-predictions --draw-heatmap
------------------------------------------------------------------------------------------------------
But I can not find top_down_img_demo.py, top_down_video_demo_full_frame_without_det.py, top_down_video_demo_full_frame_without_det.py, top_down_video_demo_with_mmde.py in the latest version of mmpose.

### Reproduces the problem - command or script

So, if I wanna run this animal pose demo, Many thanks

### Reproduces the problem - error message

!python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/animal_2d_keypoint/topdown_heatmap/animalpose/td-hm_hrnet-w32_8xb64-210e_animalpose-256x256.py \
    https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth \
    --input tests/data/animalpose/cow1.jpg \
    --output-root vis_results --save-predictions --draw-heatmap
06/06 02:45:48 - mmengine - WARNING - The "model" registry in mmdet did not set import location. Fallback to call `mmdet.utils.register_all_modules` instead.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/faster_rcnn.py", line 20, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 32, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 31, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 78, in __init__
    self.data_preprocessor = MODELS.build(data_preprocessor)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DetDataPreprocessor is not in the model registry. Please check whether the value of `DetDataPreprocessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/topdown_demo_with_mmdet.py", line 292, in <module>
    main()
  File "demo/topdown_demo_with_mmdet.py", line 178, in main
    detector = init_detector(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/apis/inference.py", line 55, in init_detector
    model = build_detector(config.model)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/builder.py", line 68, in build_detector
    return DETECTORS.build(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `FasterRCNN` in mmdet/models/detectors/faster_rcnn.py: 'DetDataPreprocessor is not in the model registry. Please check whether the value of `DetDataPreprocessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. The demo script you are using relies on mmdet. Please install [mmdet](https://github.com/open-mmlab/mmdetection) with version >= 3.0 to run this demo
