### ISSUE TITLE
[Bug] run train.py TypeError

### ISSUE THREAD

**Issue by IGLatte** [open-mmlab/mmpose#2446]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

1.<function collect_env at 0x0000012E2443E8B0>
2.
mmcv                2.0.0
mmdet               3.0.0
mmengine            0.7.4
mmpose              1.0.0

### Reproduces the problem - code sample

![微信截图_20230610113449](https://github.com/open-mmlab/mmpose/assets/53251825/54b26996-9cc4-4180-a37e-e42546500238)

### Reproduces the problem - command or script

Command:python tools/train.py configs/animal_2d_keypoint/topdown_heatmap/animalpose/mousepose-256x256.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "D:\necessary\Anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
  File "D:\necessary\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1486, in build_train_loop
    loop = EpochBasedTrainLoop(
  File "D:\necessary\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "D:\necessary\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "D:\necessary\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "D:\necessary\Anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\necessary\Anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 144, in build_from_cfg
    raise type(e)(
TypeError: class `MouseDataset` in mmpose/datasets/datasets/animal/mouse_dataset.py: __init__() got an unexpected keyword argument 'data_mode'

### Additional information

1.Dataset is my mouse dataset.
Data structure is below:
data 
    |---|Annotations
         |         |-----|train.json
         |                 |val.json
         |images
               |----train
               |----val

**Comment by Tau-J** [comment]
Hi @IGLatte , thanks for using MMPose. It seems that you pass a  `data_mode` when initializing `MouseDataset`, yet there is no such a `data_mode` in it. Therefore, you need to check the definition of `MouseDataset` in `mmpose/datasets/datasets/animal/mouse_dataset.py`.

**Comment by IGLatte** [comment]
According to the configuration file method described in the document, the `data_mode` appears in the position shown in the image below. However, in the `mouse_dataset.py` file, there is no definition for `data_mode`.
![QQ图片20230615111859](https://github.com/open-mmlab/mmpose/assets/53251825/2aeb689e-53b3-405f-8d7e-d5cac2895d7d)
![QQ截图20230615111933](https://github.com/open-mmlab/mmpose/assets/53251825/a8f2ce31-8c0d-451d-9c77-431e28702b02)
