### ISSUE TITLE
[Bug] bug in install of mmpose in Google Colab

### ISSUE THREAD

**Issue by SylvainArd** [open-mmlab/mmpose#2453]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Google Colab

### Reproduces the problem - code sample

I have launched it in Google Colab with mmpose 0.29

### Reproduces the problem - command or script

I have launched : 
```
!pip3 install openmim
!mim install mmcv-full
cd mmpose-master
!pip3 install -e .
!python tools/train.py configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py --work-dir "output"
```

### Reproduces the problem - error message

```
/usr/local/lib/python3.10/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/mmpose-master/tools/train.py", line 17, in <module>
    from mmpose.apis import init_random_seed, train_model
  File "/content/mmpose-master/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottom_up_pose_model,
  File "/content/mmpose-master/mmpose/apis/inference.py", line 17, in <module>
    from mmpose.datasets.dataset_info import DatasetInfo
  File "/content/mmpose-master/mmpose/datasets/__init__.py", line 7, in <module>
    from .datasets import (  # isort:skip
  File "/content/mmpose-master/mmpose/datasets/datasets/__init__.py", line 2, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/content/mmpose-master/mmpose/deprecated.py", line 5, in <module>
    from .datasets.datasets.base import Kpt2dSviewRgbImgTopDownDataset
  File "/content/mmpose-master/mmpose/datasets/datasets/base/__init__.py", line 2, in <module>
    from .kpt_2d_sview_rgb_img_bottom_up_dataset import \
  File "/content/mmpose-master/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_bottom_up_dataset.py", line 8, in <module>
    from xtcocotools.coco import COCO
  File "/usr/local/lib/python3.10/dist-packages/xtcocotools/coco.py", line 58, in <module>
    from . import mask as maskUtils
  File "/usr/local/lib/python3.10/dist-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 23, in init xtcocotools._mask
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

**Comment by SylvainArd** [comment]
I finally succeeded by doing : 
```
!pip uninstall tensorflow -y
!pip uninstall numba -y
!pip install numpy --upgrade
!pip3 install openmim
!mim install mmcv-full
cd mmpose-master
!pip3 install -e .
!python tools/train.py configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py --work-dir "output"
```
