### ISSUE TITLE
unable to train

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmpose#2570]
### 📚 The doc issue

After I installed mmpsoe1.1, I tried to train configs\animal_2d_keypoint\topdown_heatmap\animalpose\td-hm_hrnet-w32_8xb64-210e_animalpose-256x256.py, using a custom dataset. Below is my config file

```
`Config:
default_scope = 'mmpose'
default_hooks = dict(   
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook',
        interval=10,
        save_best='coco/AP',
        rule='greater'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='PoseVisualizationHook', enable=False))
custom_hooks = [
    dict(type='SyncBuffersHook'),
]
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    type='PoseLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ],
    name='visualizer')
log_processor = dict(
    type='LogProcessor', window_size=50, by_epoch=True, num_digits=6)
log_level = 'INFO'
load_from = None
resume = False
backend_args = dict(backend='local')
train_cfg = dict(by_epoch=True, max_epochs=210, val_interval=10)
val_cfg = dict()
test_cfg = dict()
optim_wrapper = dict(optimizer=dict(type='Adam', lr=0.0005))
param_scheduler = [
    dict(
        type='LinearLR', begin=0, end=500, start_factor=0.001, by_epoch=False),
    dict(
        type='MultiStepLR',
        begin=0,
        end=210,
        milestones=[
            170,
            200,
        ],
        gamma=0.1,
        by_epoch=True),
]
auto_scale_lr = dict(base_batch_size=512)
codec = dict(
    type='MSRAHeatmap',
    input_size=(
        256,
        256,
    ),
    heatmap_size=(
        64,
        64,
    ),
    sigma=2)
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(
                    4,
                    4,
                ),
                num_channels=(
                    32,
                    64,
                )),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(
                    4,
                    4,
                    4,
                ),
                num_channels=(
                    32,
                    64,
                    128,
                )),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(
                    4,
                    4,
                    4,
                    4,
                ),
                num_channels=(
                    32,
                    64,
                    128,
                    256,
                ))),
        init_cfg=dict(
            type='Pretrained',
            checkpoint=
            'https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w32-36af842e.pth'
        )),
    head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=16,
        deconv_out_channels=None,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        decoder=dict(
            type='MSRAHeatmap',
            input_size=(
                256,
                256,
            ),
            heatmap_size=(
                64,
                64,
            ),
            sigma=2)),
    test_cfg=dict(flip_test=True, flip_mode='heatmap', shift_heatmap=True))
dataset_type = 'HorseAnimalDataset'
data_mode = 'topdown'
data_root = 'data\\horse\\AugmentforKeypoints\\labels/'
train_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=(
        256,
        256,
    )),
    dict(
        type='GenerateTarget',
        encoder=dict(
            type='MSRAHeatmap',
            input_size=(
                256,
                256,
            ),
            heatmap_size=(
                64,
                64,
            ),
            sigma=2)),
    dict(type='PackPoseInputs'),
]
val_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=(
        256,
        256,
    )),
    dict(type='PackPoseInputs'),
]
train_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='HorseAnimalDataset',
        data_root='data\\horse\\AugmentforKeypoints\\labels/',
        data_mode='topdown',
        ann_file='train_coco.json',
        data_prefix=dict(img=''),
        pipeline=[
            dict(type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(type='RandomFlip', direction='horizontal'),
            dict(type='RandomHalfBody'),
            dict(type='RandomBBoxTransform'),
            dict(type='TopdownAffine', input_size=(
                256,
                256,
            )),
            dict(
                type='GenerateTarget',
                encoder=dict(
                    type='MSRAHeatmap',
                    input_size=(
                        256,
                        256,
                    ),
                    heatmap_size=(
                        64,
                        64,
                    ),
                    sigma=2)),
            dict(type='PackPoseInputs'),
        ],
        metainfo=dict(
            from_file=
            'D:\\Code\\mmpose-1.1.0\\configs\\_base_\\datasets\\horse.py')))
val_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type='HorseAnimalDataset',
        data_root='data\\horse\\AugmentforKeypoints\\labels/',
        data_mode='topdown',
        ann_file='val_coco.json',
        data_prefix=dict(img=''),
        test_mode=True,
        pipeline=[
            dict(type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(type='TopdownAffine', input_size=(
                256,
                256,
            )),
            dict(type='PackPoseInputs'),
        ],
        metainfo=dict(
            from_file=
            'D:\\Code\\mmpose-1.1.0\\configs\\_base_\\datasets\\horse.py')))
test_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type='HorseAnimalDataset',
        data_root='data\\horse\\AugmentforKeypoints\\labels/',
        data_mode='topdown',
        ann_file='val_coco.json',
        data_prefix=dict(img=''),
        test_mode=True,
        pipeline=[
            dict(type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(type='TopdownAffine', input_size=(
                256,
                256,
            )),
            dict(type='PackPoseInputs'),
        ],
        metainfo=dict(
            from_file=
            'D:\\Code\\mmpose-1.1.0\\configs\\_base_\\datasets\\horse.py')))
val_evaluator = dict(
    type='CocoMetric',
    ann_file='data\\horse\\AugmentforKeypoints\\labels/val_coco.json')
test_evaluator = dict(
    type='CocoMetric',
    ann_file='data\\horse\\AugmentforKeypoints\\labels/val_coco.json')`
```

Below is my data form：
```
`dataset_info = dict(
    dataset_name='HorsePoseDataset',
    paper_info=dict(
        author='Lin, Tsung-Yi and Maire, Michael and '
        'Belongie, Serge and Hays, James and '
        'Perona, Pietro and Ramanan, Deva and '
        r'Doll{\'a}r, Piotr and Zitnick, C Lawrence',
        title='Microsoft coco: Common objects in context',
        container='European conference on computer vision',
        year='2014',
        homepage='http://cocodataset.org/',
    ),
    keypoint_info={
        0:
        dict(name='nose', id=0, color=[51, 153, 255], type='upper', swap=''),
        1:
        dict(
            name='head',
            id=1,
            color=[51, 153, 255],
            type='upper',
            swap=''),
        2:
        dict(
            name='neck',
            id=2,
            color=[51, 153, 255],
            type='upper',
            swap=''),
        3:
        dict(
            name='hip',
            id=3,
            color=[51, 153, 255],
            type='upper',
            swap=''),
        4:
        dict(
            name='rear_right_leg_root',
            id=4,
            color=[51, 153, 255],
            type='upper',
            swap='rear_left_leg_root'),
        5:
        dict(
            name='rear_right_leg_knee',
            id=5,
            color=[0, 255, 0],
            type='upper',
            swap='rear_left_leg_knee'),
        6:
        dict(
            name='rear_right_leg_hoof',
            id=6,
            color=[255, 128, 0],
            type='upper',
            swap='rear_left_leg_hoof'),
        7:
        dict(
            name='rear_left_leg_root',
            id=7,
            color=[0, 255, 0],
            type='upper',
            swap='rear_right_leg_root'),
        8:
        dict(
            name='rear_left_leg_knee',
            id=8,
            color=[255, 128, 0],
            type='upper',
            swap='rear_right_leg_knee'),
        9:
        dict(
            name='rear_left_leg_hoof',
            id=9,
            color=[0, 255, 0],
            type='upper',
            swap='rear_right_leg_hoof'),
        10:
        dict(
            name='front_right_leg_root',
            id=13,
            color=[0, 255, 0],
            type='lower',
            swap='front_left_leg_root'),
        11:
        dict(
            name='front_right_leg_knee',
            id=14,
            color=[255, 128, 0],
            type='lower',
            swap='front_left_leg_knee'),
        12:
        dict(
            name='front_right_leg_hoof',
            id=15,
            color=[0, 255, 0],
            type='lower',
            swap='front_left_leg_hoof'),
        13:
        dict(
            name='front_left_leg_root',
            id=16,
            color=[255, 128, 0],
            type='lower',
            swap='front_right_leg_root'),
        14:
        dict(
            name='front_left_leg_knee',
            id=16,
            color=[255, 128, 0],
            type='lower',
            swap='front_right_leg_knee'),
        15:
        dict(
            name='front_left_leg_hoof',
            id=16,
            color=[255, 128, 0],
            type='lower',
            swap='front_right_leg_hoof'),
    },
    skeleton_info={
        0:
        dict(link=('nose', 'head'), id=0, color=[0, 255, 0]),
        1:
        dict(link=('head', 'neck'), id=1, color=[0, 255, 0]),
        2:
        dict(link=('neck', 'hip'), id=2, color=[255, 128, 0]),
        3:
        dict(link=('hip', 'rear_right_leg_root'), id=3, color=[255, 128, 0]),
        4:
        dict(link=('hip', 'rear_left_leg_root'), id=4, color=[51, 153, 255]),
        5:
        dict(link=('neck', 'front_right_leg_root'), id=5, color=[51, 153, 255]),
        6:
        dict(link=('neck', 'front_left_leg_root'), id=6, color=[51, 153, 255]),
        7:
        dict(
            link=('rear_right_leg_root', 'rear_right_leg_knee'),
            id=7,
            color=[51, 153, 255]),
        8:
        dict(link=('rear_right_leg_knee', 'rear_right_leg_hoof'), id=8, color=[0, 255, 0]),
        9:
        dict(
            link=('rear_left_leg_root', 'rear_left_leg_knee'), id=9, color=[255, 128, 0]),
        10:
        dict(link=('rear_left_leg_knee', 'rear_left_leg_hoof'), id=10, color=[0, 255, 0]),
        11:
        dict(link=('front_right_leg_root', 'front_right_leg_knee'), id=11, color=[255, 128, 0]),
        12:
        dict(link=('front_right_leg_knee', 'front_right_leg_hoof'), id=12, color=[51, 153, 255]),
        13:
        dict(link=('front_left_leg_root', 'front_left_leg_knee'), id=13, color=[51, 153, 255]),
        14:
        dict(link=('front_left_leg_knee', 'front_left_leg_hoof'), id=14, color=[51, 153, 255]),
    },
    joint_weights=[
        1., 1., 1., 1., 1., 1., 1., 1.2, 1.2, 1.5, 1.5, 1., 1., 1.2, 1.2
    ],
    sigmas=[
        0.026, 0.025, 0.025, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072, 0.062,
        0.062, 0.107, 0.107, 0.087, 0.087, 0.089
    ])
`
```
```
`# Copyright (c) OpenMMLab. All rights reserved.
from mmpose.registry import DATASETS
from ..base import BaseCocoStyleDataset

@DATASETS.register_module(name='HorseAnimalDataset')
class HorseAnimalDataset(BaseCocoStyleDataset):
    METAINFO: dict = dict(from_file='D:\Code\mmpose-1.1.0\configs\_base_\datasets\horse.py')
`
```

When I run the command 'python .\tools\train.py .\configs\animal_2d_keypoint\topdown_heatmap\animalpose\td-hm_hrnet-w32_8xb64-210e_animalpose-256x256.py', it reported the following error：
```
`Traceback (most recent call last):
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmpose\datasets\datasets\base\base_coco_style_dataset.py", line 98, in __init__
    super().__init__(
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\dataset\base_dataset.py", line 245, in __init__
    self.full_init()
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\dataset\base_dataset.py", line 305, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\dataset\base_dataset.py", line 765, in _serialize_data
    data_bytes = np.concatenate(data_list)
ValueError: need at least one array to concatenate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\mmpose-1.1.0\tools\train.py", line 161, in <module>
    main()
  File "D:\Code\mmpose-1.1.0\tools\train.py", line 157, in main
    runner.train()
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\runner\runner.py", line 1701, in train
    self._train_loop = self.build_train_loop(
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\runner\runner.py", line 1500, in build_train_loop
    loop = EpochBasedTrainLoop(
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\runner\loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\runner\base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\runner\runner.py", line 1351, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\registry\build_functions.py", line 144, in build_from_cfg
    raise type(e)(
ValueError: class `HorseAnimalDataset` in mmpose/datasets/datasets/animal/horse_animal_dataset.py: need at least one array to concatenate`
```

**Comment by Ben-Louis** [comment]
It seems like there could be issues with the path setting for your dataset. To ensure proper placement of your images, they should be stored in the directory `{data_root}/{data_prefix['img']}`.

**Comment by hsp2454** [comment]
Do you add the path to the image in the configuration file?
![image](https://github.com/open-mmlab/mmpose/assets/115400289/767623a5-308f-4a29-833e-2cfbd74ca79f)

**Comment by Tau-J** [comment]
Hi @hsp2454 , I notice that you are running on windows platform. You need to use `/` or `r'D:\'` in your string path.

**Comment by hsp2454** [comment]
Sorry, I still report an error after modifying according to your suggestion

```
_base_ = ['../../../_base_/default_runtime.py']

# runtime
train_cfg = dict(max_epochs=210, val_interval=10)

# optimizer
optim_wrapper = dict(optimizer=dict(
    type='Adam',
    lr=5e-4,
))

# learning policy
param_scheduler = [
    dict(
        type='LinearLR', begin=0, end=500, start_factor=0.001,
        by_epoch=False),  # warm-up
    dict(
        type='MultiStepLR',
        begin=0,
        end=210,
        milestones=[170, 200],
        gamma=0.1,
        by_epoch=True)
]

# automatically scaling LR based on the actual training batch size
auto_scale_lr = dict(base_batch_size=512)

# hooks
default_hooks = dict(checkpoint=dict(save_best='coco/AP', rule='greater'))

# codec settings
codec = dict(
    type='MSRAHeatmap', input_size=(256, 256), heatmap_size=(64, 64), sigma=2)

# model settings
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(32, 64)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(32, 64, 128)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(32, 64, 128, 256))),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmpose/'
            'pretrain_models/hrnet_w32-36af842e.pth'),
    ),
    head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=16,
        deconv_out_channels=None,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        decoder=codec),
    test_cfg=dict(
        flip_test=True,
        flip_mode='heatmap',
        shift_heatmap=True,
    ))

# base dataset settings
dataset_type = 'HorseAnimalDataset'
data_mode = 'topdown'
data_root = 'data/horse/AugmentforKeypoints/labels/'

# pipelines
train_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='GenerateTarget', encoder=codec),
    dict(type='PackPoseInputs')
]
val_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='PackPoseInputs')
]

# data loaders
train_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='train_coco.json',
        data_prefix=dict(img='train2017/'),
        pipeline=train_pipeline,
        metainfo=dict(from_file='configs/_base_/datasets/horse.py')
    ))
val_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='val_coco.json',
        data_prefix=dict(img='val2017/'),
        test_mode=True,
        pipeline=val_pipeline,
        metainfo=dict(from_file='configs/_base_/datasets/horse.py')
    ))
test_dataloader = val_dataloader

# evaluators
val_evaluator = dict(
    type='CocoMetric', ann_file=data_root + 'val_coco.json')
test_evaluator = val_evaluator
```
![image](https://github.com/open-mmlab/mmpose/assets/115400289/97d30491-6489-474b-8ac9-cb89827940c4)

**Comment by lbq779660843** [comment]
I have two custom datasets, one can work fine but the other one meets the same error.

**Comment by lbq779660843** [comment]
I find my problem is that I set some labels 'iscrowd' to **1**, it must be **0**  if annotating object one by one.
