### ISSUE TITLE
[Bug] Cannot reproduce TCFormer on MSCOCOWholeBody

### ISSUE THREAD

**Issue by GuKerui** [open-mmlab/mmpose#2586]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

{'sys.platform': 'linux', 'Python': '3.9.17 (main, Jul  5 2023, 20:41:20) [GCC 11.2.0]', 'CUDA available': True, 'GPU 0,1,2,3,4,5,6,7': 'NVIDIA RTX A5000', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Cuda compilation tools, release 11.3, V11.3.58', 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0', 'PyTorch': '1.13.1', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.6\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.3.2  (built against CUDA 11.5)\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n', 'TorchVision': '0.14.1', 'OpenCV': '4.8.0', 'MMCV': '1.5.0', 'MMCV Compiler': 'GCC 9.4', 'MMCV CUDA Compiler': '11.3', 'MMPose': '0.28.0+aaff2b7'}

mmcls               0.25.0
mmcv-full           1.5.0
mmdet               2.28.2
mmpose              0.28.0
mmtrack             0.14.0

### Reproduces the problem - code sample

I didn't change anything following the instructions of TCFormer.

### Reproduces the problem - command or script

MASTER_PORT=29599 ./tools/dist_train.sh configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/tcformer_mta_coco_wholebody_256x192.py 2 --work-dir work_dirs/wholebody/tcformer_mta_256

### Reproduces the problem - error message

^CTraceback (most recent call last):
  File "/home/kerui/projects/TCFormer/pose/./tools/train.py", line 175, in <module>
Traceback (most recent call last):
  File "/home/kerui/projects/TCFormer/pose/./tools/train.py", line 175, in <module>
    main()
  File "/home/kerui/projects/TCFormer/pose/./tools/train.py", line 150, in main
    main()
      File "/home/kerui/projects/TCFormer/pose/./tools/train.py", line 150, in main
datasets = [build_dataset(cfg.data.train)]
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/builder.py", line 87, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    datasets = [build_dataset(cfg.data.train)]
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/builder.py", line 87, in build_dataset
    return obj_cls(**args)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py", line 83, in __init__
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    self.db = self._get_db()
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 101, in _get_db
    return obj_cls(**args)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py", line 83, in __init__
    gt_db = self._load_coco_keypoint_annotations()
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 111, in _load_coco_keypoint_annotations
    self.db = self._get_db()
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 101, in _get_db
    gt_db.extend(self._load_coco_keypoint_annotation_kernel(img_id))
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py", line 131, in _load_coco_keypoint_annotation_kernel
    gt_db = self._load_coco_keypoint_annotations()
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 111, in _load_coco_keypoint_annotations
    keypoints = np.array(obj['keypoints'] + obj['foot_kpts'] +
KeyboardInterrupt    gt_db.extend(self._load_coco_keypoint_annotation_kernel(img_id))

  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py", line 132, in _load_coco_keypoint_annotation_kernel
    obj['face_kpts'] + obj['lefthand_kpts'] +
KeyboardInterrupt
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 331270 closing signal SIGINT
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 331274 closing signal SIGINT
^CWARNING:torch.distributed.elastic.multiprocessing.api:Sending process 331274 closing signal SIGTERM
Traceback (most recent call last):
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 331199 got signal: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 716, in run
    self._shutdown(e.sigval)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 289, in _shutdown
    self._pcontext.close(death_sig)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 332, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 709, in _close
    handler.proc.wait(time_to_wait)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/subprocess.py", line 1927, in _wait
    time.sleep(delay)
  File "/home/kerui/miniconda3/envs/mmpose/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 331199 got signal: 2

### Additional information

mostly I want to know how to train TCFormer in this mmpose v1.0.x or previous mmpose v0.x?

**Comment by GuKerui** [comment]
Hi, I have a follow-up to better understand this issue.

1) I can run inference. 2) When I set distributed=False, I can run MMDP on a single GPU.
