### ISSUE TITLE
[Bug] multi-frame inference in demo/body3d_pose_lifter_demo.py

### ISSUE THREAD

**Issue by unrealMJ** [open-mmlab/mmpose#2592]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

![image](https://github.com/open-mmlab/mmpose/assets/45420156/fa358558-4221-4a05-a26a-796e68430acc)

![image](https://github.com/open-mmlab/mmpose/assets/45420156/f336dcd1-f52d-412e-bd59-9af06e102c45)

### Reproduces the problem - code sample

```shell
python  demo/body3d_pose_lifter_demo.py  \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  \
configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth  \
configs/body_3d_keypoint/pose_lift/h36m/pose-lift_videopose3d-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth  \
--input https://user-images.githubusercontent.com/87690686/164970135-b14e424c-765a-4180-9bc8-fa8d6abc5510.mp4 \
--output-root  vis_results  \
--use-multi-frames
```

### Reproduces the problem - command or script

```shell
python  demo/body3d_pose_lifter_demo.py  \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  \
configs/body_2d_keypoint/topdown_heatmap/posetrack18/td-hm_hrnet-w48_8xb64-20e_posetrack18-384x288.py \
https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_posetrack18_384x288-5fd6d3ff_20211130.pth  \
configs/body_3d_keypoint/pose_lift/h36m/pose-lift_videopose3d-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth  \
--input https://user-images.githubusercontent.com/87690686/164970135-b14e424c-765a-4180-9bc8-fa8d6abc5510.mp4 \
--output-root  vis_results  \
--use-multi-frames
```

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/mnt/petrelfs/majie/project/openmmlab/mmpose/demo/body3d_pose_lifter_demo.py", line 569, in <module>
    main()
  File "/mnt/petrelfs/majie/project/openmmlab/mmpose/demo/body3d_pose_lifter_demo.py", line 395, in main
    assert 'frame_indices' in pose_estimator.cfg.test_dataloader.dataset
AssertionError

### Additional information

1. the parser doesn't contain the **--online** option, see line 498 in body3d_pose_lifter_demo.py
2. reference docs https://github.com/open-mmlab/mmpose/blob/dev-1.x/demo/docs/en/3d_human_pose_demo.md

**Comment by unrealMJ** [comment]
Besides, the body3d_pose_lifter_demo.py can't visualize pose in branch dev-1.x

This is main branch:
![video_clip_pose](https://github.com/open-mmlab/mmpose/assets/45420156/85c88acb-7334-400e-b0fd-54e96077c455)

This is dev-1.x branch:

![video_clip1_x](https://github.com/open-mmlab/mmpose/assets/45420156/a25bde13-5cc7-4dea-b2e2-8af0d9f6793e)

**Comment by Tau-J** [comment]
Thanks for you feedback. We will fix it in https://github.com/open-mmlab/mmpose/pull/2594 .
