### ISSUE TITLE
[Bug] ddp training on multiple GPUs, when validate the error arise

### ISSUE THREAD

**Issue by wxhqw** [open-mmlab/mmpose#2622]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

albumentations
mmcv==2.0.1
mmdet==3.1.0
mmengine==0.8.4
requests
munkres
regex
scipy
titlecase
xtcocotools>=1.13
chumpy
json_tricks
matplotlib
munkres
numpy
opencv-python
pillow
scipy
coverage
flake8
interrogate
isort==4.3.21
parameterized
pytest
pytest-runner
xdoctest>=0.10.0
torch==1.11.0
torchvision==0.12.0+cu113

### Reproduces the problem - code sample

python3 -m torch.distributed.launch \
        --nnodes ${WORKER_NUM} \
		--node_rank ${ID} \
		--master_addr ${WORKER_0_HOST} \
		--master_port ${PORT} \
		--nproc_per_node ${WORKER_GPU} tools/train.py \
        $CONFIG --launcher pytorch

### Reproduces the problem - command or script

on 1.x branch , training the rtmpose on multiple GPUs, runnig comman is:
python3 -m torch.distributed.launch \
        --nnodes ${WORKER_NUM} \
		--node_rank ${ID} \
		--master_addr ${WORKER_0_HOST} \
		--master_port ${PORT} \
		--nproc_per_node ${WORKER_GPU} tools/train.py \
        $CONFIG --launcher pytorch

### Reproduces the problem - error message

/usr/local/lib/python3.7/dist-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.2.0)/charset_normalizer (None) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.2.0)/charset_normalizer (None) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.2.0)/charset_normalizer (None) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.2.0)/charset_normalizer (None) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
  File "tools/train.py", line 161, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    main()
  File "tools/train.py", line 157, in main
    runner.train()
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/runner.py", line 1745, in train
    runner.train()
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/runner.py", line 1745, in train
        main()main()

  File "tools/train.py", line 157, in main
  File "tools/train.py", line 157, in main
        runner.train()runner.train()

  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/runner.py", line 1745, in train
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/runner.py", line 1745, in train
        model = self.train_loop.run()  # type: ignoremodel = self.train_loop.run()  # type: ignore        

model = self.train_loop.run()  # type: ignoremodel = self.train_loop.run()  # type: ignore  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 102, in run
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 102, in run

  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 102, in run
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 102, in run
                self.runner.val_loop.run()self.runner.val_loop.run()self.runner.val_loop.run()self.runner.val_loop.run()

  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 366, in run
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 366, in run
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 366, in run
  File "/usr/local/lib/python3.7/dist-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
      File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
      File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))metrics = self.evaluator.evaluate(len(self.dataloader.dataset))

  File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
  File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
                _results = metric.evaluate(size)_results = metric.evaluate(size)_results = metric.evaluate(size)_results = metric.evaluate(size)

  File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/metric.py", line 126, in evaluate
  File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/metric.py", line 126, in evaluate
  File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/metric.py", line 126, in evaluate
  File "/usr/local/lib/python3.7/dist-packages/mmengine/evaluator/metric.py", line 126, in evaluate
            tmpdir=self.collect_dir)tmpdir=self.collect_dir)tmpdir=self.collect_dir)    

tmpdir=self.collect_dir)  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 931, in collect_results
  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 931, in collect_results
  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 931, in collect_results

  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 931, in collect_results
    return collect_results_cpu(results, size, tmpdir)            
return collect_results_cpu(results, size, tmpdir)return collect_results_cpu(results, size, tmpdir)return collect_results_cpu(results, size, tmpdir)  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 990, in collect_results_cpu

  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 990, in collect_results_cpu
  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 990, in collect_results_cpu
  File "/usr/local/lib/python3.7/dist-packages/mmengine/dist/dist.py", line 990, in collect_results_cpu
    with open(osp.join(tmpdir, f'part_{rank}.pkl'), 'wb') as f:  # type: ignore
    with open(osp.join(tmpdir, f'part_{rank}.pkl'), 'wb') as f:  # type: ignore
    FileNotFoundError    : with open(osp.join(tmpdir, f'part_{rank}.pkl'), 'wb') as f:  # type: ignoreFileNotFoundErrorwith open(osp.join(tmpdir, f'part_{rank}.pkl'), 'wb') as f:  # type: ignore: [Errno 2] No such file or directory: '.dist_test/tmp675p5blf/part_6.pkl'

[Errno 2] No such file or directory: '.dist_test/tmp675p5blf/part_5.pkl'

FileNotFoundErrorFileNotFoundError: [Errno 2] No such file or directory: '.dist_test/tmp675p5blf/part_7.pkl'
: [Errno 2] No such file or directory: '.dist_test/tmp675p5blf/part_4.pkl'
/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2241) of binary: /usr/bin/python3
ERROR:torch.distributed.elastic.agent.server.api:Error waiting on exit barrier. Elapsed: 987.5974795818329 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/agent/server/api.py", line 912, in _exit_barrier
    barrier_timeout=self._exit_barrier_timeout,
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/utils/store.py", line 67, in barrier
    synchronize(store, data, rank, world_size, key_prefix, barrier_timeout)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/utils/store.py", line 53, in synchronize
    agent_data = get_all(store, key_prefix, world_size)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/utils/store.py", line 31, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED

### Additional information

the log only the device 0 has, the devices 1 doesn't have

**Comment by Ben-Louis** [comment]
According to the error reported, process 4-7 can not access the folder created by process 0. Did you use one machine to run the training?

**Comment by wxhqw** [comment]
> According to the error reported, process 4-7 can not access the folder created by process 0. Did you use one machine to run the training?

use two machines, every machine has 4 gpus

**Comment by Ben-Louis** [comment]
By default, the results generated by different processes are collected by the CPU, which is not applicable in your case. To change this, you could specify `val_evaluator=dict(..., collect_device='gpu')` in your config file.

**Comment by wxhqw** [comment]
> By default, the results generated by different processes are collected by the CPU, which is not applicable in your case. To change this, you could specify `val_evaluator=dict(..., collect_device='gpu')` in your config file.
ok，i make a try
