### ISSUE TITLE
AttributeError: class `YOLODetector` in mmyolo/models/detectors/yolo_detector.py: class `YOLOXPoseHead` in models/yolox_pose_head.py: 'YOLOXPoseHead' object has no attribute 'sampler'

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmpose#2671]
### 📚 The doc issue

When I use bottomup_demo.py or image_demo.py to run projects/yolox_pose/configs/lameness_pig_yolox-pose_s_8xb32-300e_coco.py, it reports the following error：
(action) D:\Code\mmpose-1.1.0>python demo\image_demo.py data/pig/lameness_20230822luoding/coco/val/frame_0_3.jpg projects\yolox_pose\configs\lameness_pig_yolox-pose_s_8xb32-300e_coco.py work_dirs\lameness_pig_yolox-pose_s_8
xb32-300e_coco\best_coco_AP_epoch_300.pth --out-file vis_results
```
Traceback (most recent call last):
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\Code\mmpose-1.1.0\projects\yolox_pose\models\yolox_pose_head.py", line 95, in __init__
    self.sampler = OutputSaveObjectWrapper(self.sampler)
  File "E:\software\Anaconda\envs\action\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'YOLOXPoseHead' object has no attribute 'sampler'

During handling of the above exception, another exception occurred:

    model = build_pose_estimator(config.model)
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmpose\models\builder.py", line 35, in build_pose_estimator
    return POSE_ESTIMATORS.build(cfg)
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\registry\build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "E:\software\Anaconda\envs\action\lib\site-packages\mmengine\registry\build_functions.py", line 144, in build_from_cfg
    raise type(e)(
AttributeError: class `YOLODetector` in mmyolo/models/detectors/yolo_detector.py: class `YOLOXPoseHead` in models/yolox_pose_head.py: 'YOLOXPoseHead' object has no attribute 'sampler'
```
Below is the content of my configuration file：
Config:
```
default_scope = 'mmyolo'
custom_imports = dict(imports=[
    'models',
    'datasets',
])
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook',
        interval=10,
        max_keep_ckpts=3,
        save_best='coco/AP',
        rule='greater'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='mmpose.PoseVisualizationHook', enable=False))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    type='mmpose.PoseLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ],
    name='visualizer')
log_processor = dict(
    type='LogProcessor', window_size=50, by_epoch=True, num_digits=6)
log_level = 'INFO'
load_from = None
resume = False
backend_args = dict(backend='local')
train_cfg = dict(
    type='EpochBasedTrainLoop',
    max_epochs=300,
    val_interval=10,
    dynamic_intervals=[
        (
            280,
            1,
        ),
    ])
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
model = dict(
    type='YOLODetector',
    use_syncbn=False,
    init_cfg=dict(
        type='Pretrained',
        checkpoint=
        'https://download.openmmlab.com/mmyolo/v0/yolox/yolox_s_fast_8xb32-300e-rtmdet-hyp_coco/yolox_s_fast_8xb32-300e-rtmdet-hyp_coco_20230210_134645-3a8dfbd7.pth'
    ),
    data_preprocessor=dict(
        type='mmdet.DetDataPreprocessor',
        pad_size_divisor=32,
        batch_augments=[
            dict(
                type='PoseBatchSyncRandomResize',
                random_size_range=(
                    480,
                    800,
                ),
                size_divisor=32,
                interval=1),
        ]),
    backbone=dict(
        type='YOLOXCSPDarknet',
        deepen_factor=0.33,
        widen_factor=0.5,
        out_indices=(
            2,
            3,
            4,
        ),
        spp_kernal_sizes=(
            5,
            9,
            13,
        ),
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True)),
    neck=dict(
        type='YOLOXPAFPN',
        deepen_factor=0.33,
        widen_factor=0.5,
        in_channels=[
            256,
            512,
            1024,
        ],
        out_channels=256,
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True)),
    bbox_head=dict(
        type='YOLOXPoseHead',
        head_module=dict(
            type='YOLOXPoseHeadModule',
            num_classes=1,
            in_channels=256,
            feat_channels=256,
            widen_factor=0.5,
            stacked_convs=2,
            num_keypoints=17,
            featmap_strides=(
                8,
                16,
                32,
            ),
            use_depthwise=False,
            norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
            act_cfg=dict(type='SiLU', inplace=True)),
        loss_cls=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='sum',
            loss_weight=1.0),
        loss_bbox=dict(
            type='mmdet.IoULoss',
            mode='square',
            eps=1e-16,
            reduction='sum',
            loss_weight=5.0),
        loss_obj=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='sum',
            loss_weight=1.0),
        loss_pose=dict(
            type='OksLoss',
            metainfo='configs\\_base_\\datasets\\lameness_pig.py',
            loss_weight=30.0),
        loss_bbox_aux=dict(
            type='mmdet.L1Loss', reduction='sum', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='PoseSimOTAAssigner',
            center_radius=2.5,
            iou_calculator=dict(type='mmdet.BboxOverlaps2D'),
            oks_calculator=dict(
                type='OksLoss',
                metainfo='configs\\_base_\\datasets\\lameness_pig.py'))),
    test_cfg=dict(
        yolox_style=True,
        multi_label=False,
        score_thr=0.001,
        max_per_img=300,
        nms=dict(type='nms', iou_threshold=0.65)))
img_scale = (
    640,
    640,
)
pre_transform = [
    dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
    dict(type='PoseToDetConverter'),
]
train_pipeline_stage1 = [
    dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
    dict(type='PoseToDetConverter'),
    dict(
        type='Mosaic',
        img_scale=(
            640,
            640,
        ),
        pad_val=114.0,
        pre_transform=[
            dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
            dict(type='PoseToDetConverter'),
        ]),
    dict(
        type='mmdet.RandomAffine',
        scaling_ratio_range=(
            0.75,
            1.0,
        ),
        border=(
            -320,
            -320,
        )),
    dict(
        type='YOLOXMixUp',
        img_scale=(
            640,
            640,
        ),
        ratio_range=(
            0.8,
            1.6,
        ),
        pad_val=114.0,
        pre_transform=[
            dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
            dict(type='PoseToDetConverter'),
        ]),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(type='mmdet.RandomFlip', prob=0.5),
    dict(type='FilterDetPoseAnnotations', keep_empty=False),
    dict(
        type='PackDetPoseInputs',
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
        )),
]
train_pipeline_stage2 = [
    dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
    dict(type='PoseToDetConverter'),
    dict(type='mmdet.Resize', scale=(
        640,
        640,
    ), keep_ratio=True),
    dict(
        type='mmdet.Pad',
        pad_to_square=True,
        pad_val=dict(img=(
            114.0,
            114.0,
            114.0,
        ))),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(type='mmdet.RandomFlip', prob=0.5),
    dict(type='FilterDetPoseAnnotations', keep_empty=False),
    dict(type='PackDetPoseInputs'),
]
test_pipeline = [
    dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
    dict(type='PoseToDetConverter'),
    dict(type='mmdet.Resize', scale=(
        640,
        640,
    ), keep_ratio=True),
    dict(
        type='mmdet.Pad',
        pad_to_square=True,
        pad_val=dict(img=(
            114.0,
            114.0,
            114.0,
        ))),
    dict(
        type='PackDetPoseInputs',
        meta_keys=(
            'id',
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'flip_indices',
        )),
]
dataset_type = 'LamenessPigDataset'
data_mode = 'bottomup'
data_root = 'data/pig/lameness_20230822luoding/coco/'
train_dataloader = dict(
    batch_size=16,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='LamenessPigDataset',
        data_mode='bottomup',
        data_root='data/pig/lameness_20230822luoding/coco/',
        ann_file='annotations/keypoints_train.json',
        data_prefix=dict(img='train/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
        pipeline=[
            dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
            dict(type='PoseToDetConverter'),
            dict(
                type='Mosaic',
                img_scale=(
                    640,
                    640,
                ),
                pad_val=114.0,
                pre_transform=[
                    dict(
                        type='mmpose.LoadImage',
                        backend_args=dict(backend='local')),
                    dict(type='PoseToDetConverter'),
                ]),
            dict(
                type='mmdet.RandomAffine',
                scaling_ratio_range=(
                    0.75,
                    1.0,
                ),
                border=(
                    -320,
                    -320,
                )),
            dict(
                type='YOLOXMixUp',
                img_scale=(
                    640,
                    640,
                ),
                ratio_range=(
                    0.8,
                    1.6,
                ),
                pad_val=114.0,
                pre_transform=[
                    dict(
                        type='mmpose.LoadImage',
                        backend_args=dict(backend='local')),
                    dict(type='PoseToDetConverter'),
                ]),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(type='mmdet.RandomFlip', prob=0.5),
            dict(type='FilterDetPoseAnnotations', keep_empty=False),
            dict(
                type='PackDetPoseInputs',
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                )),
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='LamenessPigDataset',
        data_mode='bottomup',
        data_root='data/pig/lameness_20230822luoding/coco/',
        ann_file='annotations/keypoints_val.json',
        data_prefix=dict(img='val/'),
        test_mode=True,
        pipeline=[
            dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
            dict(type='PoseToDetConverter'),
            dict(type='mmdet.Resize', scale=(
                640,
                640,
            ), keep_ratio=True),
            dict(
                type='mmdet.Pad',
                pad_to_square=True,
                pad_val=dict(img=(
                    114.0,
                    114.0,
                    114.0,
                ))),
            dict(
                type='PackDetPoseInputs',
                meta_keys=(
                    'id',
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'flip_indices',
                )),
        ]))
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='LamenessPigDataset',
        data_mode='bottomup',
        data_root='data/pig/lameness_20230822luoding/coco/',
        ann_file='annotations/keypoints_val.json',
        data_prefix=dict(img='val/'),
        test_mode=True,
        pipeline=[
            dict(type='mmpose.LoadImage', backend_args=dict(backend='local')),
            dict(type='PoseToDetConverter'),
            dict(type='mmdet.Resize', scale=(
                640,
                640,
            ), keep_ratio=True),
            dict(
                type='mmdet.Pad',
                pad_to_square=True,
                pad_val=dict(img=(
                    114.0,
                    114.0,
                    114.0,
                ))),
            dict(
                type='PackDetPoseInputs',
                meta_keys=(
                    'id',
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'flip_indices',
                )),
        ]))
val_evaluator = dict(
    type='mmpose.CocoMetric',
    ann_file=
    'data/pig/lameness_20230822luoding/coco/annotations/keypoints_val.json',
    score_mode='bbox')
test_evaluator = dict(
    type='mmpose.CocoMetric',
    ann_file=
    'data/pig/lameness_20230822luoding/coco/annotations/keypoints_val.json',
    score_mode='bbox')
base_lr = 0.004
max_epochs = 300
num_last_epochs = 20
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=0.004, weight_decay=0.05),
    paramwise_cfg=dict(
        norm_decay_mult=0, bias_decay_mult=0, bypass_duplicate=True))
param_scheduler = [
    dict(
        type='mmdet.QuadraticWarmupLR',
        by_epoch=True,
        begin=0,
        end=5,
        convert_to_iter_based=True),
    dict(
        type='CosineAnnealingLR',
        eta_min=0.0002,
        begin=5,
        T_max=280,
        end=280,
        by_epoch=True,
        convert_to_iter_based=True),
    dict(type='ConstantLR', by_epoch=True, factor=1, begin=280, end=300),
]
custom_hooks = [
    dict(
        type='YOLOXModeSwitchHook',
        num_last_epochs=20,
        new_train_pipeline=[
    dict(type='mmdet.SyncNormHook', priority=48),
    dict(
        type='EMAHook',
        ema_type='ExpMomentumEMA',
        momentum=0.0002,
        update_buffers=True,
        strict_load=False,
        priority=49),
]
auto_scale_lr = dict(base_batch_size=256)
```

**Comment by Ben-Louis** [comment]
Sorry but the 'yolox_pose' project in MMPose is only compatible with mmyolo version 0.5.0. To use this project, please install mmyolo 0.5.0 by running `mim install mmyolo==0.5.0`.

We're currently in the process of updating yolox-pose, and once that's done, it should be compatible with mmyolo

**Comment by hsp2454** [comment]
Sorry, I have already installed mmyolo0.5.0, but it reported some error
![image](https://github.com/open-mmlab/mmpose/assets/115400289/927a1922-b86b-4692-bc70-2e1f3de211dd)

**Comment by Ben-Louis** [comment]
Please follow [this guide](https://github.com/open-mmlab/mmpose/blob/main/projects/yolox_pose/README.md#inference) for inference with yolox-pose. Additionally, don't forget to set the `PYTHONPATH`
