### ISSUE TITLE
[Bug] export RTMdet to onnx

### ISSUE THREAD

**Issue by Haroldhy** [open-mmlab/mmpose#2686]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

09/12 17:02:11 - mmengine - INFO - **********Environmental information**********
09/12 17:02:16 - mmengine - INFO - sys.platform: win32
09/12 17:02:16 - mmengine - INFO - Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
09/12 17:02:16 - mmengine - INFO - CUDA available: True
09/12 17:02:16 - mmengine - INFO - numpy_random_seed: 2147483648
09/12 17:02:16 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1080 Ti
09/12 17:02:16 - mmengine - INFO - GPU 1: NVIDIA GeForce GTX 1070 Ti
09/12 17:02:16 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
09/12 17:02:16 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.0, V11.0.221
09/12 17:02:16 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32537 版
09/12 17:02:16 - mmengine - INFO - GCC: n/a
09/12 17:02:16 - mmengine - INFO - PyTorch: 1.8.1+cu111
09/12 17:02:16 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

09/12 17:02:16 - mmengine - INFO - TorchVision: 0.9.1+cu111
09/12 17:02:16 - mmengine - INFO - OpenCV: 4.8.0
09/12 17:02:16 - mmengine - INFO - MMEngine: 0.8.4
09/12 17:02:16 - mmengine - INFO - MMCV: 2.0.1
09/12 17:02:16 - mmengine - INFO - MMCV Compiler: MSVC 192930148
09/12 17:02:16 - mmengine - INFO - MMCV CUDA Compiler: 11.1
09/12 17:02:16 - mmengine - INFO - MMDeploy: 1.2.0+6e60cae
09/12 17:02:16 - mmengine - INFO -

09/12 17:02:16 - mmengine - INFO - **********Backend information**********
09/12 17:02:16 - mmengine - INFO - tensorrt:    8.5.2.2
09/12 17:02:16 - mmengine - INFO - tensorrt custom ops: Available
09/12 17:02:17 - mmengine - INFO - ONNXRuntime: 1.8.1
09/12 17:02:17 - mmengine - INFO - ONNXRuntime-gpu:     None
09/12 17:02:17 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/12 17:02:17 - mmengine - INFO - pplnn:       None
09/12 17:02:17 - mmengine - INFO - ncnn:        None
09/12 17:02:17 - mmengine - INFO - snpe:        None
09/12 17:02:17 - mmengine - INFO - openvino:    None
09/12 17:02:17 - mmengine - INFO - torchscript: 1.8.1+cu111
09/12 17:02:17 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/12 17:02:17 - mmengine - INFO - rknn-toolkit:        None
09/12 17:02:17 - mmengine - INFO - rknn-toolkit2:       None
09/12 17:02:17 - mmengine - INFO - ascend:      None
09/12 17:02:17 - mmengine - INFO - coreml:      None
09/12 17:02:17 - mmengine - INFO - tvm: None
09/12 17:02:17 - mmengine - INFO - vacc:        None
09/12 17:02:17 - mmengine - INFO -

09/12 17:02:17 - mmengine - INFO - **********Codebase information**********
09/12 17:02:17 - mmengine - INFO - mmdet:       3.1.0
09/12 17:02:17 - mmengine - INFO - mmseg:       None
09/12 17:02:17 - mmengine - INFO - mmpretrain:  1.0.2
09/12 17:02:17 - mmengine - INFO - mmocr:       None
09/12 17:02:17 - mmengine - INFO - mmagic:      None
09/12 17:02:17 - mmengine - INFO - mmdet3d:     None
09/12 17:02:17 - mmengine - INFO - mmpose:      1.1.0
09/12 17:02:17 - mmengine - INFO - mmrotate:    None
09/12 17:02:17 - mmengine - INFO - mmaction:    None
09/12 17:02:17 - mmengine - INFO - mmrazor:     None
09/12 17:02:17 - mmengine - INFO - mmyolo:      None

### Reproduces the problem - code sample

python .\convert_rtmdet.py --config ..\mmpose\projects\rtmpose\rtmdet\person\rtmdet_nano_320-8xb32_coco-person.py --checkpoint .\weights\rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth --output ..\mmpose\projects\rtmpose\examples\RTMPose-Deploy\Windows\TensorRT\python\rtmdet\

### Reproduces the problem - command or script

使用mmpose\projects\rtmpose\examples\RTMPose-Deploy\Windows\TensorRT\python/convert_rtmdet.py  发生报错：opset11不支持hardsigmoid操作，但是我没有在config以及其他地方看到使用这个操作的地方，请问我需要怎么解决这个问题呢？

### Reproduces the problem - error message

E:\anaconda3\envs\mmpose\lib\site-packages\torch\nn\functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File ".\convert_rtmdet.py", line 109, in <module>
    torch.onnx.export(
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 694, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 993, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 950, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\symbolic_registry.py", line 116, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator hardsigmoid to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by Haroldhy** [comment]
这个问题我已经解决了，我遇到了新的问题，报错代码如下所示：
E:\anaconda3\envs\mmpose\lib\site-packages\torch\nn\functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File ".\convert_rtmdet.py", line 108, in <module>
    torch.onnx.export(
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\onnx\utils.py", line 728, in _export
    with torch.serialization._open_file_like(f, 'wb') as opened_file:
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\anaconda3\envs\mmpose\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: '..\\mmpose\\projects\\rtmpose\\examples\\RTMPose-Deploy\\Windows\\TensorRT\\python\\rtmdet\\'

**Comment by Haroldhy** [comment]
以上问题均已解决，不需要回答了，抱歉
