### ISSUE TITLE
[Bug] MMpose Bottom-up demo unable to run

### ISSUE THREAD

**Issue by donovan361** [open-mmlab/mmpose#2747]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

```
OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.18 (default, Aug 25 2023, 13:20:30) [GCC 11.4.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'Tesla T4'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.8, V11.8.89'), ('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'), ('PyTorch', '2.0.1+cu117'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.7\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.5\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2+cu117'), ('OpenCV', '4.7.0'), ('MMEngine', '0.9.0'), ('MMPose', '1.1.0+')])
```

### Reproduces the problem - code sample

Running the demo command after installing all required dependencies for bottom-up does not work.

Here is to the google colab: https://colab.research.google.com/drive/1CTS_3meP0QKrLKLoji7hj1mcoorGC3FL?usp=sharing

Below is the code ran:

```
python mmpose/demo/bottomup_demo.py \
    configs/body_2d_keypoint/dekr/coco/dekr_hrnet-w32_8xb10-140e_coco-512x512.py \
    https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/dekr/coco/dekr_hrnet-w32_8xb10-140e_coco-512x512_ac7c17bf-20221228.pth \
    --input tests/data/coco/000000197388.jpg --output-root=vis_results \
    --save-predictions
```

### Reproduces the problem - command or script

As above

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "mmpose/demo/bottomup_demo.py", line 13, in <module>
    from mmpose.apis import inference_bottomup, init_model
  File "/usr/local/lib/python3.8/dist-packages/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottomup,
  File "/usr/local/lib/python3.8/dist-packages/mmpose/apis/inference.py", line 11, in <module>
    from mmengine.model.utils import revert_sync_batchnorm
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/__init__.py", line 6, in <module>
    from .base_model import BaseDataPreprocessor, BaseModel, ImgDataPreprocessor
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 9, in <module>
    from mmengine.optim import OptimWrapper
  File "/usr/local/lib/python3.8/dist-packages/mmengine/optim/__init__.py", line 2, in <module>
    from .optimizer import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/usr/local/lib/python3.8/dist-packages/mmengine/optim/optimizer/__init__.py", line 5, in <module>
    from .builder import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/usr/local/lib/python3.8/dist-packages/mmengine/optim/optimizer/builder.py", line 157, in <module>
    BITSANDBYTES_OPTIMIZERS = register_bitsandbytes_optimizers()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/optim/optimizer/builder.py", line 149, in register_bitsandbytes_optimizers
    _optim = getattr(bnb.optim, module_name)
AttributeError: module 'bitsandbytes.optim' has no attribute 'PagedAdam8bit'
```

### Additional information

1. It should have ran the demo with no issue
2. The demo dataset
3. I think the problem is the dependency "bitsandbytes" updated its module names

**Comment by Ben-Louis** [comment]
Hi @donovan361, would you be able to share the complete notebook file? I am unable to replicate the issue on Colab. You may try my notebook available at https://colab.research.google.com/drive/1W6UtrB2Wry_qhfueKfB-m-P3CbXnzhrr?usp=sharing.

**Comment by donovan361** [comment]
Hi @Ben-Louis, Apologies, I forgot to share the colab file. I have updated the link above and here: https://colab.research.google.com/drive/1CTS_3meP0QKrLKLoji7hj1mcoorGC3FL?usp=sharing

**Comment by donovan361** [comment]
Hi Ben,

Upgrading bits andd bytes solves the above issue but introduces another one.

I think for myself, downgrading mmengine back to 0.8.5 seems to solve the issue.

``!python3 -m mim install "mmengine==0.8.5"``
