### ISSUE TITLE
[Bug] 部署代码执行报错，前段时间都可以使用。今天就开始报错了。

### ISSUE THREAD

**Issue by vicnoah** [open-mmlab/mmpose#2777]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

```
OrderedDict([('sys.platform', 'linux'), ('Python', '3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'Tesla T4'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 11.8, V11.8.89'), ('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'), ('PyTorch', '2.1.0+cu118'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90\n  - CuDNN 8.7\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.16.0+cu118'), ('OpenCV', '4.8.0'), ('MMEngine', '0.9.0'), ('MMPose', '1.2.0+')])
```

```
community                        1.0.0b1
googleapis-common-protos         1.61.0
mmcv                             2.1.0
mmdeploy                         1.3.0
mmdeploy-runtime                 1.3.0
mmdet                            3.2.0
mmengine                         0.9.0
mmpose                           1.2.0
pyviz_comms                      3.0.0
snowballstemmer                  2.2.0
torchsummary                     1.5.1
```

### Reproduces the problem - code sample

```
!cd mmpose && python ../mmdeploy/tools/deploy.py \
../mmdeploy/configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py \
configs/body_2d_keypoint/rtmpose/coco/rtmpose-m_8xb256-420e_coco-256x192_rail.py \
../drive/MyDrive/mmpose/rail_qrcode/best_rail_publish.pth demo.jpg \
--work-dir ../drive/MyDrive/mmpose/rail_qrcode/rtmpose/pose --device cpu --dump-info
```

### Reproduces the problem - command or script

```
!cd mmpose && python ../mmdeploy/tools/deploy.py \
../mmdeploy/configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py \
configs/body_2d_keypoint/rtmpose/coco/rtmpose-m_8xb256-420e_coco-256x192_rail.py \
../drive/MyDrive/mmpose/rail_qrcode/best_rail_publish.pth demo.jpg \
--work-dir ../drive/MyDrive/mmpose/rail_qrcode/rtmpose/pose --device cpu --dump-info
```

### Reproduces the problem - error message

```
10/25 02:21:05 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
10/25 02:21:05 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
10/25 02:21:10 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
10/25 02:21:15 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
10/25 02:21:15 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: ../drive/MyDrive/mmpose/rail_qrcode/best_rail_publish.pth
10/25 02:21:17 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
10/25 02:21:17 - mmengine - INFO - Export PyTorch model to ONNX: ../drive/MyDrive/mmpose/rail_qrcode/rtmpose/pose/end2end.onnx.
10/25 02:21:17 - mmengine - WARNING - Can not find models.yolox_pose_head.YOLOXPoseHead.predict, function rewrite will not be applied
10/25 02:21:17 - mmengine - WARNING - Can not find models.yolox_pose_head.YOLOXPoseHead.predict_by_feat, function rewrite will not be applied
10/25 02:21:19 - mmengine - INFO - Execute onnx optimize passes.
10/25 02:21:19 - mmengine - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/experimental/onnx_optimizer.md
10/25 02:21:20 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
10/25 02:21:21 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
10/25 02:21:21 - mmengine - INFO - Finish pipeline mmdeploy.apis.utils.utils.to_backend
10/25 02:21:21 - mmengine - INFO - visualize onnxruntime model start.
2023-10-25:02:21:24 - numexpr.utils - INFO - NumExpr defaulting to 2 threads.
10/25 02:21:28 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
10/25 02:21:28 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
10/25 02:21:28 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "backend_segmentors" registry tree. As a workaround, the current "backend_segmentors" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
10/25 02:21:28 - mmengine - INFO - Successfully loaded onnxruntime custom ops from /usr/local/lib/python3.10/dist-packages/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so
2023-10-25:02:21:28 - root - ERROR - 'InstanceData' object has no attribute 'bbox_centers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mmdeploy/utils/utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmdeploy/apis/visualize.py", line 72, in visualize_model
    result = model.test_step(model_inputs)[0]
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmdeploy/codebase/mmpose/deploy/pose_detection_model.py", line 114, in forward
    results = self.pack_result(preds, data_samples)
  File "/usr/local/lib/python3.10/dist-packages/mmdeploy/codebase/mmpose/deploy/pose_detection_model.py", line 148, in pack_result
    bbox_centers = gt_instances.bbox_centers
AttributeError: 'InstanceData' object has no attribute 'bbox_centers'
10/25 02:21:30 - mmengine - ERROR - /content/mmpose/../mmdeploy/tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.
```

**Comment by Ben-Louis** [comment]
这个问题是新版本的 mmpose 和之前版本的 mmdeploy 的不兼容导致的，我们会尽快修复。目前可以通过安装 mmdeploy 的 main 分支 `pip install git+https://github.com/open-mmlab/mmdeploy.git` 解决

**Comment by vicnoah** [comment]
> 这个问题是新版本的 mmpose 和之前版本的 mmdeploy 的不兼容导致的，我们会尽快修复。目前可以通过安装 mmdeploy 的 main 分支 `pip install git+https://github.com/open-mmlab/mmdeploy.git` 解决

好的，谢谢

**Comment by vicnoah** [comment]
> 这个问题是新版本的 mmpose 和之前版本的 mmdeploy 的不兼容导致的，我们会尽快修复。目前可以通过安装 mmdeploy 的 main 分支 `pip install git+https://github.com/open-mmlab/mmdeploy.git` 解决

好的，谢谢

**Comment by shekmun** [comment]
参考[这个官方](https://mmdeploy.readthedocs.io/zh_CN/latest/04-supported-codebases/mmpose.html)例子：
1、mim download mmpose --config td-hm_hrnet-w32_8xb64-210e_coco-256x192 --dest .
2、python tools/deploy.py configs/mmpose/pose-detection_onnxruntime_static.py td-hm_hrnet-w32_8xb64-210e_coco-256x192.py td-hm_hrnet-w32_8xb64-210e_coco-256x192-81c58e40_20220909.pth demo/resources/human-pose.jpg --work-dir mmdeploy_models/mmpose/ort --device cpu --show

一开始也是报一样的错误，把mmdeploy更新成git版本之后，执行都成功了，但是只生成了3个文件：end2end.onnx、output_onnxruntime.jpg、output_pytorch.jpg
为什么没有模型对应的几个json文件（deploy.json、detail.json、pipeline.json），模型无法通过C++加载 @Ben-Louis

**Comment by volkov-maxim** [comment]
Hi @Ben-Louis !
I have same problem: `AttributeError: 'InstanceData' object has no attribute 'bbox_centers'`.
Installing mmdeploy with command `pip install git+https://github.com/open-mmlab/mmdeploy.git` does not help.

My env:
```
mmcv                     2.1.0
mmdeploy                 1.3.0
mmdeploy-runtime-gpu     1.3.0
mmdet                    3.2.0
mmengine                 0.9.1
mmpose                   1.2.0
```

Have you another idea how to solve this problem?

**Comment by volkov-maxim** [comment]
Find workaround: downgrade `mmpose` version from `1.2.0` to `1.1.0`

`mim install --upgrade mmpose==1.1.0`

My env now:
```
mmcv                     2.0.1
mmdeploy                 1.3.0
mmdeploy-runtime-gpu     1.3.0
mmdet                    3.1.0
mmengine                 0.9.1
mmpose                   1.1.0
```
