### ISSUE TITLE
Can't load td-hm_hrnet-w32_8xb64-210e_ubody-256x192 by name

### ISSUE THREAD

**Issue by SpecLad** [open-mmlab/mmpose#2781]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

```
OrderedDict([('sys.platform', 'linux'), ('Python', '3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'), ('PyTorch', '2.0.0+cpu'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.1+cpu'), ('OpenCV', '4.8.1'), ('MMEngine', '0.9.0'), ('MMPose', '1.2.0+')])

mmcv                   2.0.1
mmdet                  3.2.0
mmengine               0.9.0
mmpose                 1.2.0
```

### Reproduces the problem - code sample

```python
from mmpose.apis import MMPoseInferencer

inferencer = MMPoseInferencer(
    pose2d='td-hm_hrnet-w32_8xb64-210e_ubody-256x192',
)
```

### Reproduces the problem - command or script

```shell
python test.py
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/tmp/test.py", line 3, in <module>
    inferencer = MMPoseInferencer(
  File "/tmp/venv/lib/python3.10/site-packages/mmpose/apis/inferencers/mmpose_inferencer.py", line 93, in __init__
    self.inferencer = Pose2DInferencer(pose2d, pose2d_weights, device,
  File "/tmp/venv/lib/python3.10/site-packages/mmpose/apis/inferencers/pose2d_inferencer.py", line 85, in __init__
    super().__init__(
  File "/tmp/venv/lib/python3.10/site-packages/mmengine/infer/infer.py", line 160, in __init__
    cfg, _weights = self._load_model_from_metafile(model)
  File "/tmp/venv/lib/python3.10/site-packages/mmengine/infer/infer.py", line 393, in _load_model_from_metafile
    raise ValueError(f'Cannot find model: {model} in {self.scope}')
ValueError: Cannot find model: td-hm_hrnet-w32_8xb64-210e_ubody-256x192 in mmpose
```

### Additional information

I expected [this](https://mmpose.readthedocs.io/en/latest/model_zoo/wholebody_2d_keypoint.html#ubody2d-dataset) model to be loaded.

I think the problem is that the corresponding config is missing from [`model-index.yml`](https://github.com/open-mmlab/mmpose/blob/6d10b2ec81da7e252016b3154c7fdb46c403ecd8/model-index.yml).

**Comment by Ben-Louis** [comment]
Apologize for the inconvenience caused. If you intend to use this model name to initialize an inferencer, it's essential to add `configs/wholebody_2d_keypoint/topdown_heatmap/ubody2d/hrnet_coco-wholebody.yml` to the `model-index.yml` file. Unfortunately, this is missing in the latest version. Would you like to raise a PR to add this to the file?

Alternatively, you can use the path of config and checkpoint to initialize the inferencer if you do not want to add this item in `model-index.yml`.
