### ISSUE TITLE
用RTM pose的wholebody模型出错

### ISSUE THREAD

**Issue by LZhen624** [open-mmlab/mmpose#2798]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

MMCV版本 2.0.1
mmpose版本 1.0.0
mmdetection版本 3.0.0

### Reproduces the problem - code sample

!python demo/topdown_demo_with_mmdet.py \
        demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
        https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
        projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmpose-m_8xb64-270e_coco-wholebody-256x192.py \
        https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth \
        --input data/test/mother_wx.mp4 \
        --output-root outputs/B1_RTM_2 \
        --save-predictions \
        --device cuda:0 \
        --bbox-thr 0.5 \
        --kpt-thr 0.5 \
        --nms-thr 0.3 \
        --radius 8 \
        --thickness 4 \
        --draw-bbox \
        --draw-heatmap \
        --show-kpt-idx

### Reproduces the problem - command or script

!python demo/topdown_demo_with_mmdet.py \
        demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
        https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
        projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmpose-m_8xb64-270e_coco-wholebody-256x192.py \
        https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth \
        --input data/test/mother_wx.mp4 \
        --output-root outputs/B1_RTM_2 \
        --save-predictions \
        --device cuda:0 \
        --bbox-thr 0.5 \
        --kpt-thr 0.5 \
        --nms-thr 0.3 \
        --radius 8 \
        --thickness 4 \
        --draw-bbox \
        --draw-heatmap \
        --show-kpt-idx

### Reproduces the problem - error message

Loads checkpoint by http backend from path: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
The model and loaded state dict do not match exactly

size mismatch for head.final_layer.weight: copying a param with shape torch.Size([17, 768, 7, 7]) from checkpoint, the shape in current model is torch.Size([133, 768, 7, 7]).
size mismatch for head.final_layer.bias: copying a param with shape torch.Size([17]) from checkpoint, the shape in current model is torch.Size([133]).
/environment/miniconda3/lib/python3.10/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Traceback (most recent call last):
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/demo/topdown_demo_with_mmdet.py", line 292, in <module>
    main()
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/demo/topdown_demo_with_mmdet.py", line 237, in main
    pred_instances = process_one_image(args, frame, detector,
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/demo/topdown_demo_with_mmdet.py", line 45, in process_one_image
    pose_results = inference_topdown(pose_estimator, img, bboxes)
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/mmpose/apis/inference.py", line 191, in inference_topdown
    results = model.test_step(batch)
  File "/environment/miniconda3/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/environment/miniconda3/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/mmpose/models/pose_estimators/base.py", line 140, in forward
    return self.predict(inputs, data_samples)
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/mmpose/models/pose_estimators/topdown.py", line 109, in predict
    preds = self.head.predict(feats, data_samples, test_cfg=self.test_cfg)
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/mmpose/models/heads/coord_cls_heads/rtmcc_head.py", line 202, in predict
    _batch_pred_x_flip, _batch_pred_y_flip = flip_vectors(
  File "/home/featurize/MMPose_Tutorials-main/2023/0524/mmpose/mmpose/models/utils/tta.py", line 83, in flip_vectors
    assert len(flip_indices) == x_labels.shape[1] and len(
AssertionError

### Additional information

我用上述的命令行去执行wholebody，就是想推理出全身的26个关键点，但是出现以上错误，希望能够得到解决

**Comment by Ben-Louis** [comment]
请使用匹配的 config 和 checkpoint

**Comment by LZhen624** [comment]
> 请使用匹配的 config 和 checkpoint

可是哪一个才是正确的呢，我试了好几天都出错。我想用那个取人体的26个关键点的模型

**Comment by Ben-Louis** [comment]
26点模型可以看下https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/rtmpose/body8/rtmpose_body8-halpe26.md

**Comment by LZhen624** [comment]
> 26点模型可以看下https://github.com/open-mmlab/mmpose/blob/main/configs/body_2d_keypoint/rtmpose/body8/rtmpose_body8-halpe26.md

# RTMPose
!python demo/topdown_demo_with_mmdet.py \
        demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
        https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
        configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb512-700e_body8-halpe26-256x192.py \
        https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth \
        --input data/2.mp4 \
        --output-root outputs \
        --device cuda:0 \
        --bbox-thr 0.5 \
        --kpt-thr 0.5 \
        --nms-thr 0.3 \
        --radius 5 \
        --thickness 2 \
        --draw-bbox \
        --draw-heatmap \
        --show-kpt-idx
      我这个代码有错误吗？一直运行不通

**Comment by LZhen624** [comment]
一直显示：
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
The model and loaded state dict do not match exactly

size mismatch for head.final_layer.weight: copying a param with shape torch.Size([17, 768, 7, 7]) from checkpoint, the shape in current model is torch.Size([26, 768, 7, 7]).
size mismatch for head.final_layer.bias: copying a param with shape torch.Size([17]) from checkpoint, the shape in current model is torch.Size([26]).
Traceback (most recent call last):
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/demo/topdown_demo_with_mmdet.py", line 302, in <module>
    main()
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/demo/topdown_demo_with_mmdet.py", line 239, in main
    pred_instances = process_one_image(args, frame, detector,
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/demo/topdown_demo_with_mmdet.py", line 47, in process_one_image
    pose_results = inference_topdown(pose_estimator, img, bboxes)
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/mmpose/apis/inference.py", line 196, in inference_topdown
    results = model.test_step(batch)
  File "/environment/miniconda3/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/environment/miniconda3/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/mmpose/models/pose_estimators/base.py", line 151, in forward
    return self.predict(inputs, data_samples)
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/mmpose/models/pose_estimators/topdown.py", line 109, in predict
    preds = self.head.predict(feats, data_samples, test_cfg=self.test_cfg)
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/mmpose/models/heads/coord_cls_heads/rtmcc_head.py", line 202, in predict
    _batch_pred_x_flip, _batch_pred_y_flip = flip_vectors(
  File "/home/featurize/MMPose_Tutorials-main/2022/mmpose/mmpose/models/utils/tta.py", line 83, in flip_vectors
    assert len(flip_indices) == x_labels.shape[1] and len(
AssertionError

**Comment by LZhen624** [comment]
top_down_img_demo_with_mmdet.py是不是没办法将预测结果显示在黑色背景下，是不是没法    --black-background
