### ISSUE TITLE
[Bug] human3d pose3d inference does not work on main branch

### ISSUE THREAD

**Issue by Jendker** [open-mmlab/mmpose#2816]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

```
OrderedDict([('sys.platform', 'darwin'), ('Python', '3.10.10 (main, Mar 19 2023, 21:40:33) [Clang 14.0.0 (clang-1400.0.29.202)]'), ('CUDA available', False), ('numpy_random_seed', 2147483648), ('GCC', 'Apple clang version 15.0.0 (clang-1500.0.40.1)'), ('PyTorch', '2.1.1'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 4.2\n  - C++ Version: 201703\n  - clang 13.1.6\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: NO AVX\n  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_13.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++, CXX_FLAGS= -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DUSE_COREML_DELEGATE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=braced-scalar-init -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wvla-extension -Wnewline-eof -Winconsistent-missing-override -Winconsistent-missing-destructor-override -Wno-range-loop-analysis -Wno-pass-failed -Wsuggest-override -Wno-error=pedantic -Wno-error=old-style-cast -Wno-error=inconsistent-missing-override -Wno-error=inconsistent-missing-destructor-override -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-missing-braces -Wunused-lambda-capture -Qunused-arguments -fcolor-diagnostics -faligned-new -Wno-unused-but-set-variable -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -Wno-unused-private-field -Wno-missing-braces, LAPACK_INFO=accelerate, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.1, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, USE_ROCM=OFF, \n'), ('TorchVision', '0.16.1'), ('OpenCV', '4.8.1'), ('MMEngine', '0.9.1'), ('MMPose', '1.2.0+6d10b2e')])
```
```
mmcv                   2.1.0
mmdet                  3.2.0
mmengine               0.9.1
mmpose                 1.2.0        /Users/jedrzej/repos/mmpose
```

### Reproduces the problem - code sample

I run the normal inferencer on current `main` branch as described below.

### Reproduces the problem - command or script

I follow https://github.com/open-mmlab/mmpose/blob/6d10b2ec81da7e252016b3154c7fdb46c403ecd8/demo/docs/en/3d_human_pose_demo.md?plain=1#L81-L82

I call: 
```
python demo/inferencer_demo.py tests/data/coco/000000000785.jpg --pose3d human3d --vis-out-dir vis_results/human3d --device cpu
```

### Reproduces the problem - error message

```
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/body_3d_keypoint/pose_lift/h36m/motionbert_ft_h36m-d80af323_20230531.pth
11/24 00:08:22 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_m_8xb32-300e_coco/rtmdet_m_8xb32-300e_coco_20220719_112220-229f527c.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

11/24 00:08:23 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
/Users/jedrzej/repos/mmpose/venv/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release,
it will be required to pass the indexing argument. (Triggered internally at
/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/Users/jedrzej/repos/mmpose/demo/inferencer_demo.py", line 193, in <module>
    main()
  File "/Users/jedrzej/repos/mmpose/demo/inferencer_demo.py", line 188, in main
    for _ in inferencer(**call_args):
  File "/Users/jedrzej/repos/mmpose/mmpose/apis/inferencers/mmpose_inferencer.py", line 208, in __call__
    visualization = self.visualize(ori_inputs, preds,
  File "/Users/jedrzej/repos/mmpose/mmpose/apis/inferencers/mmpose_inferencer.py", line 247, in visualize
    return self.inferencer.visualize(
  File "/Users/jedrzej/repos/mmpose/mmpose/apis/inferencers/pose3d_inferencer.py", line 424, in visualize
    visualization = self.visualizer.add_datasample(
  File "/Users/jedrzej/repos/mmpose/venv/lib/python3.10/site-packages/mmengine/dist/utils.py", line 419, in wrapper
    return func(*args, **kwargs)
  File "/Users/jedrzej/repos/mmpose/mmpose/visualization/local_visualizer_3d.py", line 615, in add_datasample
    drawn_img = np.concatenate((det_img_data, pred_img_data), axis=1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 3 and the array at index 1 has size 12
```

### Additional information

I expect the results to be produced as described in 3d human pose README.

**Comment by Jendker** [comment]
I run into similar issues with the pose lifter demos. 

Command (comes from https://github.com/open-mmlab/mmpose/blob/main/demo/docs/en/3d_human_pose_demo.md?plain=1#L49-L58:
```
python demo/body3d_pose_lifter_demo.py  \
demo/mmdetection_cfg/rtmdet_m_640-8xb32_coco-person.py \
https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth \
configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb256-420e_body8-256x192.py \
https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth \
configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth  \
--input https://user-images.githubusercontent.com/87690686/164970135-b14e424c-765a-4180-9bc8-fa8d6abc5510.mp4 \
--output-root  vis_results \
--save-predictions --device cpu
```
Output:
```
/Users/jedrzej/repos/mmpose/venv/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "demo/body3d_pose_lifter_demo.py", line 553, in <module>
    main()
  File "demo/body3d_pose_lifter_demo.py", line 488, in main
    next_id) = process_one_image(
  File "demo/body3d_pose_lifter_demo.py", line 346, in process_one_image
    visualizer.add_datasample(
  File "/Users/jedrzej/repos/mmpose/venv/lib/python3.8/site-packages/mmengine/dist/utils.py", line 419, in wrapper
    return func(*args, **kwargs)
  File "/Users/jedrzej/repos/mmpose/mmpose/visualization/local_visualizer_3d.py", line 615, in add_datasample
    drawn_img = np.concatenate((det_img_data, pred_img_data), axis=1)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 3 and the array at index 1 has size 12
```
