### ISSUE TITLE
[Bug] module 'mmpose' has no attribute 'apis' 

### ISSUE THREAD

**Issue by hhhuaang** [open-mmlab/mmpose#2818]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

i install mmpose like this:
```shell
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.1"
mim install "mmdet>=3.1.0"
mim install "mmpose==1.2.0"
```

my test code is like this:
```python
import mmpose
print(mmpose.__all__)
print(mmpose.apis.__all__)
```
it print:
```
['__version__', 'short_version']
Traceback (most recent call last):
  File "D:\python\gpu\test\test_mmpose.py", line 3, in <module>
    print(mmpose.apis.__all__)
AttributeError: module 'mmpose' has no attribute 'apis'
```

### Reproduces the problem - code sample

```python
import mmpose
print(mmpose.__all__)
print(mmpose.apis.__all__)
```

### Reproduces the problem - command or script

```shell
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.1"
mim install "mmdet>=3.1.0"
mim install "mmpose==1.2.0"
```

### Reproduces the problem - error message

```
['__version__', 'short_version']
Traceback (most recent call last):
  File "D:\python\gpu\test\test_mmpose.py", line 3, in <module>
    print(mmpose.apis.__all__)
AttributeError: module 'mmpose' has no attribute 'apis'
```

**Comment by Ben-Louis** [comment]
I guess the mim you are using does not share the environment with the python you are using. It can be challenging to resolve environment issues on Windows. Perhaps you could try using 'python -m mim install xxx' to install the required packages.

**Comment by Ben-Louis** [comment]
> Hey @Ben-Louis I am facing a similar issue on google collab, any suggestions??

I suggest opening a new issue and completing the template to provide necessary information

**Comment by hhhuaang** [comment]
我是应为显卡的电源被拔掉了导致的这个问题，我觉得这不是代码的bug，而是我的愚蠢导致这个问题，可以关闭这个问题了
