### ISSUE TITLE
Unable to install xtcocotools and related failures

### ISSUE THREAD

**Issue by SMHendryx** [open-mmlab/mmpose#282]
Hi, I followed the docs and tried installing from source but get an error on `xtcocotools`

This is reproducible following your installation procedure on MacOS. https://mmpose.readthedocs.io/en/latest/install.html

```
ERROR: Could not find a version that satisfies the requirement xtcocotools>=1.6 (from -r requirements/runtime.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for xtcocotools>=1.6 (from -r requirements/runtime.txt (line 10))
(open-mmlab) ~/repositories/mmpose @ MacBook-Pro-2(sean): python setup.py develop
running develop
running egg_info
creating mmpose.egg-info
writing mmpose.egg-info/PKG-INFO
writing dependency_links to mmpose.egg-info/dependency_links.txt
writing requirements to mmpose.egg-info/requires.txt
writing top-level names to mmpose.egg-info/top_level.txt
writing manifest file 'mmpose.egg-info/SOURCES.txt'
reading manifest file 'mmpose.egg-info/SOURCES.txt'
writing manifest file 'mmpose.egg-info/SOURCES.txt'
running build_ext
Creating /Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmpose.egg-link (link to .)
Adding mmpose 0.8.0 to easy-install.pth file

Installed /Users/sean/repositories/mmpose
Processing dependencies for mmpose==0.8.0
Searching for xtcocotools>=1.6
Reading https://pypi.org/simple/xtcocotools/
No local packages or working download links found for xtcocotools>=1.6
error: Could not find suitable distribution for Requirement.parse('xtcocotools>=1.6')
```

**Comment by innerlee** [comment]
Could you try to install xtcocotools manually? ref https://pypi.org/project/xtcocotools/

```bash
pip install xtcocotools
```

**Comment by innerlee** [comment]
Okay i see, it haven't built for Mac yet. For now, you can clone the repo and build from source

**Comment by innerlee** [comment]
Instructions:

```bash
git clone https://github.com/jin-s13/xtcocoapi
cd xtcocoapi
make install
```

**Comment by SMHendryx** [comment]
Thanks for the update. It looks like there is a bug in xtcocotools:
```
git clone https://github.com/jin-s13/xtcocoapi
cd xtcocoapi
make install

# install xtcocotools to the Python site-packages
python setup.py build_ext install
running build_ext
building 'xtcocotools._mask' extension
creating build
creating build/temp.macosx-10.9-x86_64-3.7
creating build/temp.macosx-10.9-x86_64-3.7/common
creating build/temp.macosx-10.9-x86_64-3.7/xtcocotools
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sean/Applications/miniconda3/envs/open-mmlab/include -arch x86_64 -I/Users/sean/Applications/miniconda3/envs/open-mmlab/include -arch x86_64 -I/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include -I./common -I/Users/sean/Applications/miniconda3/envs/open-mmlab/include/python3.7m -c ./common/maskApi.c -o build/temp.macosx-10.9-x86_64-3.7/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sean/Applications/miniconda3/envs/open-mmlab/include -arch x86_64 -I/Users/sean/Applications/miniconda3/envs/open-mmlab/include -arch x86_64 -I/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include -I./common -I/Users/sean/Applications/miniconda3/envs/open-mmlab/include/python3.7m -c xtcocotools/_mask.c -o build/temp.macosx-10.9-x86_64-3.7/xtcocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
clang: error: no such file or directory: 'xtcocotools/_mask.c'
clang: error: no input files
error: command 'gcc' failed with exit status 1
make: *** [install] Error 1
```

**Comment by innerlee** [comment]
do you have cython installed?

**Comment by SMHendryx** [comment]
Thanks I got a bit further by installing Cython and torch vision. Those should be added to the `requirements`. ( I tried to create a PR, but couldn't push a branch due to permissions).

At any rate, now I have another failure:
```
python demo/top_down_img_demo_with_mmdet.py     demo/mmdetection_cfg/faster_rcnn_r50_fpn_1x_coco.py     http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth     configs/top_down/hrnet/coco/hrnet_w48_coco_256x192.py     https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth     --img-root tests/data/coco/     --out-img-root vis_results --device cpu
Traceback (most recent call last):
  File "demo/top_down_img_demo_with_mmdet.py", line 4, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/Users/sean/Applications/miniconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

**Comment by innerlee** [comment]
Try this to see if it works
```
pip uninstall mmcv
pip install mmcv-full
```

Permissions are not needed if you create pr from fork https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by SMHendryx** [comment]
Thanks, that worked @innerlee . Here is a PR from my fork with update requirements. https://github.com/open-mmlab/mmpose/pull/285

**Comment by bedbad** [comment]
Suggested fix creates the following issue
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <=2.1.0.

**Comment by ll8657** [comment]
For 'ModuleNotFoundError: No module named 'mmcv._ext', you can recompile it using the source code. 
cd mmcv
pip install -r requirements/build.txt
pip install ninja
MMCV_WITH_OPS=1 python setup.py develop
