### ISSUE TITLE
crash during training

### ISSUE THREAD

**Issue by imistyrain** [open-mmlab/mmpose#284]

**Comment by imistyrain** [comment]
system: ubuntu 16.04, with GTX1060 8G and 16G memroy, with config: sample_per_gpu=8
train cmd is :
```
./tools/dist_train.sh configs/top_down/resnet/coco/res50_coco_256x192.py 1
```
```
2020-11-18 07:12:31,206 - mmpose - INFO - Epoch [10][18500/18726]	lr: 5.000e-04, eta: 7 days, 21:03:58, time: 0.180, data_time: 0.000, memory: 1418, mse_loss: 0.0009, acc_pose: 0.6577, loss: 0.0009
2020-11-18 07:12:40,201 - mmpose - INFO - Epoch [10][18550/18726]	lr: 5.000e-04, eta: 7 days, 21:03:47, time: 0.180, data_time: 0.000, memory: 1418, mse_loss: 0.0009, acc_pose: 0.6655, loss: 0.0009
2020-11-18 07:12:49,199 - mmpose - INFO - Epoch [10][18600/18726]	lr: 5.000e-04, eta: 7 days, 21:03:36, time: 0.180, data_time: 0.000, memory: 1418, mse_loss: 0.0010, acc_pose: 0.6384, loss: 0.0010
2020-11-18 07:12:58,240 - mmpose - INFO - Epoch [10][18650/18726]	lr: 5.000e-04, eta: 7 days, 21:03:26, time: 0.181, data_time: 0.000, memory: 1418, mse_loss: 0.0010, acc_pose: 0.6338, loss: 0.0010
2020-11-18 07:13:07,248 - mmpose - INFO - Epoch [10][18700/18726]	lr: 5.000e-04, eta: 7 days, 21:03:16, time: 0.180, data_time: 0.000, memory: 1418, mse_loss: 0.0010, acc_pose: 0.6452, loss: 0.0010
2020-11-18 07:13:20,215 - mmpose - INFO - Saving checkpoint at 10 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 104125/104125, 48.5 task/s, elapsed: 2147s, ETA:     0sTraceback (most recent call last):
  File "anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', './tools/train.py', '--local_rank=0', 'configs/top_down/resnet/coco/res50_coco_256x192.py', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>.
```

**Comment by innerlee** [comment]
This is because of out of memory on validation.

Are you on the master branch of mmpose?

**Comment by innerlee** [comment]
@jin-s13 we may support assigning different configs for train and val, like here https://github.com/open-mmlab/mmaction2/blob/master/configs/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature.py#L84

**Comment by imistyrain** [comment]
ok, got it, thanks
