### ISSUE TITLE
  The connection between mmpose and mmpretrain.

### ISSUE THREAD

**Issue by mmis00112** [open-mmlab/mmpose#2845]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Thank you for all your great projects.

I apologize if this is a simple lack of effort on my part.

I am trying to re-categorize the BONE estimated by video estimation with mmpose, frame by frame, with mmpretrain.
I am currently experiencing some problems.
Most of them are due to build_functions.py.

ResizeEdge is not in mmdet::transform registry. Please verify if the value of `ResizeEdge` is correct or registered as expected. For details, refer to https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module.'

Perhaps it is because I have not set it up properly, but I have no idea.

Is it possible to use both mmpose and mmpretrain.
Here is the output of the command

 python -c "from mmpose.utils import collect_env; print(collect_env())"
OrderedDict([('sys.platform', 'win32'), ('Python', '3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'NVIDIA GeForce RTX 3070'), ('CUDA_HOME', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8'), ('NVCC', 'Cuda compilation tools, release 11.8, V11.8.89'), ('MSVC', 'Microsoft(R) C/C++ Optimizing Compiler Version 19.29.30147 for x64'), ('GCC', 'n/a'), ('PyTorch', '2.1.0+cu118'), ('PyTorch compiling details', 'PyTorch built with:\n  - C++ Version: 199711\n  - MSVC 192930151\n  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)\n  - OpenMP 2019\n  - LAPACK is enabled (usually provided by MKL)\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.7\n  - Magma 2.5.4\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /utf-8 /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.16.0+cu118'), ('OpenCV', '4.8.1'), ('MMEngine', '0.9.1'), ('MMPose', '1.2.0+6d10b2e')])

### Codes used.
_mmpose_inferencer.py_　
Changes: 
・Save images for study
・import mmpretrain
・Only key points are returned for inference.

# Copyright (c) OpenMMLab. All rights reserved.
import warnings
from typing import Dict, List, Optional, Sequence, Union

import numpy as np
import torch
from mmengine.config import Config, ConfigDict
from mmengine.infer.infer import ModelType
from mmengine.structures import InstanceData

from .base_mmpose_inferencer import BaseMMPoseInferencer
from .hand3d_inferencer import Hand3DInferencer
from .pose2d_inferencer import Pose2DInferencer
from .pose3d_inferencer import Pose3DInferencer

from mmpretrain import ImageClassificationInferencer #mmpretrain

InstanceList = List[InstanceData]
InputType = Union[str, np.ndarray]
InputsType = Union[InputType, Sequence[InputType]]
PredType = Union[InstanceData, InstanceList]
ImgType = Union[np.ndarray, Sequence[np.ndarray]]
ConfigType = Union[Config, ConfigDict]
ResType = Union[Dict, List[Dict], InstanceData, List[InstanceData]]

class MMPoseInferencer(BaseMMPoseInferencer):
    """MMPose Inferencer. It's a unified inferencer interface for pose
    estimation task, currently including: Pose2D. and it can be used to perform
    2D keypoint detection.

    Args:
        pose2d (str, optional): Pretrained 2D pose estimation algorithm.
            It's the path to the config file or the model name defined in
            metafile. For example, it could be:

            - model alias, e.g. ``'body'``,
            - config name, e.g. ``'simcc_res50_8xb64-210e_coco-256x192'``,
            - config path

            Defaults to ``None``.
        pose2d_weights (str, optional): Path to the custom checkpoint file of
            the selected pose2d model. If it is not specified and "pose2d" is
            a model name of metafile, the weights will be loaded from
            metafile. Defaults to None.
        device (str, optional): Device to run inference. If None, the
            available device will be automatically used. Defaults to None.
        scope (str, optional): The scope of the model. Defaults to "mmpose".
        det_model(str, optional): Config path or alias of detection model.
            Defaults to None.
        det_weights(str, optional): Path to the checkpoints of detection
            model. Defaults to None.
        det_cat_ids(int or list[int], optional): Category id for
            detection model. Defaults to None.
        output_heatmaps (bool, optional): Flag to visualize predicted
            heatmaps. If set to None, the default setting from the model
            config will be used. Default is None.
    """

    preprocess_kwargs: set = {
        'bbox_thr', 'nms_thr', 'bboxes', 'use_oks_tracking', 'tracking_thr',
        'disable_norm_pose_2d'
    }
    forward_kwargs: set = {'disable_rebase_keypoint'}
    visualize_kwargs: set = {
        'return_vis', 'show', 'wait_time', 'draw_bbox', 'radius', 'thickness',
        'kpt_thr', 'vis_out_dir', 'skeleton_style', 'draw_heatmap',
        'black_background', 'num_instances'
    }
    postprocess_kwargs: set = {'pred_out_dir', 'return_datasample'}

    def __init__(self,
                 pose2d: Optional[str] = None,
                 pose2d_weights: Optional[str] = None,
                 pose3d: Optional[str] = None,
                 pose3d_weights: Optional[str] = None,
                 device: Optional[str] = None,
                 scope: str = 'mmpose',
                 det_model: Optional[Union[ModelType, str]] = None,
                 det_weights: Optional[str] = None,
                 det_cat_ids: Optional[Union[int, List]] = None) -> None:

        self.visualizer = None
        if pose3d is not None:
            if 'hand3d' in pose3d:
                self.inferencer = Hand3DInferencer(pose3d, pose3d_weights,
                                                   device, scope, det_model,
                                                   det_weights, det_cat_ids)
            else:
                self.inferencer = Pose3DInferencer(pose3d, pose3d_weights,
                                                   pose2d, pose2d_weights,
                                                   device, scope, det_model,
                                                   det_weights, det_cat_ids)
        elif pose2d is not None:
            self.inferencer = Pose2DInferencer(pose2d, pose2d_weights, device,
                                               scope, det_model, det_weights,
                                               det_cat_ids)
        else:
            raise ValueError('Either 2d or 3d pose estimation algorithm '
                             'should be provided.')

    def preprocess(self, inputs: InputsType, batch_size: int = 1, **kwargs):
        """Process the inputs into a model-feedable format.

        Args:
            inputs (InputsType): Inputs given by user.
            batch_size (int): batch size. Defaults to 1.

        Yields:
            Any: Data processed by the ``pipeline`` and ``collate_fn``.
            List[str or np.ndarray]: List of original inputs in the batch
        """

        for i, input in enumerate(inputs):
            data_batch = {}
            data_infos = self.inferencer.preprocess_single(
                input, index=i, **kwargs)
            data_batch = self.inferencer.collate_fn(data_infos)
            # only supports inference with batch size 1
            yield data_batch, [input]

    @torch.no_grad()
    def forward(self, inputs: InputType, **forward_kwargs) -> PredType:
        """Forward the inputs to the model.

        Args:
            inputs (InputsType): The inputs to be forwarded.

        Returns:
            Dict: The prediction results. Possibly with keys "pose2d".
        """
        return self.inferencer.forward(inputs, **forward_kwargs)

    def __call__(
        self,
        inputs: InputsType,
        return_datasamples: bool = False,
        batch_size: int = 1,
        out_dir: Optional[str] = None,
        **kwargs,
    ) -> dict:
        """Call the inferencer.

        Args:
            inputs (InputsType): Inputs for the inferencer.
            return_datasamples (bool): Whether to return results as
                :obj:`BaseDataElement`. Defaults to False.
            batch_size (int): Batch size. Defaults to 1.
            out_dir (str, optional): directory to save visualization
                results and predictions. Will be overoden if vis_out_dir or
                pred_out_dir are given. Defaults to None
            **kwargs: Key words arguments passed to :meth:`preprocess`,
                :meth:`forward`, :meth:`visualize` and :meth:`postprocess`.
                Each key in kwargs should be in the corresponding set of
                ``preprocess_kwargs``, ``forward_kwargs``,
                ``visualize_kwargs`` and ``postprocess_kwargs``.

        Returns:
            dict: Inference and visualization results.
        """
        if out_dir is not None:
            if 'vis_out_dir' not in kwargs:
                kwargs['vis_out_dir'] = f'{out_dir}/visualizations'
            if 'pred_out_dir' not in kwargs:
                kwargs['pred_out_dir'] = f'{out_dir}/predictions'

        kwargs = {
            key: value
            for key, value in kwargs.items()
            if key in set.union(self.inferencer.preprocess_kwargs,
                                self.inferencer.forward_kwargs,
                                self.inferencer.visualize_kwargs,
                                self.inferencer.postprocess_kwargs)
        }
        (
            preprocess_kwargs,
            forward_kwargs,
            visualize_kwargs,
            postprocess_kwargs,
        ) = self._dispatch_kwargs(**kwargs)

        self.inferencer.update_model_visualizer_settings(**kwargs)

        # preprocessing
        if isinstance(inputs, str) and inputs.startswith('webcam'):
            inputs = self.inferencer._get_webcam_inputs(inputs)
            batch_size = 1
            if not visualize_kwargs.get('show', False):
                warnings.warn('The display mode is closed when using webcam '
                              'input. It will be turned on automatically.')
            visualize_kwargs['show'] = True
        else:
            inputs = self.inferencer._inputs_to_list(inputs)
        self._video_input = self.inferencer._video_input
        if self._video_input:
            self.video_info = self.inferencer.video_info

        inputs = self.preprocess(
            inputs, batch_size=batch_size, **preprocess_kwargs)

        # forward
        if 'bbox_thr' in self.inferencer.forward_kwargs:
            forward_kwargs['bbox_thr'] = preprocess_kwargs.get('bbox_thr', -1)

        preds = []

        for proc_inputs, ori_inputs in inputs:
            preds = self.forward(proc_inputs, **forward_kwargs)

            visualization = self.visualize(ori_inputs, preds,
                                           **visualize_kwargs)
            results = self.postprocess(
                preds,
                visualization,
                return_datasamples=return_datasamples,
                **postprocess_kwargs)
#            yield results

	    
		#make black image
		#For creating learning images
 
            img_black = np.zeros((480, 640, 3), np.uint8)

            result = results['predictions'][0][0]['keypoints']

            #背景黒の画像に推論した座標を描画する

            for i in range(17):
                cv2.circle(img_black,(int(result[i][0]),int(result[i][1])), 5, (255,0,0), -1)

            #line

           
            cv2.line(img_black,(int(result[0][0]),int(result[0][1])),(int(result[2][0]),int(result[2][1])),(0,255,0),3)
            cv2.line(img_black,(int(result[0][0]),int(result[0][1])),(int(result[5][0]),int(result[5][1])),(0,255,0),3)
            
            
            cv2.line(img_black,(int(result[1][0]),int(result[1][1])),(int(result[3][0]),int(result[3][1])),(0,255,0),3)
            cv2.line(img_black,(int(result[1][0]),int(result[1][1])),(int(result[6][0]),int(result[6][1])),(0,255,0),3)
            
            
            cv2.line(img_black,(int(result[2][0]),int(result[2][1])),(int(result[3][0]),int(result[3][1])),(0,255,0),3)
            cv2.line(img_black,(int(result[2][0]),int(result[2][1])),(int(result[4][0]),int(result[4][1])),(0,255,0),3)

            
            cv2.line(img_black,(int(result[3][0]),int(result[3][1])),(int(result[4][0]),int(result[4][1])),(0,255,0),3)
            
           
            cv2.line(img_black,(int(result[5][0]),int(result[5][1])),(int(result[7][0]),int(result[7][1])),(0,255,0),3)
            cv2.line(img_black,(int(result[5][0]),int(result[5][1])),(int(result[6][0]),int(result[6][1])),(0,255,0),3)
            cv2.line(img_black,(int(result[5][0]),int(result[5][1])),(int(result[11][0]),int(result[11][1])),(0,255,0),3)
            
            
            cv2.line(img_black,(int(result[6][0]),int(result[6][1])),(int(result[8][0]),int(result[8][1])),(0,255,0),3)
            cv2.line(img_black,(int(result[6][0]),int(result[6][1])),(int(result[12][0]),int(result[12][1])),(0,255,0),3)

            
            cv2.line(img_black,(int(result[7][0]),int(result[7][1])),(int(result[9][0]),int(result[9][1])),(0,255,0),3)

            
            cv2.line(img_black,(int(result[8][0]),int(result[8][1])),(int(result[10][0]),int(result[10][1])),(0,255,0),3)

            
            cv2.line(img_black,(int(result[11][0]),int(result[11][1])),(int(result[12][0]),int(result[12][1])),(0,255,0),3)
            cv2.line(img_black,(int(result[11][0]),int(result[11][1])),(int(result[13][0]),int(result[13][1])),(0,255,0),3)

            
            cv2.line(img_black,(int(result[12][0]),int(result[12][1])),(int(result[14][0]),int(result[14][1])),(0,255,0),3)

            
            cv2.line(img_black,(int(result[13][0]),int(result[13][1])),(int(result[15][0]),int(result[15][1])),(0,255,0),3)

           
            cv2.line(img_black,(int(result[14][0]),int(result[14][1])),(int(result[16][0]),int(result[16][1])),(0,255,0),3)

            config = "../mmpretrain/configs/resnet/resnet50_8xb32_in1k.py"
            checkpoint = "../mmpretrain/work_dirs/resnet50_8xb32_in1k/epoch_100.pth" 

            cfg = Config.fromfile(config)
            inferencer = ImageClassificationInferencer(model=cfg, pretrained=checkpoint, device='cuda:0')
            result_pose = inferencer(img_black, show=True, show_dir='pose_result')[0]           
  

            # result_pose = inferencer(img_black, show=True, show_dir='pose_result')[0]           
            print(result_pose['pred_class'])

            yield results['predictions'][0][0]['keypoints']

        if self._video_input:
            self._finalize_video_processing(
                postprocess_kwargs.get('pred_out_dir', ''))

    def visualize(self, inputs: InputsType, preds: PredType,
                  **kwargs) -> List[np.ndarray]:
        """Visualize predictions.

        Args:
            inputs (list): Inputs preprocessed by :meth:`_inputs_to_list`.
            preds (Any): Predictions of the model.
            return_vis (bool): Whether to return images with predicted results.
            show (bool): Whether to display the image in a popup window.
                Defaults to False.
            show_interval (int): The interval of show (s). Defaults to 0
            radius (int): Keypoint radius for visualization. Defaults to 3
            thickness (int): Link thickness for visualization. Defaults to 1
            kpt_thr (float): The threshold to visualize the keypoints.
                Defaults to 0.3
            vis_out_dir (str, optional): directory to save visualization
                results w/o predictions. If left as empty, no file will
                be saved. Defaults to ''.

        Returns:
            List[np.ndarray]: Visualization results.
        """
        window_name = ''
        if self.inferencer._video_input:
            window_name = self.inferencer.video_info['name']

        return self.inferencer.visualize(
            inputs, preds, window_name=window_name, **kwargs)

_inferencer_demo.py_

# Copyright (c) OpenMMLab. All rights reserved.
from argparse import ArgumentParser
from typing import Dict

from mmpose.apis.inferencers import MMPoseInferencer, get_model_aliases

def parse_args():
    parser = ArgumentParser()
    parser.add_argument(
        '--inputs',
        type=str,
        default='webcam',
        help='Input image/video path or folder path.')
    parser.add_argument(
        '--pose2d',
        type=str,
        default='./configs/body_2d_keypoint/topdown_heatmap/coco/teddybear_td-hm_res50_8xb64-210e_coco-256x192.py',
        help='Pretrained 2D pose estimation algorithm. It\'s the path to the '
        'config file or the model name defined in metafile.')
    parser.add_argument(
        '--pose2d-weights',
        type=str,
        default='../teddybear/best_coco_AP_epoch_180.pth',
        help='Path to the custom checkpoint file of the selected pose model. '
        'If it is not specified and "pose2d" is a model name of metafile, '
        'the weights will be loaded from metafile.')
    parser.add_argument(
        '--pose3d',
        type=str,
        default=None,
        help='Pretrained 3D pose estimation algorithm. It\'s the path to the '
        'config file or the model name defined in metafile.')
    parser.add_argument(
        '--pose3d-weights',
        type=str,
        default=None,
        help='Path to the custom checkpoint file of the selected pose model. '
        'If it is not specified and "pose3d" is a model name of metafile, '
        'the weights will be loaded from metafile.')
    parser.add_argument(
        '--det-model',
        type=str,
        default=None,
        help='Config path or alias of detection model.')
    parser.add_argument(
        '--det-weights',
        type=str,
        default=None,
        help='Path to the checkpoints of detection model.')
    parser.add_argument(
        '--det-cat-ids',
        type=int,
        nargs='+',
        default=88,
        help='Category id for detection model.')
    parser.add_argument(
        '--scope',
        type=str,
        default='mmpose',
        help='Scope where modules are defined.')
    parser.add_argument(
        '--device',
        type=str,
        default='cuda:0',
        help='Device used for inference. '
        'If not specified, the available device will be automatically used.')
    parser.add_argument(
        '--show',
        action='store_true',
        help='Display the image/video in a popup window.')
    parser.add_argument(
        '--draw-bbox',
        action='store_true',
        help='Whether to draw the bounding boxes.')
    parser.add_argument(
        '--draw-heatmap',
        action='store_true',
        default=False,
        help='Whether to draw the predicted heatmaps.')
    parser.add_argument(
        '--bbox-thr',
        type=float,
        default=0.8,
        help='Bounding box score threshold')
    parser.add_argument(
        '--nms-thr',
        type=float,
        default=0.3,
        help='IoU threshold for bounding box NMS')
    parser.add_argument(
        '--kpt-thr', type=float, default=0.6, help='Keypoint score threshold')
    parser.add_argument(
        #defalt 0.3
        '--tracking-thr', type=float, default=0.3
        , help='Tracking threshold')
    parser.add_argument(
        '--use-oks-tracking',
        action='store_true',
        help='Whether to use OKS as similarity in tracking')
    parser.add_argument(
        '--disable-norm-pose-2d',
        action='store_true',
        help='Whether to scale the bbox (along with the 2D pose) to the '
        'average bbox scale of the dataset, and move the bbox (along with the '
        '2D pose) to the average bbox center of the dataset. This is useful '
        'when bbox is small, especially in multi-person scenarios.')
    parser.add_argument(
        '--disable-rebase-keypoint',
        action='store_true',
        default=False,
        help='Whether to disable rebasing the predicted 3D pose so its '
        'lowest keypoint has a height of 0 (landing on the ground). Rebase '
        'is useful for visualization when the model do not predict the '
        'global position of the 3D pose.')
    parser.add_argument(
        '--num-instances',
        type=int,
        default=1,
        help='The number of 3D poses to be visualized in every frame. If '
        'less than 0, it will be set to the number of pose results in the '
        'first frame.')
    parser.add_argument(
        '--radius',
        type=int,
        default=5,
        help='Keypoint radius for visualization.')
    parser.add_argument(
        '--thickness',
        type=int,
        default=2,
        help='Link thickness for visualization.')
    parser.add_argument(
        '--skeleton-style',
        default='mmpose',
        type=str,
        choices=['mmpose', 'openpose'],
        help='Skeleton style selection')
    parser.add_argument(
        '--black-background',
        action='store_true',
        help='Plot predictions on a black image')
    parser.add_argument(
        '--vis-out-dir',
        type=str,
        default='tmp_1117',
        help='Directory for saving visualized results.')
    parser.add_argument(
        '--pred-out-dir',
        type=str,
        default='',
        help='Directory for saving inference results.')
    parser.add_argument(
        '--show-alias',
        action='store_true',
        help='Display all the available model aliases.')
    
    

    call_args = vars(parser.parse_args())

    init_kws = [
        'pose2d', 'pose2d_weights', 'scope', 'device', 'det_model',
        'det_weights', 'det_cat_ids', 'pose3d', 'pose3d_weights'
    ]
    
    init_args = {}
    for init_kw in init_kws:
        init_args[init_kw] = call_args.pop(init_kw)

    diaplay_alias = call_args.pop('show_alias')

    return init_args, call_args, diaplay_alias

def display_model_aliases(model_aliases: Dict[str, str]) -> None:
    """Display the available model aliases and their corresponding model
    names."""
    aliases = list(model_aliases.keys())
    max_alias_length = max(map(len, aliases))
    print(f'{"ALIAS".ljust(max_alias_length+2)}MODEL_NAME')
    for alias in sorted(aliases):
        print(f'{alias.ljust(max_alias_length+2)}{model_aliases[alias]}')

def main():
    init_args, call_args, diaplay_alias = parse_args()
    if diaplay_alias:
        model_alises = get_model_aliases(init_args['scope'])
        display_model_aliases(model_alises)
    else:
        frame = 0
        inferencer = MMPoseInferencer(**init_args)
        
        for result in inferencer(**call_args):
            
            # print(result)
            # frame += 1
            pass

if __name__ == '__main__':
    main()

### Reproduces the problem - command or script

python inferencer.py 

### Reproduces the problem - error message

ResizeEdge is not in mmdet::transform registry. Please verify if the value of `ResizeEdge` is correct or registered as expected. For details, refer to https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module.'

and other registry name error (same Error Script)

### Additional information

If the model connection is not available, will you implement it in the future?

I always appreciate your work from the bottom of my heart.

**Comment by Ben-Louis** [comment]
Hello, I think you could try to replace `inferencer = ImageClassificationInferencer(model=cfg, pretrained=checkpoint, device='cuda:0')` with `inferencer = ImageClassificationInferencer(model=cfg, pretrained=checkpoint, device='cuda:0', scope='mmpretrain')`

**Comment by mmis00112** [comment]
Thanks for getting back to me.

I made the changes as instructed and got the following error
_code_
_
            config = "../mmpretrain/configs/resnet/resnet50_8xb32_in1k.py"
            checkpoint = "../mmpretrain/work_dirs/resnet50_8xb32_in1k/epoch_100.pth" 

            cfg = Config.fromfile(config)
            inferencer = ImageClassificationInferencer(model=cfg, pretrained=checkpoint, device='cuda:0', scope='mmpretrain')
            result_pose = inferencer(img_black, show=True, show_dir='pose_result')[0]           
  

            result_pose = inferencer(img_black, show=True, show_dir='pose_result')[0]           
            print(result_pose['pred_class'])


            yield results['predictions'][0][0]['keypoints']_

_error code_
Traceback (most recent call last):
  File "c:/Users/Baolab/mmpose/thr_decisive.py", line 323, in <module>
    main()
  File "c:/Users/Baolab/mmpose/thr_decisive.py", line 212, in main
    for result in inferencer(**call_args):
  File "c:\Users\Baolab\mmpose\mmpose\apis\inferencers\mmpose_inferencer.py", line 316, in __call__
    inferencer = ImageClassificationInferencer(model=cfg, pretrained=checkpoint, device='cuda:0', scope='mmpretrain')
  File "c:\users\baolab\mmpretrain\mmpretrain\apis\image_classification.py", line 66, in __init__
    super().__init__(
  File "c:\users\baolab\mmpretrain\mmpretrain\apis\base.py", line 109, in __init__
    model = get_model(
  File "c:\users\baolab\mmpretrain\mmpretrain\apis\model.py", line 192, in get_model
    model = MODELS.build(config.model)
  File "C:\Users\Baolab\.conda\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 573, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\Baolab\.conda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 254, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\Baolab\.conda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 142, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'scope'

**Comment by Ben-Louis** [comment]
I see. The inferencer in mmpretrain does not support argument `scope`. I would suggest moving the initialization of mmpretrain inferencer to the `__init__` function
```python
config = "../mmpretrain/configs/resnet/.py"
checkpoint = "../mmpretrain/work_dirs/resnet50_8xb32_in1k/epoch_100.pth" 
self.mmpretrain_inferencer = ImageClassificationInferencer(model=config, pretrained=checkpoint, device='cuda:0')
```
and calling it via `result_pose = self.mmpretrain_inferencer(img_black, show=True, show_dir='pose_result')[0]`
