### ISSUE TITLE
[Bug] Unknown layout when running simple 3d inference models

### ISSUE THREAD

**Issue by Lee4396** [open-mmlab/mmpose#2956]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Linux with Python3.10

### Reproduces the problem - code sample

after installing the library and successfully inferenced the 2d models, I and getting an Unknown Layout error when trying to run demo/body3d_pose_lifter_demo.py

### Reproduces the problem - command or script

python demo/body3d_pose_lifter_demo.py  \
demo/mmdetection_cfg/rtmdet_m_640-8xb32_coco-person.py \
https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth \
configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb256-420e_body8-256x192.py \
https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth \
configs/body_3d_keypoint/video_pose_lift/h36m/video-pose-lift_tcn-243frm-supv-cpn-ft_8xb128-200e_h36m.py \
https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth  \
--input https://user-images.githubusercontent.com/87690686/164970135-b14e424c-765a-4180-9bc8-fa8d6abc5510.mp4 \
--output-root  vis_results \
--save-predictions

### Reproduces the problem - error message

Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth
Downloading: "https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth" to /home/ec2-user/.cache/torch/hub/checkpoints/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 94.4M/94.4M [00:06<00:00, 16.1MB/s]
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
Downloading: "https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth" to /home/ec2-user/.cache/torch/hub/checkpoints/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 52.0M/52.0M [00:03<00:00, 15.5MB/s]
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth
Downloading: "https://download.openmmlab.com/mmpose/body3d/videopose/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth" to /home/ec2-user/.cache/torch/hub/checkpoints/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 64.8M/64.8M [00:04<00:00, 15.6MB/s]
/opt/conda/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/ec2-user/mmpose/demo/body3d_pose_lifter_demo.py", line 553, in <module>
    main()
  File "/home/ec2-user/mmpose/demo/body3d_pose_lifter_demo.py", line 488, in main
    next_id) = process_one_image(
  File "/home/ec2-user/mmpose/demo/body3d_pose_lifter_demo.py", line 213, in process_one_image
    det_result = inference_detector(detector, frame)
  File "/opt/conda/lib/python3.10/site-packages/mmdet/apis/inference.py", line 189, in inference_detector
    results = model.test_step(data_)[0]
  File "/opt/conda/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/detectors/base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/detectors/single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 279, in predict_by_feat
    results = self._predict_by_feat_single(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 423, in _predict_by_feat_single
    return self._bbox_post_process(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 485, in _bbox_post_process
    det_bboxes, keep_idxs = batched_nms(bboxes, results.scores,
  File "/opt/conda/lib/python3.10/site-packages/mmcv/ops/nms.py", line 303, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/utils/misc.py", line 395, in new_func
    output = old_func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmcv/ops/nms.py", line 127, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/mmcv/ops/nms.py", line 27, in forward
    inds = ext_module.nms(
RuntimeError: Unknown layout

### Additional information

seems the older version of the code works

**Comment by Ben-Louis** [comment]
Could you please share the package details displayed by running `pip list | grep mm`? This could help identify any version discrepancies.

**Comment by Lee4396** [comment]
> Could you please share the package details displayed by running `pip list | grep mm`? This could help identify any version discrepancies.

Hi,

Here it is <img width="488" alt="Screenshot 2024-02-19 at 08 40 21" src="https://github.com/open-mmlab/mmpose/assets/43795612/c34594e7-91a2-496e-9c46-3f9afa94bd6b">

**Comment by Ben-Louis** [comment]
Based on the error message, it seems that there is an incompatibility between the pre-compiled package and your device. To fix the issue, try reinstalling mmcv from source using the command `pip install git+https://github.com/open-mmlab/mmcv.git`.

**Comment by Lee4396** [comment]
> Based on the error message, it seems that there is an incompatibility between the pre-compiled package and your device. To fix the issue, try reinstalling mmcv from source using the command `pip install git+https://github.com/open-mmlab/mmcv.git`.

Yeah, I have tried this command and it gives the same error. It seems the command just installed the same version of mmcv.

**Comment by BenjiKCF** [comment]
Same issue
