### ISSUE TITLE
[Docs] how to set sigmas?

### ISSUE THREAD

**Issue by liujingtingdev** [open-mmlab/mmpose#2969]
### 📚 The doc issue

I want to fine-tune RTMPose with human3.6m dataset, I use the h36m_to_coco.py code provided by mmpose to generate human3.6 dataset in coco format, how to set sigmas and joint_weights during training, is it the setting h36m.py in config?

### Suggest a potential alternative/fix

add this in the fine-tune page

**Comment by Ben-Louis** [comment]
1) `sigmas` and `joint_weights` should be set in the metainfo file of the dataset
2) To generate `bbox_file`, please refer to https://github.com/open-mmlab/mmpose/blob/main/tools/misc/generate_bbox_file.py

**Comment by liujingtingdev** [comment]
Thank you very much for your answer, but I encountered a new problem when configuring the environment, and after configuring the environment according to the documentation, I encountered the following problem
02/29 21:28:05 - mmengine - WARNING - mmpose is not installed and its modules will not be registered. If you want to use modules defined in mmpose, Please install mmpose by `pip install mmpose.
02/29 21:28:05 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "./tools/train.py", line 162, in <module>
    main()
  File "./tools/train.py", line 155, in main
    runner = Runner.from_cfg(cfg)
  File "C:\Users\sutai\.conda\envs\mymmpose\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
    runner = cls(
  File "C:\Users\sutai\.conda\envs\mymmpose\lib\site-packages\mmengine\runner\runner.py", line 416, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "C:\Users\sutai\.conda\envs\mymmpose\lib\site-packages\mmengine\runner\runner.py", line 803, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "C:\Users\sutai\.conda\envs\mymmpose\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\sutai\.conda\envs\mymmpose\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'PoseLocalVisualizer is not in the mmengine::visualizer registry. Please check whether the value of `PoseLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

You can see from the pip list that mmpose has installed version 1.3.1
![image](https://github.com/open-mmlab/mmpose/assets/70000601/576c2eba-6d7a-4ffb-b235-cec4fea1e1d8)
