### ISSUE TITLE
[Bug] torch , mmpose old version 0.x and mmcv issue 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpose#3035]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

I am trying to work on the previous version of mmpose (0.x) , when running the collect_env it gives me this 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mmpose'
`
although , i try to install mmcv-full as it is the compatible one with mmpose (0.x) version , it took me long time without success. 
it gives me this error : 
<img width="323" alt="image" src="https://github.com/open-mmlab/mmpose/assets/10245810/880f664e-27c8-4d47-a086-cf83ad95896c">

after running this line `pip list | grep mm`, i got this : 
<img width="269" alt="image" src="https://github.com/open-mmlab/mmpose/assets/10245810/00c7fc41-7d19-44c7-b2a3-aca1cbacf6f1">

### Reproduces the problem - code sample

error in mmpose and mmcv versions , compatible with torch 

i try to install pytorch using this command : 
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`
as i can not create a conda environment in a cluster system

### Reproduces the problem - command or script

I want to run this code : 
`python tools/analysis_tools/get_flops.py ${CONFIG_FILE}`
using my config file which has been designed and built on previous mmpose (0.x) version.  as i want to calculate the number of parameters and flops in my model. 

### Reproduces the problem - error message

I run this line 
python tools/analysis/get_flops.py configs/excavator/resnet50normal/res50_animalpose_256x256_exc.py

i got this error : 

  File "tools/analysis/get_flops.py", line 5, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by alaa-shubbak** [comment]
i have this error now :
  ```
ModuleNotFoundError: No module named 'pip'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/shubbak/pose_env4/bin/python3.10 /home/shubbak/pose_env4/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/10545044.0.tmpdir/tmpcisn3jx1
  cwd: /tmp/10545044.0.tmpdir/pip-install-5zc93m1z/chumpy_3c4e7e9d91464cd88f5015607132a8fa
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

although my pip version is 
`pip 24.0 from /home/shubbak/pose_env4/lib/python3.10/site-packages/pip (python 3.10)`

any help plz
