### ISSUE TITLE
[Bug] KeyError: 'bbox'

### ISSUE THREAD

**Issue by Adblu** [open-mmlab/mmpose#3155]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

Environment:

OrderedDict([('sys.platform', 'linux'), ('Python', '3.8.20 | packaged by conda-forge | (default, Sep 30 2024, 17:52:49) [GCC 13.3.0]'), ('CUDA available', True), ('MUSA available', False), ('numpy_random_seed', 2147483648), ('GPU 0', 'NVIDIA T1200 Laptop GPU'), ('CUDA_HOME', '/usr/local/cuda'), ('NVCC', 'Cuda compilation tools, release 12.5, V12.5.40'), ('GCC', 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0'), ('PyTorch', '2.4.1+cu121'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v3.4.2 (Git Hash 1137e04ec0b5251ca2b4400a4fd3c667ce843d67)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - CUDA Runtime 12.1\n  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90\n  - CuDNN 90.1  (built against CUDA 12.4)\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=9.1.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.4.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, \n'), ('TorchVision', '0.19.1+cu121'), ('OpenCV', '4.10.0'), ('MMEngine', '0.10.5'), ('MMPose', '1.3.2+71ec36e')])

MM versions:

pip list | grep mm       
mmcv                     2.1.0
mmdet                    3.3.0
mmengine                 0.10.5
mmpose                   1.1.0

### Reproduces the problem - code sample

python demo/bottomup_demo.py configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_litehrnet-30_8xb64-210e_mpii-256x256.py https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_mpii_256x256-faae8bd8_20210622.pth --input /home/video.mp4 --output-root=vis_results --show --save-predictions

### Reproduces the problem - command or script

python demo/bottomup_demo.py configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_litehrnet-30_8xb64-210e_mpii-256x256.py https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_mpii_256x256-faae8bd8_20210622.pth --input /home/video.mp4 --output-root=vis_results --show --save-predictions

### Reproduces the problem - error message

Traceback (most recent call last):
  File "demo/bottomup_demo.py", line 237, in <module>
    main()
  File "demo/bottomup_demo.py", line 175, in main
    pred_instances = process_one_image(args, frame, model, visualizer,
  File "demo/bottomup_demo.py", line 28, in process_one_image
    batch_results = inference_bottomup(pose_estimator, img)
  File "/home/ictadmin/anaconda3/envs/mpose/lib/python3.8/site-packages/mmpose/apis/inference.py", line 223, in inference_bottomup
    data = pipeline(data_info)
  File "/home/ictadmin/anaconda3/envs/mpose/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
    data = t(data)
  File "/home/ictadmin/anaconda3/envs/mpose/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/ictadmin/anaconda3/envs/mpose/lib/python3.8/site-packages/mmpose/datasets/transforms/common_transforms.py", line 75, in transform
    bbox = results['bbox']
KeyError: 'bbox'

### Additional information

Any idea ??

**Comment by YaqiZhai** [comment]
maybe you can try to print results.keys() to see if your results have bbox_scale and bbox_center.cause this code wanna use result['bbox'] to calculate bbox_scale and bbox_center. however some datasets already have bbox_center and  bbox_scale .
![image](https://github.com/user-attachments/assets/7ec6cd0c-ebc5-4ca9-95d3-7643184ac5f1)
