### ISSUE TITLE
CUDA OUT OF MEMORY with dist_train.sh

### ISSUE THREAD

**Issue by SAIL-LAB155** [open-mmlab/mmpose#321]
Hello. When I am using ./tools/dist_train.sh, I found that the CUDA error will occur.
I use the command _"./tools/dist_train.sh  configs/bottom_up/mobilenet/coco/mobilenetv2_coco_512x512.py 3"_. My server has 4 GPUs, and GPU 0,1,3 are available. The information is shown below. 
I wonder what's the meaning and how to solve it?

```bash
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
    main()
  File "./tools/train.py", line 98, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 423, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/mm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/anaconda3/envs/mm/bin/python', '-u', './tools/train.py', '--local_rank=2', 'configs/bottom_up/mobilenet/coco/mobilenetv2_coco_512x512.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
 \Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
    main()
  File "./tools/train.py", line 98, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: out of memory
Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
    main()
  File "./tools/train.py", line 98, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729006826/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
^C
Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
    main()
  File "./tools/train.py", line 98, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/home/user/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729006826/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
```

**Comment by innerlee** [comment]
> RuntimeError: Address already in use

Change port in the script?

**Comment by SAIL-LAB155** [comment]
Emmm I indeed didn't change the port address... 
Are there any docs about how to find an unused port? Sorry that I didn't have any experience in distributed training and I don't know which port I should select.

**Comment by innerlee** [comment]
There are tools for that. Another approach is to try random numbers, and hope you get luck

**Comment by Canwang-sjtu** [comment]
For example: PORT=22334 bash tools/dist_train.sh configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py 1
