### ISSUE TITLE
MSPN inference problem

### ISSUE THREAD

**Issue by fedorchuk1** [open-mmlab/mmpose#358]
Hi, I`m trying to run MSPN model on inference and got the following problem: 

```
Traceback (most recent call last):
  File "demo/top_down_video_demo_with_mmdet.py", line 140, in <module>
    main()
  File "demo/top_down_video_demo_with_mmdet.py", line 105, in main
    pose_results, returned_outputs = inference_top_down_pose_model(
  File "/home/taras.fedorchuk/pose_estimation/mmpose/mmpose/apis/inference.py", line 298, in inference_top_down_pose_model
    pose, heatmap = _inference_single_pose_model(
  File "/home/taras.fedorchuk/pose_estimation/mmpose/mmpose/apis/inference.py", line 224, in _inference_single_pose_model
    data = test_pipeline(data)
  File "/home/taras.fedorchuk/pose_estimation/mmpose/mmpose/datasets/pipelines/shared_transform.py", line 78, in __call__
    data = t(data)
  File "/home/taras.fedorchuk/pose_estimation/mmpose/mmpose/datasets/pipelines/shared_transform.py", line 134, in __call__
    meta[key] = results[key]
KeyError: 'bbox_id'
```

Thanks for the help!

**Comment by innerlee** [comment]
Delete `bbox_id` from config

**Comment by fedorchuk1** [comment]
It helped. Thank you!
