### ISSUE TITLE
geos_c dll missing

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmpose#363]
Running the top_down_img_demo.py example, an error is thrown that shapely cannot find geos_c.dll. When I just try to import inference_top_down_pose_model/bottom_up_pose_model, the same error appears (see below)
```
>>> from mmpose.apis import inference_top_down_pose_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\apis\__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\apis\inference.py", line 9, in <module>
    from mmpose.datasets.pipelines import Compose
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\__init__.py", line 2, in <module>
    from .datasets import (BottomUpCocoDataset, BottomUpCrowdPoseDataset,
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\datasets\__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\datasets\top_down\__init__.py", line 9, in <module>
    from .topdown_posetrack18_dataset import TopDownPoseTrack18Dataset
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\datasets\top_down\topdown_posetrack18_dataset.py", line 8, in <module>
    from poseval import eval_helpers
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\poseval\eval_helpers.py", line 2, in <module>
    from shapely import geometry
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
>>> from mmpose.apis import inference_bottom_up_pose_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\apis\__init__.py", line 5, in <module>
    from .train import train_model
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\apis\train.py", line 8, in <module>
    from mmpose.datasets import build_dataloader, build_dataset
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\__init__.py", line 2, in <module>
    from .datasets import (BottomUpCocoDataset, BottomUpCrowdPoseDataset,
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\datasets\__init__.py", line 8, in <module>
    from .top_down import (TopDownAicDataset, TopDownCocoDataset,
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\datasets\top_down\__init__.py", line 9, in <module>
    from .topdown_posetrack18_dataset import TopDownPoseTrack18Dataset
  File "C:\Users\nuzuegbunam\Documents\Projects\mmpose\mmpose\datasets\datasets\top_down\topdown_posetrack18_dataset.py", line 8, in <module>
    from poseval import eval_helpers
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\poseval\eval_helpers.py", line 2, in <module>
    from shapely import geometry
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\nuzuegbunam\Anaconda3\envs\open-mmlab38\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.


```

I was only able to solve it by using: `conda install shapely`.  I was curious if this a pip install issue or if it is a windows issue? Do I need to update the requirements for install.

**Comment by innerlee** [comment]
Could you try this in python repl?

```python
from poseval import eval_helpers
```

**Comment by innerlee** [comment]
I installed poseval on a windows machine, and it installs shapely automatically. So this might be an accident.

![image](https://user-images.githubusercontent.com/9464825/102569579-abae0700-4120-11eb-892f-24b80853c2ca.png)

**Comment by nikky4D** [comment]
The code: `from poseval import eval_helpers`, works on my setup.

**Comment by innerlee** [comment]
The previous error is caused by the missing of `shapely`, which is a dependency of `poseval`. After you installed `shapely` manually, everything works.  

Normally it will install all dependencies correctly.

**Comment by nikky4D** [comment]
Thanks. I'll close this now.
