### ISSUE TITLE
Error when conducting dist_train

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmpose#376]
Hello. When I am training with ./dist_train.sh with 4 GPUs, an error occurs:

```bash
./tools/dist_train.sh configs/bottom_up/mobilenet/coco/mobilenetv2_coco_512x512.py 4 --resume-from work_dirs/mobilenetv2_coco_512x512/latest.pth
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2020-12-21 10:42:45,361 - mmpose - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.2.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMPose: 0.9.0+be4b35b
------------------------------------------------------------

2020-12-21 10:42:45,362 - mmpose - INFO - Distributed training: True
2020-12-21 10:42:46,544 - mmpose - INFO - Config:
log_level = 'INFO'
load_from = None
resume_from = 'work_dirs/mobilenetv2_coco_512x512/latest.pth'
dist_params = dict(backend='nccl')
workflow = [('train', 1)]
checkpoint_config = dict(interval=20)
evaluation = dict(interval=20, metric='mAP', key_indicator='AP')
optimizer = dict(type='Adam', lr=0.0015)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[200, 260])
total_epochs = 300
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
channel_cfg = dict(
    dataset_joints=17,
    dataset_channel=[[
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
    ]],
    inference_channel=[
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
    ])
data_cfg = dict(
    image_size=512,
    base_size=256,
    base_sigma=2,
    heatmap_size=[128],
    num_joints=17,
    dataset_channel=[[
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
    ]],
    inference_channel=[
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
    ],
    num_scales=1,
    scale_aware_sigma=False)
model = dict(
    type='BottomUp',
    pretrained='mmcls://mobilenet_v2',
    backbone=dict(type='MobileNetV2', widen_factor=1.0, out_indices=(7, )),
    keypoint_head=dict(
        type='BottomUpSimpleHead',
        in_channels=1280,
        num_joints=17,
        tag_per_joint=True,
        with_ae_loss=[True]),
    train_cfg=dict(num_joints=17, img_size=512),
    test_cfg=dict(
        num_joints=17,
        max_num_people=30,
        scale_factor=[1],
        with_heatmaps=[True],
        with_ae=[True],
        project2image=True,
        nms_kernel=5,
        nms_padding=2,
        tag_per_joint=True,
        detection_threshold=0.1,
        tag_threshold=1,
        use_detection_val=True,
        ignore_too_much=False,
        adjust=True,
        refine=True,
        flip_test=True),
    loss_pose=dict(
        type='MultiLossFactory',
        num_joints=17,
        num_stages=1,
        ae_loss_type='exp',
        with_ae_loss=[True],
        push_loss_factor=[0.001],
        pull_loss_factor=[0.001],
        with_heatmaps_loss=[True],
        heatmaps_loss_factor=[1.0]))
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='BottomUpRandomAffine',
        rot_factor=30,
        scale_factor=[0.75, 1.5],
        scale_type='short',
        trans_factor=40),
    dict(type='BottomUpRandomFlip', flip_prob=0.5),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(type='BottomUpGenerateTarget', sigma=2, max_num_people=30),
    dict(
        type='Collect',
        keys=['img', 'joints', 'targets', 'masks'],
        meta_keys=[])
]
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
    dict(
        type='BottomUpResizeAlign',
        transforms=[
            dict(type='ToTensor'),
            dict(
                type='NormalizeTensor',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225])
        ]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'aug_data', 'test_scale_factor', 'base_size',
            'center', 'scale', 'flip_index'
        ])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
    dict(
        type='BottomUpResizeAlign',
        transforms=[
            dict(type='ToTensor'),
            dict(
                type='NormalizeTensor',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225])
        ]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'aug_data', 'test_scale_factor', 'base_size',
            'center', 'scale', 'flip_index'
        ])
]
data_root = '../coco'
data = dict(
    samples_per_gpu=24,
    workers_per_gpu=1,
    train=dict(
        type='BottomUpCocoDataset',
        ann_file='../coco/annotations/person_keypoints_train2017.json',
        img_prefix='../coco/train2017/',
        data_cfg=dict(
            image_size=512,
            base_size=256,
            base_sigma=2,
            heatmap_size=[128],
            num_joints=17,
            dataset_channel=[[
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
            ]],
            inference_channel=[
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
            ],
            num_scales=1,
            scale_aware_sigma=False),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='BottomUpRandomAffine',
                rot_factor=30,
                scale_factor=[0.75, 1.5],
                scale_type='short',
                trans_factor=40),
            dict(type='BottomUpRandomFlip', flip_prob=0.5),
            dict(type='ToTensor'),
            dict(
                type='NormalizeTensor',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]),
            dict(type='BottomUpGenerateTarget', sigma=2, max_num_people=30),
            dict(
                type='Collect',
                keys=['img', 'joints', 'targets', 'masks'],
                meta_keys=[])
        ]),
    val=dict(
        type='BottomUpCocoDataset',
        ann_file='../coco/annotations/person_keypoints_val2017.json',
        img_prefix='../coco/val2017/',
        data_cfg=dict(
            image_size=512,
            base_size=256,
            base_sigma=2,
            heatmap_size=[128],
            num_joints=17,
            dataset_channel=[[
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
            ]],
            inference_channel=[
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
            ],
            num_scales=1,
            scale_aware_sigma=False),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
            dict(
                type='BottomUpResizeAlign',
                transforms=[
                    dict(type='ToTensor'),
                    dict(
                        type='NormalizeTensor',
                        mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
                ]),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'image_file', 'aug_data', 'test_scale_factor', 'base_size',
                    'center', 'scale', 'flip_index'
                ])
        ]),
    test=dict(
        type='BottomUpCocoDataset',
        ann_file='../coco/annotations/person_keypoints_val2017.json',
        img_prefix='../coco/val2017/',
        data_cfg=dict(
            image_size=512,
            base_size=256,
            base_sigma=2,
            heatmap_size=[128],
            num_joints=17,
            dataset_channel=[[
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
            ]],
            inference_channel=[
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
            ],
            num_scales=1,
            scale_aware_sigma=False),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='BottomUpGetImgSize', test_scale_factor=[1]),
            dict(
                type='BottomUpResizeAlign',
                transforms=[
                    dict(type='ToTensor'),
                    dict(
                        type='NormalizeTensor',
                        mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
                ]),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'image_file', 'aug_data', 'test_scale_factor', 'base_size',
                    'center', 'scale', 'flip_index'
                ])
        ]))
work_dir = './work_dirs/mobilenetv2_coco_512x512'
gpu_ids = range(0, 1)

loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Done (t=5.57s)
creating index...
Done (t=5.66s)
creating index...
Done (t=5.67s)
creating index...
Done (t=5.71s)
creating index...
index created!
index created!
index created!
index created!
=> num_images: 64115
=> num_images: 64115
=> num_images: 64115
=> num_images: 64115
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Done (t=0.16s)
creating index...
Done (t=0.16s)
creating index...
Done (t=0.16s)
creating index...
Done (t=0.16s)
creating index...
index created!
index created!
index created!
=> num_images: 5000
2020-12-21 10:42:55,182 - mmpose - INFO - load checkpoint from work_dirs/mobilenetv2_coco_512x512/latest.pth
=> num_images: 5000
index created!
=> num_images: 5000
=> num_images: 5000
Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
    main()
  File "./tools/train.py", line 152, in main
    main()
  File "./tools/train.py", line 152, in main
    meta=meta)
  File "/media/hkuit155/Elements/mmpose/mmpose/apis/train.py", line 129, in train_model
    meta=meta)
  File "/media/hkuit155/Elements/mmpose/mmpose/apis/train.py", line 129, in train_model
    runner.resume(cfg.resume_from)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 323, in resume
    runner.resume(cfg.resume_from)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 323, in resume
    map_location=lambda storage, loc: storage.cuda(device_id))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 312, in load_checkpoint
    map_location=lambda storage, loc: storage.cuda(device_id))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 312, in load_checkpoint
    self.logger)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint
    self.logger)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 223, in _load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 223, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
    result = unpickler.load()
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 833, in load_tensor
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94101839026144: invalid header or archive is corrupted
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94101839026144: invalid header or archive is corrupted
Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
    main()
  File "./tools/train.py", line 152, in main
    meta=meta)
  File "/media/hkuit155/Elements/mmpose/mmpose/apis/train.py", line 129, in train_model
    runner.resume(cfg.resume_from)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 323, in resume
    map_location=lambda storage, loc: storage.cuda(device_id))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 312, in load_checkpoint
    self.logger)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 223, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94101839026144: invalid header or archive is corrupted
Traceback (most recent call last):
  File "./tools/train.py", line 156, in <module>
    main()
  File "./tools/train.py", line 152, in main
    meta=meta)
  File "/media/hkuit155/Elements/mmpose/mmpose/apis/train.py", line 129, in train_model
    runner.resume(cfg.resume_from)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 323, in resume
    map_location=lambda storage, loc: storage.cuda(device_id))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 312, in load_checkpoint
    self.logger)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 223, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94101839026144: invalid header or archive is corrupted
Traceback (most recent call last):
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hkuit155/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/bottom_up/mobilenet/coco/mobilenetv2_coco_512x512.py', '--launcher', 'pytorch', '--resume-from', 'work_dirs/mobilenetv2_coco_512x512/latest.pth']' died with <Signals.SIGSEGV: 11>.
```

I wonder whether it is a system error? How can I solve it. Thank you.

**Comment by CheungBH** [comment]
I am resuming a model using --resume-from. I wonder whether there are any potential problems in resuming, because it seems to get some error in resuming.

**Comment by innerlee** [comment]
>PytorchStreamReader failed reading file data/94101839026144: invalid header or archive is corrupted

Looks like the storage is corrupted.

**Comment by CheungBH** [comment]
Oh thanks. I tried to train it again, but another error occurs. Is it caused by training data?

Traceback (most recent call last):
  File "tools/train.py", line 156, in <module>
    main()
  File "tools/train.py", line 152, in main
    meta=meta)
  File "/home/hkuit155/Documents/mmpose/mmpose/apis/train.py", line 80, in train_model
    flops, paras = get_model_complexity_info(model,input_shape)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/utils/flops_counter.py", line 101, in get_model_complexity_info
    _ = flops_model(batch,torch.randn(64,16,64,64),torch.randn(64,16,1))
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hkuit155/Documents/mmpose/mmpose/models/detectors/bottom_up.py", line 114, in forward
    **kwargs)
  File "/home/hkuit155/Documents/mmpose/mmpose/models/detectors/bottom_up.py", line 158, in forward_train
    output, targets, masks, joints)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hkuit155/Documents/mmpose/mmpose/models/losses/multi_loss_factory.py", line 234, in forward
    masks[idx])
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hkuit155/Documents/mmpose/mmpose/models/losses/multi_loss_factory.py", line 46, in forward
    assert pred.size() == gt.size()
AssertionError

**Comment by innerlee** [comment]
> get_model_complexity_info

why it runs the flops script?

**Comment by CheungBH** [comment]
> > get_model_complexity_info
> 
> why it runs the flops script?

Someone else in my team wrongly modify the code...Thanks for your warning...
