### ISSUE TITLE
top_down_pose_tracking_demo RuntimeError

### ISSUE THREAD

**Issue by 13517592731** [open-mmlab/mmpose#392]
My Runtime: RTX3090, cuda11.1, cudnn8.0.5, pytorch1.7.1
When I run top_down_pose_tracking_demo_with_mmdet, I get a error

```bash
Traceback (most recent call last):
  File "demo/top_down_pose_tracking_demo_with_mmdet.py", line 150, in <module>
    main()
  File "demo/top_down_pose_tracking_demo_with_mmdet.py", line 105, in main
    mmdet_results = inference_detector(det_model, img)
  File "/home/machine/project/python/deep-learn/mmpose/mmdetection/mmdet/apis/inference.py", line 123, in inference_detector
    result = model(return_loss=False, rescale=True, **data)[0]
  File "/home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/machine/project/python/deep-learn/mmpose/mmdetection/mmdet/models/detectors/base.py", line 182, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/machine/project/python/deep-learn/mmpose/mmdetection/mmdet/models/detectors/base.py", line 159, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/machine/project/python/deep-learn/mmpose/mmdetection/mmdet/models/detectors/two_stage.py", line 194, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/home/machine/project/python/deep-learn/mmpose/mmdetection/mmdet/models/dense_heads/rpn_test_mixin.py", line 36, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/machine/project/python/deep-learn/mmpose/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 571, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/machine/project/python/deep-learn/mmpose/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 167, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 259, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 113, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 19, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device
Exception raised from NMSCUDAKernelLauncher at /tmp/mmcv/mmcv/ops/csrc/pytorch/nms_cuda.cu:50 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fab851d48b2 in /home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: NMSCUDAKernelLauncher(at::Tensor, at::Tensor, float, int) + 0x77a (0x7fab3cb62ff2 in /home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #2: nms_cuda(at::Tensor, at::Tensor, float, int) + 0x4f (0x7fab3cafb38f in /home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #3: nms(at::Tensor, at::Tensor, float, int) + 0x1bb (0x7fab3cafc39b in /home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0xd63cb (0x7fab3cb913cb in /home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0xcd23f (0x7fab3cb8823f in /home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #10: THPFunction_apply(_object*, _object*) + 0x93d (0x7fac0448900d in /home/machine/application/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
```

**Comment by jin-s13** [comment]
`RuntimeError: CUDA error: no kernel image is available for execution on the device`
It seems that CUDA / pytorch is not installed properly.

**Comment by innerlee** [comment]
Kindly ping @13517592731

**Comment by jin-s13** [comment]
closing due to inactivity
