### ISSUE TITLE
evaluation is very slow, about half hour on V100(coco2017 val)

### ISSUE THREAD

**Issue by maowayne123** [open-mmlab/mmpose#515]

**Comment by innerlee** [comment]
Thanks for the report. Infrence speed up is on our March plan https://github.com/open-mmlab/mmpose/issues/513

**Comment by jin-s13** [comment]
Please try using `batchsize>1` when evaluation, see [resnet50](https://github.com/open-mmlab/mmpose/blob/4a552d0db7d3410d5e26209aaa7dea7a99d53914/configs/top_down/resnet/coco/res50_coco_256x192.py#L122)

**Comment by wuyuuu** [comment]
> Please try using `batchsize>1` when evaluation, see [resnet50](https://github.com/open-mmlab/mmpose/blob/4a552d0db7d3410d5e26209aaa7dea7a99d53914/configs/top_down/resnet/coco/res50_coco_256x192.py#L122)

Hi Jin,
I try to change the batch size when evaluating for a bottom-up model, but it seems like it does not work for bottom-up models. 
I got:
```
loading annotations into memory...
Done (t=0.44s)
creating index...
index created!
=> num_images: 5000
Use load_from_local loader
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/home2/wuy/project/mmpose/tools/test.py", line 141, in <module>
    main()
  File "/home2/wuy/project/mmpose/tools/test.py", line 119, in main
    outputs = single_gpu_test(model, data_loader)
  File "/home2/wuy/project/mmpose/mmpose/apis/test.py", line 30, in single_gpu_test
    for data in data_loader:
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp>
    for key in batch[0]
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 84, in collate
    return default_collate(batch)
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home2/wuy/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [427, 640, 3] at entry 0 and [230, 352, 3] at entry 1

```

**Comment by jin-s13** [comment]
Yes, it only works for top-down approaches now.
