### ISSUE TITLE
AssertionError: Please install mmtrack to run the demo.

### ISSUE THREAD

**Issue by seunghalee1226** [open-mmlab/mmpose#530]
I completely installed mmtrack, mmcv, mmdet and mmpose, but i got this AssertionError about mmtrack module.

How could i fix it?

**Reproduction**

- What command or script did you run?

```
(mmpose) airteam@air:~/shl/mmpose$ python demo/top_down_pose_tracking_demo_with_mmtracking.py demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py configs/top_down/hrnet/coco/hrnet_w48_coco_384x288.py work_dirs/hrnet_w48_coco_384x288/epoch_40.pth --video-path data/tail5.mp4 --show --device 0 --bbox-thr 0.1 --kpt-thr 0.1

```

- What config did you run?

```
log_level = 'INFO'
load_from = None
resume_from = None
dist_params = dict(backend='nccl')
workflow = [('train', 1)]
checkpoint_config = dict(interval=10)
evaluation = dict(interval=10, metric='mAP', key_indicator='AP')

optimizer = dict(
    type='Adam',
    lr=3e-4,
    weight_decay=0.001
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    # warmup=None,
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[170, 200])
total_epochs = 210
log_config = dict(
    interval=10,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])

channel_cfg = dict(
    num_output_channels=17,
    dataset_joints=17,
    dataset_channel=[
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    ],
    inference_channel=[
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17
    ])

# model settings
model = dict(
    type='TopDown',
    pretrained='https://download.openmmlab.com/mmpose/'
    'pretrain_models/hrnet_w48-8ef0771d.pth',
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(48, 96)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(48, 96, 192)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(48, 96, 192, 384))),
    ),
    keypoint_head=dict(
        type='TopDownSimpleHead',
        in_channels=48,
        out_channels=channel_cfg['num_output_channels'],
        num_deconv_layers=0,
        extra=dict(final_conv_kernel=1, ),
        loss_keypoint=dict(type='JointsMSELoss', use_target_weight=True)),
    train_cfg=dict(),
    test_cfg=dict(
        flip_test=True,
        post_process='default',
        shift_heatmap=True,
        modulate_kernel=11))

data_cfg = dict(
    image_size=[288, 384],
    heatmap_size=[72, 96],
    num_output_channels=channel_cfg['num_output_channels'],
    num_joints=channel_cfg['dataset_joints'],
    dataset_channel=channel_cfg['dataset_channel'],
    inference_channel=channel_cfg['inference_channel'],
    soft_nms=False,
    nms_thr=1.0,
    oks_thr=0.9,
    vis_thr=0.2,
    use_gt_bbox=True,
    det_bbox_thr=0.0,
    bbox_file='data/'
    'pig1_20210319.json',
)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownRandomFlip', flip_prob=0.5),
    dict(
        type='TopDownHalfBodyTransform',
        num_joints_half_body=8,
        prob_half_body=0.3),
    dict(
        type='TopDownGetRandomScaleRotation', rot_factor=40, scale_factor=0.5),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(type='TopDownGenerateTarget', sigma=3),
    dict(
        type='Collect',
        keys=['img', 'target', 'target_weight'],
        meta_keys=[
            'image_file', 'joints_3d', 'joints_3d_visible', 'center', 'scale',
            'rotation', 'bbox_score', 'flip_pairs'
        ]),
]

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='NormalizeTensor',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'center', 'scale', 'rotation', 'bbox_score',
            'flip_pairs'
        ]),
]

test_pipeline = val_pipeline

data_root = 'data/'
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=2,
    train=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/pig1_20210319.json',
        img_prefix=f'{data_root}/train2017/',
        data_cfg=data_cfg,
        pipeline=train_pipeline),
    val=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/1_74.json',
        img_prefix=f'{data_root}/val2017/',
        data_cfg=data_cfg,
        pipeline=val_pipeline),
    test=dict(
        type='TopDownCocoDataset',
        ann_file=f'{data_root}/101_149.json',
        img_prefix=f'{data_root}/val2017/',
        data_cfg=data_cfg,
        pipeline=val_pipeline),
)
```

** Conda list **
```

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_pytorch_select           0.1                       cpu_0
addict                    2.4.0                    pypi_0    pypi
albumentations            0.5.2                    pypi_0    pypi
apex                      0.1                      pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2021.1.19            h06a4308_1
certifi                   2020.12.5        py37h06a4308_0
cffi                      1.14.4           py37h261ae71_0
chumpy                    0.70                     pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coverage                  5.3                      pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
dotty-dict                1.3.0                    pypi_0    pypi
flake8                    3.8.4                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0
future                    0.18.2                   pypi_0    pypi
geos                      3.8.0                he6710b0_0
imageio                   2.9.0                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        3.3.0                    pypi_0    pypi
imutils                   0.5.3                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2020.2                      254
interrogate               1.3.2                    pypi_0    pypi
ipython_genutils          0.2.0                    py37_0
isort                     4.3.21                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2
json-tricks               3.15.5                   pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 9.1.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_1
libuv                     1.40.0               h7b6447c_0
lz4-c                     1.9.2                heb0550a_3
matplotlib                3.3.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.2.0            py37h23d657b_0
mkl_random                1.1.1            py37h0573a6f_0
mmcls                     0.9.0                    pypi_0    pypi
mmcv-full                 1.2.1                    pypi_0    pypi
mmdet                     2.6.0                     dev_0    <develop>
mmpose                    0.12.0                    dev_0    <develop>
mmpycocotools             12.0.3                   pypi_0    pypi
mmtrack                   0.5.0                     dev_0    <develop>
motmetrics                1.2.0                    pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1
networkx                  2.5                      pypi_0    pypi
ninja                     1.10.1           py37hfd86e86_0
numpy                     1.19.2           py37h54aff64_0
numpy-base                1.19.2           py37hfa32c7d_0
olefile                   0.46                     py37_0
onnx                      1.8.1                    pypi_0    pypi
onnxruntime               1.7.0                    pypi_0    pypi
opencv-contrib-python     4.5.1.48                 pypi_0    pypi
opencv-python             4.4.0.46                 pypi_0    pypi
opencv-python-headless    4.5.1.48                 pypi_0    pypi
openssl                   1.1.1j               h27cfd23_0
packaging                 20.8                     pypi_0    pypi
pandas                    1.1.5                    pypi_0    pypi
pillow                    8.0.1            py37he98fc37_0
pip                       20.2.4           py37h06a4308_0
pluggy                    0.13.1                   pypi_0    pypi
poseval                   0.1.0                    pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
py                        1.10.0                   pypi_0    pypi
py-cpuinfo                7.0.0                    pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pycparser                 2.20                       py_2
pyflakes                  2.2.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pytest                    6.2.0                    pypi_0    pypi
pytest-benchmark          3.2.3                    pypi_0    pypi
pytest-runner             5.2                      pypi_0    pypi
python                    3.7.9                h7579374_0
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.7.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2020.4                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0
scikit-image              0.18.1                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
setuptools                50.3.1           py37h06a4308_1
setuptools-scm            6.0.1                    pypi_0    pypi
shapely                   1.6.4            py37hc5e8c75_0
six                       1.15.0           py37h06a4308_0
smplx                     0.1.26                   pypi_0    pypi
sqlite                    3.33.0               h62c20be_0
tabulate                  0.8.7                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
terminaltables            3.1.0                    pypi_0    pypi
tifffile                  2021.3.17                pypi_0    pypi
tk                        8.6.10               hbc83047_0
toml                      0.10.2                   pypi_0    pypi
torchaudio                0.7.0                      py37    pytorch
torchgeometry             0.1.2                    pypi_0    pypi
torchvision               0.8.0                py37_cu101    pytorch
tqdm                      4.54.1                   pypi_0    pypi
typing_extensions         3.7.4.3                    py_0
wheel                     0.35.1             pyhd3eb1b0_0
xdoctest                  0.15.0                   pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
xtcocotools               1.6                      pypi_0    pypi
xz                        5.2.5                h7b6447c_0
yapf                      0.30.0                   pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h9ceee32_0

```

**Environment**
```
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.0
OpenCV: 4.5.1
MMCV: 1.2.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMPose: 0.12.0+c28f54a
```

**Error traceback**

If applicable, paste the error traceback here.

```
Traceback (most recent call last):
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 151, in <module>
    main()
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 62, in main
    assert has_mmtrack, 'Please install mmtrack to run the demo.'
AssertionError: Please install mmtrack to run the demo.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by jin-s13** [comment]
@luminxu  please try if this problem can be reproduced.

**Comment by luminxu** [comment]
It seems that you have not installed mmtracking successfully. Please install mmtracking and conduct **_verification_** following [mmtracking](https://github.com/open-mmlab/mmtracking/blob/master/docs/install.md). You can also verify it by 'from mmtrack.apis import inference_mot, init_model' to check whether there is any problem with importing mmtracking. Besides, please note that your installed mmcv-full==1.2.1 is incompatible with latest mmtracking.

**Comment by seunghalee1226** [comment]
I did re-install and verify if by 'from mmtrack.apis import inference_mot, init_model' .
But I tried to conduct same command, i got this error.

```
(mmpose) airteam@air:~/shl/mmpose$ python demo/top_down_pose_tracking_demo_with_mmtracking.py demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py configs/top_down/hrnet/coco/hrnet_w48_coco_384x288.py work_dirs/hrnet_w48_coco_384x288/epoch_40.pth --video-path data/tail5.mp4 --show --device 0 --bbox-thr 0.1 --kpt-thr 0.1
2021-04-01 11:35:04,892 - mmtrack - INFO - load detector from: https://download.openmmlab.com/mmtracking/mot/faster_rcnn/faster-rcnn_r50_fpn_4e_mot17-ffa52ae7.pth
2021-04-01 11:35:04,892 - mmtrack - INFO - Use load_from_http loader
2021-04-01 11:35:04,978 - mmtrack - INFO - load reid from: https://download.openmmlab.com/mmtracking/mot/reid/tracktor_reid_r50_iter25245-a452f51f.pth
2021-04-01 11:35:04,979 - mmtrack - INFO - Use load_from_http loader
Traceback (most recent call last):
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 151, in <module>
    main()
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 70, in main
    args.tracking_config, None, device=args.device.lower())
  File "/datas/airteam/shl/mmtracking/mmtrack/apis/inference.py", line 47, in init_model
    model.to(device)
  File "/home/airteam/anaconda3/envs/mmpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 600, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Invalid device string: '0'
```

**Comment by innerlee** [comment]
The mmcv 1.2.4 lower bound is requested by mmdet, when mmdet is used.

**Comment by seunghalee1226** [comment]
After re-installing mmdet following https://github.com/open-mmlab/mmdetection/issues/1554#issuecomment-558655512,
I found that the verification of mmtracking works.
Furthermore, because of the assertion error, 1.2.4 <= mmcv <= 1.4.0 , i installed mmcv-full==1.2.7.

**Comment by innerlee** [comment]
`args.device.lower()` shold be look like "cuda:0", as the default value for the device argument in https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_pose_tracking_demo_with_mmtracking.py#L53

**Comment by seunghalee1226** [comment]
I tried to conduct command like this in tutorial, but i got new error.....

My command
```
python demo/top_down_pose_tracking_demo_with_mmtracking.py \
    demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py \
    configs/top_down/resnet/coco/res50_coco_256x192.py \
    https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth \
    --video-path demo/demo.mp4 \
    --out-video-root vis_results
```


error
```
UserWarning: In rpn_proposal or test_cfg, nms_thr has been moved to a dict named nms as iou_threshold, max_num has been renamed as max_per_img, name of original arguments and the way to specify iou_threshold of NMS will be deprecated.
```

**Comment by innerlee** [comment]
Warnings should not affect the final result.

**Comment by seunghalee1226** [comment]
@innerlee  OK, Thanks !

**Comment by JeremyCKT** [comment]
I've already installed mmdet and mmtrack, but I also have the same problem.

`python3 demo/top_down_video_demo_with_mmdet.py \ demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \ https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \ configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py \ https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth \ --video-path 01.MOV  --out-video-root Output01.mp4`

Traceback (most recent call last):
  File "demo/top_down_video_demo_with_mmdet.py", line 173, in <module>
    main()
  File "demo/top_down_video_demo_with_mmdet.py", line 84, in main
    assert has_mmdet, 'Please install mmdet to run the demo.'
AssertionError: Please install mmdet to run the demo.

`python3 demo/top_down_pose_tracking_demo_with_mmtracking.py \ demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py \ configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py \ https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth \ --video-path 01.MOV  --out-video-root vis_results`

Traceback (most recent call last):
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 164, in <module>
    main()
  File "demo/top_down_pose_tracking_demo_with_mmtracking.py", line 72, in main
    assert has_mmtrack, 'Please install mmtrack to run the demo.'
AssertionError: Please install mmtrack to run the demo.

How to fix it? Thanks!

**Comment by innerlee** [comment]
Open a python terminal, type

```python
from mmdet.apis import inference_detector, init_detector
```

**Comment by JeremyCKT** [comment]
> Open a python terminal, type
> 
> ```python
> from mmdet.apis import inference_detector, init_detector
> ```

It shows error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeremyckt/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/jeremyckt/mmdetection/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIPool
  File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by jin-s13** [comment]
Please uninstall all mmcv & mmcv-full in your system, and reinstall the latest mmcv-full.

**Comment by wangm-word** [comment]
> > Open a python terminal, type
> > ```python
> > from mmdet.apis import inference_detector, init_detector
> > ```
> 
> It shows error
> 
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/jeremyckt/mmdetection/mmdet/apis/**init**.py", line 1, in
> from .inference import (async_inference_detector, inference_detector,
> File "/home/jeremyckt/mmdetection/mmdet/apis/inference.py", line 6, in
> from mmcv.ops import RoIPool
> File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/**init**.py", line 1, in
> from .bbox import bbox_overlaps
> File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in
> ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
> File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
> ext = importlib.import_module('mmcv.' + name)
> File "/home/jeremyckt/anaconda3/envs/open-mmlab/lib/python3.7/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named 'mmcv._ext'

@JeremyCKT have you solved this proplem ,i meet too
