### ISSUE TITLE
(TopDown Inference) IndexError: tuple index out of range

### ISSUE THREAD

**Issue by HoBeom** [open-mmlab/mmpose#568]
**Describe the bug**

IndexError: tuple index out of range

**Reproduction**
```
python demo/top_down_pose_tracking_demo_with_mmdet.py  \
demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/top_down/resnet/coco/res50_coco_256x192.py \
    https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth \
    --video-path /dev/video0 \
    --show
```

**Environment**

Docker env
 
**Error traceback**

```
Use load_from_http loader
Use load_from_http loader
Traceback (most recent call last):
  File "demo/top_down_pose_tracking_demo_with_mmdet.py", line 177, in <module>
    main()
  File "demo/top_down_pose_tracking_demo_with_mmdet.py", line 132, in main
    pose_results, returned_outputs = inference_top_down_pose_model(
  File "/mmpose/mmpose/apis/inference.py", line 370, in inference_top_down_pose_model
    assert bboxes.shape[1] == 5
IndexError: tuple index out of range
```
**Exception handling is not exist when the human bounding boxes are not detected**

**Bug fix**
https://github.com/open-mmlab/mmpose/blob/dc7adc2d11f4b752cc089e3ba7b57f0fbc3cce77/mmpose/apis/inference.py#L364
ADD
```
    if len(person_results) == 0:
        return pose_results, returned_outputs
```

**Comment by innerlee** [comment]
Thanks for the report!
