### ISSUE TITLE
pytorch2onnx.py  lite_hrnet error

### ISSUE THREAD

**Issue by zhepherd** [open-mmlab/mmpose#585]
```bash
/data1/control/project/mmpose/mmpose/models/backbones/utils/channel_shuffle.py:20: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (num_channels % groups == 0), ('num_channels should be '
Traceback (most recent call last):
  File "pytorch2onnx.py", line 154, in <module>
    verify=args.verify)
  File "pytorch2onnx.py", line 76, in pytorch2onnx
    opset_version=12) #opset_version
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/data1/control/software/anaconda3.8/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 81, in _parse_arg
    "', since it's not constant, please try to make "
RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
```

**Comment by innerlee** [comment]
@grimoire could you offer some tips?

**Comment by grimoire** [comment]
Hi @zhepherd 
This error is caused by [adaptive_avg_pool2d](https://github.com/HRNet/Lite-HRNet/blob/b4c0ae489af4e2bd8244884217eef0ac9f7a3306/models/backbones/litehrnet.py#L86) in `CrossResolutionWeighting`

ONNX does not have perfect dynamic shape support for `adaptive_avg_pool2d`, So the pooling size has to be a constant value. (Unless pooling size=1, which will use Global pooling node instead.)

As a temporary solution, you can cast the pooling size to int.

```python
        mini_size = [int(v) for v in mini_size]
        out = [F.adaptive_avg_pool2d(s, mini_size) for s in x[:-1]] + [x[-1]]
```

**Comment by zhepherd** [comment]
> Hi @zhepherd
> This error is caused by [adaptive_avg_pool2d](https://github.com/HRNet/Lite-HRNet/blob/b4c0ae489af4e2bd8244884217eef0ac9f7a3306/models/backbones/litehrnet.py#L86) in `CrossResolutionWeighting`
> 
> ONNX does not have perfect dynamic shape support for `adaptive_avg_pool2d`, So the pooling size has to be a constant value. (Unless pooling size=1, which will use Global pooling node instead.)
> 
> As a temporary solution, you can cast the pooling size to int.
> 
> ```python
>         mini_size = [int(v) for v in mini_size]
>         out = [F.adaptive_avg_pool2d(s, mini_size) for s in x[:-1]] + [x[-1]]
> ```

thx for your help, i'll try~

**Comment by zhepherd** [comment]
> Hi @zhepherd
> This error is caused by [adaptive_avg_pool2d](https://github.com/HRNet/Lite-HRNet/blob/b4c0ae489af4e2bd8244884217eef0ac9f7a3306/models/backbones/litehrnet.py#L86) in `CrossResolutionWeighting`
> 
> ONNX does not have perfect dynamic shape support for `adaptive_avg_pool2d`, So the pooling size has to be a constant value. (Unless pooling size=1, which will use Global pooling node instead.)
> 
> As a temporary solution, you can cast the pooling size to int.
> 
> ```python
>         mini_size = [int(v) for v in mini_size]
>         out = [F.adaptive_avg_pool2d(s, mini_size) for s in x[:-1]] + [x[-1]]
> ```

thx for your help, i'll try~  BTW，why  add convert to int is ok?

**Comment by zhepherd** [comment]
> Hi @zhepherd
> This error is caused by [adaptive_avg_pool2d](https://github.com/HRNet/Lite-HRNet/blob/b4c0ae489af4e2bd8244884217eef0ac9f7a3306/models/backbones/litehrnet.py#L86) in `CrossResolutionWeighting`
> 
> ONNX does not have perfect dynamic shape support for `adaptive_avg_pool2d`, So the pooling size has to be a constant value. (Unless pooling size=1, which will use Global pooling node instead.)
> 
> As a temporary solution, you can cast the pooling size to int.
> 
> ```python
>         mini_size = [int(v) for v in mini_size]
>         out = [F.adaptive_avg_pool2d(s, mini_size) for s in x[:-1]] + [x[-1]]
> ```

thx for your help, i'll try~ BTW，why convert to int is ok?

**Comment by grimoire** [comment]
Convert tensor (include shape tensor) to python integer will **NOT** be recorded in PyTorch->ONNX tracing. The value will be treated as a constant.

**Comment by zhepherd** [comment]
> Convert tensor (include shape tensor) to python integer will **NOT** be recorded in PyTorch->ONNX tracing. The value will be treated as a constant.

thx，i have convert to onnx succeed and results is the same，but onnx to mnn also succeed，but the result is wrong ，why？

**Comment by ko440124** [comment]
Hi, I met the same error just like yours. I tried
`
mini_size = [int(v) for v in mini_size]
out = [F.adaptive_avg_pool2d(s, mini_size) for s in x[:-1]] + [x[-1]]
`

an other error occurs:

`
Traceback (most recent call last):
  File "/home/lai/code/mmpose/tools/pytorch2onnx.py", line 158, in <module>
    verify=args.verify)
  File "/home/lai/code/mmpose/tools/pytorch2onnx.py", line 74, in pytorch2onnx
    opset_version=opset_version)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/utils.py", line 467, in _model_to_graph
    module=module)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/lai/anaconda3/envs/mindspore/lib/python3.7/site-packages/mmcv/onnx/symbolic.py", line 333, in symbolic_fn
    '[Adaptive pool]:input size not accessible')
NotImplementedError: [Adaptive pool]:input size not accessible
`

Any suggestion will be grateful.
