### ISSUE TITLE
Topdown demo failed

### ISSUE THREAD

**Issue by ioctl-user** [open-mmlab/mmpose#593]
I have built environment with the project Docker file, downloaded mmdetection project to the output directory, installed mmdet and other required packages, prepared input video and run test:

```
# python demo/top_down_video_demo_with_mmdet.py --device=cpu output/mmdetection/configs/vfnet/vfnet_x101_32x4d_fpn_mdconv_c3-c5_mstrain_2x_coco.py https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmdetection/v2.0/vfnet/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco_20201027pth-b5f6da5e.pth  configs/top_down/hrnet/coco/hrnet_w48_coco_384x288.py  https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288-314c8528_20200708.pth --video-path output/input/input.mkv --out-video-root output/hrnet_w48_coco_384x288/

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "demo/top_down_video_demo_with_mmdet.py", line 6, in <module>
    from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
  File "/mmpose/mmpose/apis/__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "/mmpose/mmpose/apis/inference.py", line 10, in <module>
    from mmpose.datasets.pipelines import Compose
  File "/mmpose/mmpose/datasets/__init__.py", line 6, in <module>
    from .datasets import (  # isort:skip
  File "/mmpose/mmpose/datasets/datasets/__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/mmpose/mmpose/deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "/mmpose/mmpose/datasets/datasets/top_down/__init__.py", line 1, in <module>
    from .topdown_aic_dataset import TopDownAicDataset
  File "/mmpose/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py", line 4, in <module>
    from xtcocotools.coco import COCO
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/coco.py", line 59, in <module>
    from . import mask as maskUtils
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

```

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmpose/issues/534

**Comment by ioctl-user** [comment]
I did "conda update numpy" and nothing changed. Conda has no numpy 1.20:

```
# conda search numpy | tail
numpy                         1.19.1  py38h30dfecb_0  pkgs/main           
numpy                         1.19.1  py38hbc911f0_0  pkgs/main           
numpy                         1.19.2  py36h54aff64_0  pkgs/main           
numpy                         1.19.2  py36h6163131_0  pkgs/main           
numpy                         1.19.2  py37h54aff64_0  pkgs/main           
numpy                         1.19.2  py37h6163131_0  pkgs/main           
numpy                         1.19.2  py38h54aff64_0  pkgs/main           
numpy                         1.19.2  py38h6163131_0  pkgs/main           
numpy                         1.19.2  py39h87658db_0  pkgs/main           
numpy                         1.19.2  py39h89c1606_0  pkgs/main           
```

How can I install newer version?

**Comment by ioctl-user** [comment]
I have updated conda with the following command: "conda update -c conda-forge numpy" .

New error:

```
# python demo/top_down_video_demo_with_mmdet.py --device=cpu output/mmdetection/configs/vfnet/vfnet_x101_32x4d_fpn_mdconv_c3-c5_mstrain_2x_coco.py https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmdetection/v2.0/vfnet/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco_20201027pth-b5f6da5e.pth  configs/top_down/hrnet/coco/hrnet_w48_coco_384x288.py  https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288-314c8528_20200708.pth --video-path output/input/input.mkv --out-video-root output/hrnet_w48_coco_384x288/
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Use load_from_http loader
Downloading: "https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmdetection/v2.0/vfnet/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco_20201027pth-b5f6da5e.pth" to /root/.cache/torch/hub/checkpoints/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco_20201027pth-b5f6da5e.pth
100%|█████████████████████████████████████████| 377M/377M [22:08<00:00, 298kB/s]
Traceback (most recent call last):
  File "demo/top_down_video_demo_with_mmdet.py", line 161, in <module>
    main()
  File "demo/top_down_video_demo_with_mmdet.py", line 84, in main
    args.det_config, args.det_checkpoint, device=args.device.lower())
  File "/opt/conda/lib/python3.7/site-packages/mmdet/apis/inference.py", line 42, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 529, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 467, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/opt/conda/lib/python3.7/site-packages/torch/hub.py", line 490, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile
```

**Comment by innerlee** [comment]
This is an mmdet issue, see https://github.com/open-mmlab/mmdetection/issues/4309

**Comment by ioctl-user** [comment]
> This is an mmdet issue, see open-mmlab/mmdetection#4309

That's my bug.

It seems, this problem is in environment.
When building docker image for mmpose, mmdetection is not installed, so, tests and other mmpose scripts using mmdet cannot be run.

**Comment by innerlee** [comment]
Good point. @jin-s13 we can install a full list of dependencies.

**Comment by ioctl-user** [comment]
Ok. I have installed mmdetection from sources. Here is the next error with the same command:

```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "demo/top_down_video_demo_with_mmdet.py", line 6, in <module>
    from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
  File "/mmpose/mmpose/apis/__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "/mmpose/mmpose/apis/inference.py", line 10, in <module>
    from mmpose.datasets.pipelines import Compose
  File "/mmpose/mmpose/datasets/__init__.py", line 6, in <module>
    from .datasets import (  # isort:skip
  File "/mmpose/mmpose/datasets/datasets/__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/mmpose/mmpose/deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "/mmpose/mmpose/datasets/datasets/top_down/__init__.py", line 10, in <module>
    from .topdown_posetrack18_dataset import TopDownPoseTrack18Dataset
  File "/mmpose/mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py", line 8, in <module>
    from poseval import eval_helpers
ModuleNotFoundError: No module named 'poseval'
```

Please, add poseval to the environment also.
