### ISSUE TITLE
evaluate error after Saving checkpoint

### ISSUE THREAD

**Issue by zxiaoyusq** [open-mmlab/mmpose#601]
HI! I expanded the coco datasets to 25 keypoints,and follow https://github.com/open-mmlab/mmpose/issues/586#issuecomment-822292041 .
But after one epoch of trainning and saving chekpoint:

```bash
2021-04-26 11:14:15,909 - mmpose - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 104125/104125, 15.9 task/s, elapsed: 6562s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/lmd/zxy/mmpose/mmpose/apis/train.py", line 144, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lmd/anaconda3/envs/detection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lmd/anaconda3/envs/detection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/lmd/anaconda3/envs/detection/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lmd/zxy/mmpose/mmpose/core/evaluation/eval_hooks.py", line 101, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/home/lmd/zxy/mmpose/mmpose/core/evaluation/eval_hooks.py", line 121, in evaluate
    results, runner.work_dir, logger=runner.logger, **self.eval_kwargs)
  File "/home/lmd/zxy/mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.py", line 387, in evaluate
    keep = nms(list(img_kpts), oks_thr, sigmas=self.sigmas)
  File "/home/lmd/zxy/mmpose/mmpose/core/post_processing/nms.py", line 116, in oks_nms
    sigmas, vis_thr)
  File "/home/lmd/zxy/mmpose/mmpose/core/post_processing/nms.py", line 81, in oks_iou
    e = (dx**2 + dy**2) / vars / ((a_g + a_d[n_d]) / 2 + np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (25,) (23,) 
```

My dataset has 25 keypoints, but the value of the last two points has not been filled in,the 'keypoints'  in json just like [...0,0,0,0,0,0],I wonder if it's because of this? Thanks！

**Comment by jin-s13** [comment]
It is normal that `keypoints` have [0, 0, 0] for invisible keypoints. So this is not the problem.
Do you know which variable has a shape of (23,)?
Did you modify the sigmas in the dataset to be a np.array of  length 25?

**Comment by zxiaoyusq** [comment]
Do you know which variable has a shape of (23,)?
I will check,thanks!

Did you modify the sigmas in the dataset to be a np.array of length 25?
No,I did't...How do I deceide the value of sigma?

**Comment by jin-s13** [comment]
At least, the length should be 25 (equal to the number of keypoints). 
This is used for nms & evaluation. Please check the homepage of [COCO](https://cocodataset.org/#keypoints-eval) for more information about sigmas.

**Comment by zxiaoyusq** [comment]
the length of sigma caused this porblem,Thanks!

**Comment by alaa-shubbak** [comment]
I have a dataset of only 4 keypoints . 
I got almost a similar error . 
I have the sigma matrix as bellow [0.025, 0.025, 0.025, 0.025] 
what shall be those values ? shall the summation of them equal 1? 
 [here](https://github.com/open-mmlab/mmpose/issues/2046) is my issue script
