### ISSUE TITLE
cant train it

### ISSUE THREAD

**Issue by alicera** [open-mmlab/mmpose#622]
Command:
./tools/dist_train.sh configs/top_down/resnet/coco/res50_coco_384x288.py 4

In the res50_coco_384x288.py I add my data_root = '../COCO'   for coco

The error log:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 14, in <module>
    from mmpose.apis import train_model
  File "/work/Pictures/POSE/mmpose/mmpose/apis/__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "/work/Pictures/POSE/mmpose/mmpose/apis/inference.py", line 10, in <module>
    from mmpose.datasets.pipelines import Compose
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/__init__.py", line 6, in <module>
    from .datasets import (  # isort:skip
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/work/Pictures/POSE/mmpose/mmpose/deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/__init__.py", line 1, in <module>
    from .topdown_aic_dataset import TopDownAicDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py", line 4, in <module>
    from xtcocotools.coco import COCO
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/coco.py", line 59, in <module>
    from . import mask as maskUtils
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "./tools/train.py", line 14, in <module>
    from mmpose.apis import train_model
  File "/work/Pictures/POSE/mmpose/mmpose/apis/__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "/work/Pictures/POSE/mmpose/mmpose/apis/inference.py", line 10, in <module>
    from mmpose.datasets.pipelines import Compose
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/__init__.py", line 6, in <module>
    from .datasets import (  # isort:skip
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/work/Pictures/POSE/mmpose/mmpose/deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/__init__.py", line 1, in <module>
    from .topdown_aic_dataset import TopDownAicDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py", line 4, in <module>
    from xtcocotools.coco import COCO
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/coco.py", line 59, in <module>
    from . import mask as maskUtils
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "./tools/train.py", line 14, in <module>
    from mmpose.apis import train_model
  File "/work/Pictures/POSE/mmpose/mmpose/apis/__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "/work/Pictures/POSE/mmpose/mmpose/apis/inference.py", line 10, in <module>
    from mmpose.datasets.pipelines import Compose
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/__init__.py", line 6, in <module>
    from .datasets import (  # isort:skip
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/work/Pictures/POSE/mmpose/mmpose/deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/__init__.py", line 1, in <module>
    from .topdown_aic_dataset import TopDownAicDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py", line 4, in <module>
    from xtcocotools.coco import COCO
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/coco.py", line 59, in <module>
    from . import mask as maskUtils
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "./tools/train.py", line 14, in <module>
    from mmpose.apis import train_model
  File "/work/Pictures/POSE/mmpose/mmpose/apis/__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "/work/Pictures/POSE/mmpose/mmpose/apis/inference.py", line 10, in <module>
    from mmpose.datasets.pipelines import Compose
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/__init__.py", line 6, in <module>
    from .datasets import (  # isort:skip
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/work/Pictures/POSE/mmpose/mmpose/deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/__init__.py", line 1, in <module>
    from .topdown_aic_dataset import TopDownAicDataset
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py", line 4, in <module>
    from xtcocotools.coco import COCO
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/coco.py", line 59, in <module>
    from . import mask as maskUtils
  File "/opt/conda/lib/python3.7/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/top_down/resnet/coco/res50_coco_384x288.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by alicera** [comment]
I solve it with https://github.com/svenkreiss/poseval
Install from a local clone:
git clone https://github.com/svenkreiss/poseval.git
cd poseval
pip install -e .  # install the local package ('.') in editable mode ('-e')


but meet another error
The error message
FileNotFoundErrorFileNotFoundErrorFileNotFoundErrorFileNotFoundError: : : : TopDownCocoDataset: [Errno 2] No such file or directory: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'TopDownCocoDataset: [Errno 2] No such file or directory: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'TopDownCocoDataset: [Errno 2] No such file or directory: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'TopDownCocoDataset: [Errno 2] No such file or directory: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'


What is the COCO_val2017_detections_AP_H_56_person?
https://drive.google.com/drive/folders/1Wy5oq9ac1tTgGy67wR1Uu8djSDnf0pOL

**Comment by jin-s13** [comment]
Please follow https://github.com/open-mmlab/mmpose/blob/master/docs/tasks/2d_body_keypoint.md#coco to prepare data.
COCO_val2017_detections_AP_H_56_person is the object detection result.

**Comment by alicera** [comment]
How to set the epoch for save ?
I cant find it

**Comment by jin-s13** [comment]
set `checkpoint_config` in the config.
Please check this [tutorial](https://github.com/open-mmlab/mmpose/blob/master/docs/tutorials/0_config.md) about config.

**Comment by alicera** [comment]
Thanks for your help

I meet another probelm 
I runt the hrnet button up

error

Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 162, in main
    meta=meta)
  File "/work/Pictures/POSE/mmpose/mmpose/apis/train.py", line 144, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 347, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 973, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 998, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/bottom_up/bottom_up_base_dataset.py", line 84, in __getitem__
    return self.prepare_train_img(idx)
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/datasets/bottom_up/bottom_up_base_dataset.py", line 71, in prepare_train_img
    return self.pipeline(results)
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/pipelines/shared_transform.py", line 87, in __call__
    data = t(data)
  File "/work/Pictures/POSE/mmpose/mmpose/datasets/pipelines/bottom_up_transform.py", line 500, in __call__
    (self.input_size, self.input_size))
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'warpAffine'
> Overload resolution failed:
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type

**Comment by innerlee** [comment]
@alicera Please try the latest master. https://github.com/open-mmlab/mmpose/pull/635 might have fixed it.
