### ISSUE TITLE
Training for bottom_up error

### ISSUE THREAD

**Issue by carollowbee** [open-mmlab/mmpose#659]
Hi,when i run like that:
 ./tools/dist_train.sh configs/bottom_up/higherhrnet/coco/higher_hrnet32_coco_512x512.py 2.

I met an error with:

```python
Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 121, in main
    env_info_dict = collect_env()
  File "/home/carol/PycharmProjects/mmpose-master/mmpose/utils/collect_env.py", line 8, in collect_env
    env_info = collect_basic_env()
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/env.py", line 85, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 121, in main
    env_info_dict = collect_env()
  File "/home/carol/PycharmProjects/mmpose-master/mmpose/utils/collect_env.py", line 8, in collect_env
    env_info = collect_basic_env()
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/env.py", line 85, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/carol/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/carol/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/bottom_up/higherhrnet/coco/higher_hrnet32_coco_512x512.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

I don't know how to solve the problem and my cuda version is 10.2.

**Comment by jin-s13** [comment]
Please try re-installing mmcv-full with cuda version 10.2

**Comment by carollowbee** [comment]
Thank you, the problem has been solved
