### ISSUE TITLE
Numpy and Cython version with xtcocotools

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmpose#677]
When I using numpy==1.19.5, Cython==0.29.19, xtcocotools will raise an error:
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
I solved this problem after upgrade to cython==0.29.23 and numpy==1.20.3.

But mmdet3d requirements numpy<1.20.0.

I hope you could provide a suitable version of these packages and add them to the requirements.txt.

Detailed error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/mmpose/apis/__init__.py", line 1, in <module>
    from .inference import (inference_bottom_up_pose_model,
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/mmpose/apis/inference.py", line 11, in <module>
    from mmpose.datasets.pipelines import Compose
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/mmpose/datasets/__init__.py", line 6, in <module>
    from .datasets import (  # isort:skip
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/mmpose/datasets/datasets/__init__.py", line 1, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/mmpose/deprecated.py", line 2, in <module>
    from .datasets.datasets.top_down.topdown_base_dataset import TopDownBaseDataset
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/mmpose/datasets/datasets/top_down/__init__.py", line 1, in <module>
    from .topdown_aic_dataset import TopDownAicDataset
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py", line 4, i
n <module>
    from xtcocotools.coco import COCO
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/xtcocotools/coco.py", line 59, in <module>
    from . import mask as maskUtils
  File "/mnt/lustre/rangilyu/anaconda3/envs/mmcli/lib/python3.7/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by innerlee** [comment]
Please raise an issue on mmdet3d to support higher np version.

**Comment by ZwwWayne** [comment]
This issue can be resolved by `pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'`.
