### ISSUE TITLE
top_down_img_demo_with_mmdet.py  other models  exclude onrhand10k-data are NotImplemented for hand pose ?

### ISSUE THREAD

**Issue by Gzzgz** [open-mmlab/mmpose#708]
eg:

```bash
python demo/top_down_img_demo_with_mmdet.py demo/mmdetection_cfg/cascade_rcnn_x101_64x4d_fpn_1class.py     https://download.openmmlab.com/mmpose/mmdet_pretrained/cascade_rcnn_x101_64x4d_fpn_20e_onehand10k-dac19597_20201030.pth     configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_w18_rhd2d_256x256_udp.py  /root/Downloads/hrnetv2_w18_rhd2d_256x256_udp-63ba6007_20210330.pth      --img-root tests/data/rhd/     --img 00111.png     --out-img-root vis_results

Use load_from_http loader
Use load_from_local loader
Traceback (most recent call last):
  File "demo/top_down_img_demo_with_mmdet.py", line 136, in <module>
    main()
  File "demo/top_down_img_demo_with_mmdet.py", line 116, in main
    outputs=output_layer_names)
  File "/root/lj28/project/git-code/mmpose/mmpose/apis/inference.py", line 402, in inference_top_down_pose_model
    return_heatmap=return_heatmap)
  File "/root/lj28/project/git-code/mmpose/mmpose/apis/inference.py", line 266, in _inference_single_pose_model
    raise NotImplementedError()
```
THX

**Comment by jin-s13** [comment]
We are also planning to refactor the codes about the datasets. #663 
This will make it more easily to support a new dataset.

**Comment by Gzzgz** [comment]
OK  THX
