### ISSUE TITLE
训练Lite-Hrnet代码报错

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#724]
Traceback (most recent call last):
  File "tools/train.py", line 17, in <module>
    from models import build_posenet
  File "/home/sa/workspace/zap/Lite-HRNet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa
  File "/home/sa/workspace/zap/Lite-HRNet/models/backbones/__init__.py", line 1, in <module>
    from .litehrnet import LiteHRNet
  File "/home/sa/workspace/zap/Lite-HRNet/models/backbones/litehrnet.py", line 12, in <module>
    from mmpose.models.registry import BACKBONES     
ModuleNotFoundError: No module named 'mmpose.models.registry'

**Comment by innerlee** [comment]
mmpose recently moved the location of registries. https://github.com/open-mmlab/mmpose/pull/669 . It was a breaking change. Downstream repos might be affected by this.

Maybe @ly015 could add some compatibility back?

**Comment by ly015** [comment]
Will be fixed in #731
