### ISSUE TITLE
mmpose不支持TopDownAicDataset数据格式吗？

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmpose#726]
Traceback (most recent call last):
  File "tools/train.py", line 167, in <module>
    main()
  File "tools/train.py", line 142, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/sa/workspace/zap/mmpose/mmpose/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/sa/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: TopDownAicDataset:

**Comment by innerlee** [comment]
Please provide the full command to reproduce this error.

**Comment by innerlee** [comment]
Kindly ping

**Comment by jin-s13** [comment]
Closed due to inactivity.
