### ISSUE TITLE
Failed to install mmcv

### ISSUE THREAD

**Issue by N1M49** [open-mmlab/mmpose#869]
**Description**

Failed to install mmcv

**Reproduction**

Windows
Cuda: 10.1

Followed the install instructions, however, the following command failed to install mmcv
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/10.1/torch1.8.0/index.html
```

**Error traceback**

```
Building wheels for collected packages: mmcv-full
  Building wheel for mmcv-full (setup.py) ... error
  ERROR: Command errored out with exit status 1:
.
.
.
Traceback (most recent call last):
    File "C:\Users\user\.conda\envs\open-mmlab-env\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninja_build
      env=env)
    File "C:\Users\user\.conda\envs\open-mmlab-env\lib\subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.
.
.
.

  RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
```

**Comment by jin-s13** [comment]
Please also raise an issue in mmcv.

**Comment by innerlee** [comment]
Please make sure the cuda version is 10.1 and torch version is 1.8.0, as shown in your command 

![image](https://user-images.githubusercontent.com/9464825/129866872-8694d0db-3c11-4cce-83f2-9771e864b6cf.png)

See https://github.com/open-mmlab/mmcv#installation for detailed instructions
