### ISSUE TITLE
Unable to load certain checkpoint files through url link due  to older Pytorch version (1.6.0) 

### ISSUE THREAD

**Issue by liqikai9** [open-mmlab/mmpose#904]
When I was trying to run the benchmark regression test task, I tried to load the previously released checkpoints through the URL [link](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/rsn_coco.md)  given in the codebase. But I encountered some errors. It seemed that pytorch can not load the checkpoint file successfully.

**Reproduction**
I run the following script for a test task:
```
MASTER_PORT=42490 GPUS=1 GPUS_PER_NODE=1 CPUS_PER_TASK=5 ./tools/slurm_test.sh mm_human test_rsn18_coco_256x192 \
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/rsn18_coco_256x192.py \
https://download.openmmlab.com/mmpose/top_down/rsn/rsn18_coco_256x192-72f4b4a7_20201127.pth \
 --work-dir work_dirs/benchmark_regression_test_2021_08_31_18_04/test_rsn18_coco_256x192
```

The config I used was:
```
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/rsn18_coco_256x192.py
```
And I did not modified any files to the code. 
The dataset used is COCO.

**Environment**
The related environment I used was:
```
No CUDA runtime is found, using CUDA_HOME='/mnt/cache/share/polaris/dep/cuda-10.1-cudnn7.6.5'
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: False
GCC: gcc (GCC) 5.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 5.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash N/A)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parame
ter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format, PERF_WITH_AVX=1, PERF_WITH_AVX2=1,
 PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.3
MMCV: 1.3.10
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a
MMPose: 0.17.0+5f3c176
```

**Error traceback**

```
Traceback (most recent call last):                                                                                                                                                                          
  File "tools/test.py", line 160, in <module>                                                                                                                                                               
    main()                                                                                                                                                                                                  
  File "tools/test.py", line 129, in main                                                                                                                                                                   
    load_checkpoint(model, args.checkpoint, map_location='cpu')                                                                                                                                             
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt1.6/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint                                                                
    checkpoint = _load_checkpoint(filename, map_location, logger)                                                                                                                                           
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt1.6/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint                                                               
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)                                                                                                                                 
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt1.6/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint                                                                
    return checkpoint_loader(filename, map_location)                                                                                                                                                        
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt1.6/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http                                                                 
    filename, model_dir=model_dir, map_location=map_location)                                                                                                                                               
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/hub.py", line 490, in load_state_dict_from_url                                                                    
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')                                                                                                                                  
RuntimeError: Only one file(not dir) is allowed in the zipfile
```

**Bug fix**
I have found a relevant [issue](https://github.com/pytorch/pytorch/issues/42239) in the Pytorch community and the corresponding [fix](https://github.com/pytorch/pytorch/pull/42333). Another documentation on the [Pytorch](https://pytorch.org/docs/stable/generated/torch.save.html?highlight=torch%20save#torch.save) also points out that: the 1.6 release of PyTorch switched `torch.save` to use a new zipfile-based file format. 

So then I tried to use Pytorch 1.9.0 to load this checkpoint and it worked. 
This checkpoint file was saved using Pytorch 1.6.0 version which can be checked by using Pytorch 1.9.0 to load the checkpoint file and read the corresponding key: 
```
from torch.hub import load_state_dict_from_url
checkpoint = load_state_dict_from_url('https://download.openmmlab.com/mmpose/top_down/rsn/rsn18_coco_256x192-72f4b4a7_20201127.pth')
print(checkpoint['meta']['env_info'])
```
So i guessed that the checkpoint may be saved using the new file format so that it can not be loaded by older Pytorch version (<=1.6.0).

**Comment by liqikai9** [comment]
This issue has been fixed through https://github.com/open-mmlab/mmcv/pull/1377.
